/**
 * 254-DS-001 v1.1, Structural Design Protocol for Residential and Light Commercial Work.
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-DS-001_Structural_Design_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 37dd6b2e44155108df1daa681277332ddb64450a0f58813979e538da469ee22b. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const DS001 = {
  "documentNumber": "254-DS-001",
  "title": "Structural Design Protocol for Residential and Light Commercial Work",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Aman Dhakal, P.E., Engineer of Record, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record",
  "appliesTo": "All structural design engagements performed by 254 Engineering Services",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "residential-light-commercial-design",
  "serviceTier": null,
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-DS-001_Structural_Design_Protocol_v1_1.pdf",
  "sourceSha256": "37dd6b2e44155108df1daa681277332ddb64450a0f58813979e538da469ee22b",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "job-information",
      "heading": "JOB INFORMATION",
      "at": "Appendix B"
    },
    {
      "key": "context",
      "heading": "CONTEXT (every visit)",
      "at": "Appendix B"
    },
    {
      "key": "existing-construction-the-design-ties-into",
      "heading": "EXISTING CONSTRUCTION THE DESIGN TIES INTO",
      "at": "Appendix B"
    },
    {
      "key": "engineer-s-job-list",
      "heading": "ENGINEER'S JOB LIST",
      "at": "Appendix B"
    },
    {
      "key": "close-out",
      "heading": "CLOSE-OUT",
      "at": "Appendix B"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the site or structure and mark North. Take a photo of it.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix B, PHOTOS"
    }
  ],
  "intakeQuestions": [
    {
      "number": 1,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & client",
      "ask": "What does the client want designed, in their words? (record exactly)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 2,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & client",
      "ask": "What is the design for? (permit / construction / pricing / lender / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 3,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & client",
      "ask": "Who is the client, and who else is on the project? (owner, architect, contractor)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 4,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & client",
      "ask": "What date does the client need it by?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 5,
      "group": "property-basics",
      "groupHeading": "Project basics",
      "ask": "Property address and county",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 6,
      "group": "property-basics",
      "groupHeading": "Project basics",
      "ask": "Which city or county issues the permit, and which code edition does it enforce?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 7,
      "group": "property-basics",
      "groupHeading": "Project basics",
      "ask": "New building, addition, alteration, or a single element?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 8,
      "group": "property-basics",
      "groupHeading": "Project basics",
      "ask": "Size: floor area, number of stories, and for a single element, what it is",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 9,
      "group": "property-basics",
      "groupHeading": "Project basics",
      "ask": "Construction type wanted, if decided (wood frame / steel / masonry / concrete; slab / pier and beam)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 10,
      "group": "property-basics",
      "groupHeading": "Project basics",
      "ask": "Is the property in a designated catastrophe area where a TDI windstorm certificate will be needed?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 11,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is there existing construction the design ties into or relies on?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 12,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is there no geotechnical report?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 13,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Has construction already started?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 14,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is the client asking the firm to seal drawings prepared by someone else?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 15,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is there an open insurance claim or litigation involving the property?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 16,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is the property in a flood zone?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 17,
      "group": "prior-paperwork",
      "groupHeading": "Documents prompt",
      "ask": "Do you have: architectural drawings, survey, geotechnical report, existing structural drawings, photos, permit comments?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    }
  ],
  "intakeUploads": [
    {
      "key": "architectural-drawings-or-a-dimensioned-sketch-1",
      "what": "Architectural drawings or a dimensioned sketch of what is to be designed",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "photo-of-the-front-of-the-2",
      "what": "Photo of the front of the property or site (confirms address)",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "geotechnical-report-3",
      "what": "Geotechnical report",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "survey-or-site-plan-4",
      "what": "Survey or site plan",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "existing-structural-drawings-5",
      "what": "Existing structural drawings",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "truss-joist-or-metal-building-manufacturer-6",
      "what": "Truss, joist, or metal building manufacturer's drawings",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "permit-comments-from-the-permitting-authority-7",
      "what": "Permit comments from the permitting authority",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "equipment-weights-and-locations-8",
      "what": "Equipment weights and locations",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-job-file-from-another-254-9",
      "what": "Any job file from another 254 service line the design comes from",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    }
  ],
  "checklist": [
    {
      "key": "photo-of-address-marker-house-number",
      "section": "job-information",
      "label": "Photo of address marker (house number, street sign, or mailbox)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "all-four-elevations-of-the-structure",
      "section": "context",
      "label": "All four elevations of the structure, or the site from each side",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-area-where-the-new-work",
      "section": "context",
      "label": "The area where the new work goes, from two directions",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "ground-slope-and-drainage-where-the",
      "section": "context",
      "label": "Ground slope and drainage where the new work goes",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "trees-utilities-and-neighboring-structures-within",
      "section": "context",
      "label": "Trees, utilities, and neighboring structures within 20 feet of the new work",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "foundation-type-and-its-edge-where",
      "section": "existing-construction-the-design-ties-into",
      "label": "Foundation type and its edge where the new work meets it, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "wall-construction-where-the-new-work",
      "section": "existing-construction-the-design-ties-into",
      "label": "Wall construction where the new work meets it: material, stud size and spacing where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "floor-framing-member-size-spacing-span",
      "section": "existing-construction-the-design-ties-into",
      "label": "Floor framing: member size, spacing, span, and direction, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "roof-framing-rafter-or-truss-member",
      "section": "existing-construction-the-design-ties-into",
      "label": "Roof framing: rafter or truss, member size, spacing, span, and pitch, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-beam-post-or-bearing-wall",
      "section": "existing-construction-the-design-ties-into",
      "label": "Each beam, post, or bearing wall near the new work, and what it sits on",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-damage-sag-or-earlier-alteration",
      "section": "existing-construction-the-design-ties-into",
      "label": "Any damage, sag, or earlier alteration near the new work",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "full-perimeter-walk-anything-unusual",
      "section": "close-out",
      "label": "Full perimeter walk: anything unusual",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exception-menu-cleared-for-every-non",
      "section": "close-out",
      "label": "Exception menu cleared for every non-applicable item",
      "photo": false,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    }
  ],
  "determinations": [],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Structural Design Protocol",
    "Document Value",
    "Title Structural Design Protocol for Residential and Light Commercial",
    "Work",
    "Document number 254-DS-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Aman Dhakal, P.E., Engineer of Record, 254 Engineering",
    "Services",
    "Approval Aman Dhakal, P.E., Engineer of Record",
    "Applies to All structural design engagements performed by 254 Engineering",
    "Services",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services performs structural design so that the",
    "engineer can issue sealed drawings and calculations.",
    "Design is the engineer's own original work. No evidence package arrives for review and no",
    "determination is recorded. This protocol sets how a design engagement is scoped, what the",
    "engineer designs from, what is checked before anything is sealed, and what is kept.",
    "2. Scope",
    "This protocol applies to structural design of residential and light commercial structures and elements:",
    "new buildings, additions, alterations, beams and headers for wall removals, foundations, decks,",
    "patio covers, carports, retaining walls, strengthening for rooftop solar, and engineered retrofits that",
    "come out of another service line.",
    "This protocol does not cover architectural, civil, mechanical, electrical, or plumbing design;",
    "geotechnical investigation; design of components that are designed by their manufacturer, such as",
    "trusses and metal buildings, beyond stating the loads and reviewing the submittal; or special",
    "inspection and testing. The firm does not perform forensic or cause-of-loss investigation under this",
    "or any protocol.",
    "3. Governing requirements",
    "• The building code adopted by the authority having jurisdiction and the standards it references.",
    "The coordinator records the authority and the code edition at scoping. The engineer confirms",
    "both and records them on the drawings.",
    "• In the designated catastrophe area, the windstorm building code under the TWIA plan of",
    "operation, where the owner will need a TDI certificate.",
    "• Texas Engineering Practice Act and TBPELS rules, 22 TAC Chapter 137, including the sealing",
    "rules.",
    "• The geotechnical report, where one exists. Where none exists, the engineer states the",
    "assumed soil values on the drawings and that they are assumed.",
    "4. Roles and responsibilities",
    "Only the Engineer of Record decides whether an engagement is accepted, the design basis, and",
    "what is issued. The coordinator relays the engineer's written decisions without interpretation or",
    "addition.",
    "• The engineer prepares the calculations. Drawings are drafted by the engineer or by a drafter",
    "working under the engineer's direct supervision.",
    "• The engineer does not attend the site. Site information comes from the client's documents and,",
    "where the engineer asks for it, from a technician working to a list the engineer writes for that",
    "job.",
    "• The contractor is responsible for means and methods, temporary shoring, and site safety. The",
    "drawings say so.",
    "5. Personnel qualifications",
    "Field Technician",
    "• Qualified under one of the firm's inspection protocols, with a supervised inspection completed.",
    "• Demonstrated ability to measure and sketch existing construction and to read plans.",
    "Drafter",
    "• Works only from the engineer's sketches, markups, and written instructions. Makes no design",
    "decision.",
    "Engineer of Record",
    "• Active Texas P.E. license. A copy, with expiration date, is held in the firm's compliance file.",
    "• The engineer accepts only work within the engineer's area of competence.",
    "6. Intake",
    "• The coordinator opens an engagement file for each request. The file records the scoping",
    "answers and client documents required by Appendix A.",
    "• Every request goes to the engineer. The engineer records accept, accept with conditions, or",
    "decline, under Appendix C.",
    "• On acceptance the engineer writes the design basis: what is being designed, what is not, the",
    "code, the loads, the documents the design relies on, what will be delivered, and the delivery",
    "date.",
    "• The design basis is sent to the client in writing with the proposal. Design does not start until the",
    "client accepts it in writing.",
    "• Delivery is quoted for each engagement. No standard turnaround is published.",
    "7. Scheduling and dispatch",
    "• A technician is dispatched only where the engineer asks for site information, or the owner",
    "orders construction observation, and the engineer writes the job list for it.",
    "• The coordinator schedules the visit within two business days of the engineer's job list. The",
    "engineer may set a different interval in the engagement file.",
    "• An engagement with no site visit is not dispatched.",
    "8. Site information",
    "Where the engineer asks for a site visit, the technician completes every item of Appendix B and",
    "every item on the engineer's job list, and follows the photo procedure printed at the head of that",
    "checklist.",
    "• Before starting, the technician makes a rough sketch of the site or structure, marks North, and",
    "photographs the sketch.",
    "• The technician ticks the item being photographed, photographs the checklist, then takes the",
    "photographs for that item, and moves to the next item the same way.",
    "• Existing construction is measured, not estimated. Every measurement has the tape in frame.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location.",
    "• An observation that cannot be made is recorded as not observed with the reason. The",
    "engineer states on the drawings every existing condition that was assumed and must be",
    "verified by the contractor before work.",
    "9. Design and engineer review",
    "Design",
    "• The engineer designs to the design basis. A change to the design basis is recorded in writing",
    "and sent to the client before the design continues.",
    "• Calculations show the code, the loads, the load path to the foundation, and each member and",
    "connection designed.",
    "• Drawings show the code and design loads, material specifications, every member and",
    "connection designed, the existing conditions assumed, and what is to be designed by others.",
    "Engineer review",
    "• Before anything is sealed, the engineer completes the issue check in Appendix C and records",
    "it in the engagement file.",
    "• A drawing drafted by someone else is checked by the engineer line by line against the",
    "calculations before it is sealed.",
    "• The engineer checks his own work using the issue check. There is no second engineer.",
    "10. Revisions and construction questions",
    "• A document released before it is final is marked preliminary, not for construction, permit, or",
    "bidding, with the engineer's name, license number, and the date. It is not sealed.",
    "• A change after issue is made by a numbered revision, with the change marked and dated, and",
    "sealed again. The superseded sheets stay in the engagement file.",
    "• Plan review comments from the permitting authority are answered by the engineer in writing. A",
    "comment that changes the design is a revision.",
    "• Contractor questions and submittals for the firm's design are answered by the engineer in",
    "writing, from the desk.",
    "• Where the owner orders construction observation, a technician photographs the work at the",
    "stages the engineer lists, to the firm's evidence standard, and the engineer reviews each",
    "package and reports in writing what was observed. The engineer does not attend the site.",
    "• A change in scope beyond the design basis is a new proposal.",
    "11. Design deliverables",
    "• The engineer seals, signs, and dates the final drawings, and the final calculations where the",
    "permitting authority or the client requires them.",
    "• Sealed documents are issued as PDF with the engineer's seal and signature as TBPELS rules",
    "allow. Editable drawing files are not released.",
    "• Each sheet carries the property, the engagement number, the revision, and the date.",
    "• The drawings state that they are for the property and the scope named and are not to be used",
    "for another site.",
    "• The engineer seals only work prepared by the engineer or under the engineer's direct",
    "supervision.",
    "• The firm does not warrant construction and does not forecast future performance.",
    "12. Exclusions",
    "The following are declined. The coordinator records the decision in the engagement file and informs",
    "the client in writing.",
    "• Work outside residential and light commercial structures, or outside the engineer's area of",
    "competence. Declined.",
    "• A request to seal drawings or calculations prepared by others who were not under the",
    "engineer's supervision. Declined.",
    "• A request to design to a code or load less than the adopted code requires. Declined.",
    "• A request tied to an open insurance claim or litigation over existing damage. Declined, with a",
    "referral to an independent firm.",
    "• A design that depends on soil information the client will not obtain, where the engineer finds",
    "assumed values are not appropriate. Declined until a geotechnical report is supplied.",
    "• A client request for a predetermined conclusion. This is an automatic decline and the request",
    "is logged verbatim.",
    "13. Records and retention",
    "• Each engagement file contains: the scoping record and client documents, the engineer's",
    "acceptance record, the design basis and the client's acceptance of it, any site information",
    "package and job list, the calculations, the issue check, every issued document and every",
    "revision, plan review comments and answers, contractor questions and answers, and any",
    "construction observation packages and reports.",
    "• Engagement files are retained for ten years from the date of the last sealed issue. For an",
    "engagement that produces no sealed document, the ten years runs from the date of the",
    "engineer's last recorded decision or closure.",
    "• Ten years is the firm's floor, reviewed against TBPELS rules.",
    "• The compliance file holds the engineer's license records, technician qualification and training",
    "records, and every issued version of this protocol.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the",
    "adopted code or to TBPELS sealing rules.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table.",
    "• This document follows the firm's house protocol format. Appendix A carries the scoping",
    "questions and client documents. Appendix B carries the site information checklist. Appendix C",
    "carries the engineer's decision rules. Appendix D is the reference list.",
    "Appendix A. Scoping questions and client documents",
    "Asked and collected by the coordinator before the request goes to the engineer.",
    "PART 1: SCOPING QUESTIONS",
    "Purpose & client",
    "1. What does the client want designed, in their words? (record exactly)",
    "Answer: ____________________________________________________",
    "2. What is the design for? (permit / construction / pricing / lender / other)",
    "Answer: ____________________________________________________",
    "3. Who is the client, and who else is on the project? (owner, architect, contractor)",
    "Answer: ____________________________________________________",
    "4. What date does the client need it by?",
    "Answer: ____________________________________________________",
    "Project basics",
    "5. Property address and county",
    "Answer: ____________________________________________________",
    "6. Which city or county issues the permit, and which code edition does it enforce?",
    "Answer: ____________________________________________________",
    "7. New building, addition, alteration, or a single element?",
    "Answer: ____________________________________________________",
    "8. Size: floor area, number of stories, and for a single element, what it is",
    "Answer: ____________________________________________________",
    "9. Construction type wanted, if decided (wood frame / steel / masonry / concrete; slab / pier and",
    "beam)",
    "Answer: ____________________________________________________",
    "10. Is the property in a designated catastrophe area where a TDI windstorm certificate will be",
    "needed?",
    "Answer: ____________________________________________________",
    "Flags: recorded for the engineer's acceptance review",
    "11. Is there existing construction the design ties into or relies on?",
    "Yes No If yes, describe: ____________________________________________________",
    "12. Is there no geotechnical report?",
    "Yes No If yes, describe: ____________________________________________________",
    "13. Has construction already started?",
    "Yes No If yes, describe: ____________________________________________________",
    "14. Is the client asking the firm to seal drawings prepared by someone else?",
    "Yes No If yes, describe: ____________________________________________________",
    "15. Is there an open insurance claim or litigation involving the property?",
    "Yes No If yes, describe: ____________________________________________________",
    "16. Is the property in a flood zone?",
    "Yes No If yes, describe: ____________________________________________________",
    "Documents prompt",
    "17. Do you have: architectural drawings, survey, geotechnical report, existing structural drawings,",
    "photos, permit comments?",
    "Answer: ____________________________________________________",
    "PART 2: CLIENT DOCUMENTS (collected at scoping)",
    "Required",
    "-- Architectural drawings or a dimensioned sketch of what is to be designed",
    "-- Photo of the front of the property or site (confirms address)",
    "Required if it exists",
    "-- Geotechnical report",
    "-- Survey or site plan",
    "-- Existing structural drawings",
    "Collect when applicable",
    "-- Truss, joist, or metal building manufacturer's drawings",
    "-- Permit comments from the permitting authority",
    "-- Equipment weights and locations",
    "-- Any job file from another 254 service line the design comes from",
    "Appendix B. Site information checklist",
    "Completed on site by the technician only where the engineer asks for a site visit. A construction",
    "observation visit uses the job information and the engineer's job list. The checklist cannot be",
    "submitted incomplete.",
    "PHOTOS",
    "-- Before starting, make a rough sketch of the site or structure and mark North. Take a photo of it.",
    "-- Tick the item you are about to photograph, take a photo of the checklist, then take the photos for",
    "that item.",
    "-- Move on to the next item the same way.",
    "JOB INFORMATION",
    "Job / Dispatch No.: ____________________________",
    "Property address (full, incl. county):",
    "__________________________________________________________",
    "Technician name: ______________________________________",
    "Date / arrival time / departure time: ________________________________________",
    "Weather during visit: ________________________________________",
    "Contact on site (name, role, phone): ________________________________________________",
    "[ ] Photo of address marker (house number, street sign, or mailbox) [PHOTO]",
    "CONTEXT (every visit)",
    "[ ] All four elevations of the structure, or the site from each side [PHOTO]",
    "[ ] The area where the new work goes, from two directions [PHOTO]",
    "[ ] Ground slope and drainage where the new work goes [PHOTO]",
    "[ ] Trees, utilities, and neighboring structures within 20 feet of the new work [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "EXISTING CONSTRUCTION THE DESIGN TIES INTO",
    "[ ] Foundation type and its edge where the new work meets it, tape in frame [PHOTO]",
    "[ ] Wall construction where the new work meets it: material, stud size and spacing where visible",
    "[PHOTO]",
    "[ ] Floor framing: member size, spacing, span, and direction, tape in frame [PHOTO]",
    "[ ] Roof framing: rafter or truss, member size, spacing, span, and pitch, tape in frame [PHOTO]",
    "[ ] Each beam, post, or bearing wall near the new work, and what it sits on [PHOTO]",
    "[ ] Any damage, sag, or earlier alteration near the new work [PHOTO]",
    "Overall dimensions of the existing structure (ft): ________ x ________ stories ____",
    "Sizes, spacings, and spans measured:",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "ENGINEER'S JOB LIST",
    "Written by the engineer for this engagement. Each line is completed like any other item.",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CLOSE-OUT",
    "[ ] Full perimeter walk: anything unusual [PHOTO]",
    "[ ] Exception menu cleared for every non-applicable item",
    "Total photos: ______________",
    "Technician signature / date: ____________________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Appendix C. Engineer decision rules",
    "Design has no pass or fail determination. The engineer records an acceptance decision at scoping",
    "and an issue check before anything is sealed.",
    "ACCEPT",
    "-- The work is residential or light commercial and within the engineer's area of competence",
    "-- The scoping record and the required client documents are complete",
    "-- The code and the permitting authority are known",
    "-- The design basis can be written from what is in the file",
    "ACCEPT WITH CONDITIONS",
    "-- A site visit is needed, the engineer writes the job list",
    "-- No geotechnical report, the engineer states the assumed soil values or requires a report",
    "-- Existing conditions must be assumed, the engineer lists what the contractor verifies before work",
    "-- Part of the structure is designed by a manufacturer, the engineer states the loads and reviews the",
    "submittal",
    "DECLINE",
    "-- Outside residential and light commercial work, or outside the engineer's area of competence",
    "-- Request to seal work prepared by others not under the engineer's supervision",
    "-- Request to design below the adopted code",
    "-- Open insurance claim or litigation over existing damage, decline, with a referral to an independent",
    "firm",
    "-- Client requests a predetermined conclusion, automatic decline, log verbatim request",
    "ISSUE CHECK (before sealing)",
    "-- Design basis accepted by the client in writing, and the design matches it",
    "-- Code edition and design loads stated on the drawings",
    "-- Load path complete to the foundation, for gravity, wind, and uplift",
    "-- Every member and connection on the drawings has a calculation or a stated prescriptive basis",
    "-- Drawings checked against the calculations, sheet by sheet",
    "-- Existing conditions assumed, and items designed by others, stated on the drawings",
    "-- Revision number and date on every sheet",
    "REVISE AND REISSUE",
    "-- Permit comment that changes the design",
    "-- Error or omission found after issue",
    "-- Site condition reported by the contractor that differs from the drawings",
    "-- Change requested by the client within the design basis",
    "Appendix D. References",
    "Item Location",
    "International Residential",
    "Code",
    "As adopted by the authority having jurisdiction",
    "International Building Code As adopted by the authority having jurisdiction",
    "International Existing",
    "Building Code",
    "As adopted by the authority having jurisdiction",
    "ASCE 7, Minimum Design",
    "Loads and Associated",
    "Criteria for Buildings and",
    "Other Structures",
    "Edition referenced by the adopted code",
    "National Design",
    "Specification for Wood",
    "Construction, American",
    "Wood Council",
    "Edition referenced by the adopted code",
    "ACI 318, Building Code",
    "Requirements for Structural",
    "Concrete",
    "Edition referenced by the adopted code",
    "AISC 360, Specification for",
    "Structural Steel Buildings",
    "Edition referenced by the adopted code",
    "TMS 402, Building Code",
    "Requirements for Masonry",
    "Structures",
    "Edition referenced by the adopted code",
    "28 TAC 5.4601 through",
    "5.4642, Inspections for",
    "Windstorm and Hail",
    "Insurance",
    "Texas Administrative Code",
    "Texas Engineering Practice",
    "Act, Texas Occupations",
    "Code Chapter 1001",
    "statutes.capitol.texas.gov",
    "TBPELS rules, 22 TAC pels.texas.gov",
    "Chapter 137",
    "254-RC-001 Roof",
    "Certification Protocol, v1.1,",
    "issued September 18, 2026",
    "Firm document",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const DS001_COUNTS = [
  {
    "key": "field-1",
    "prompt": "Job / Dispatch No.: ____________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-2",
    "prompt": "Property address (full, incl. county):",
    "at": "Appendix B"
  },
  {
    "key": "field-3",
    "prompt": "Technician name: ______________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-4",
    "prompt": "Date / arrival time / departure time: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-5",
    "prompt": "Weather during visit: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-6",
    "prompt": "Contact on site (name, role, phone): ________________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-7",
    "prompt": "Overall dimensions of the existing structure (ft): ________ x ________ stories ____",
    "at": "Appendix B"
  },
  {
    "key": "field-8",
    "prompt": "Sizes, spacings, and spans measured:",
    "at": "Appendix B"
  },
  {
    "key": "field-9",
    "prompt": "Total photos: ______________",
    "at": "Appendix B"
  },
  {
    "key": "field-10",
    "prompt": "Technician signature / date: ____________________________________________",
    "at": "Appendix B"
  }
];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const DS001_OTHER_RULES = [
  {
    "key": "accept",
    "heading": "ACCEPT",
    "effect": null,
    "criteria": [
      "The work is residential or light commercial and within the engineer's area of competence",
      "The scoping record and the required client documents are complete",
      "The code and the permitting authority are known",
      "The design basis can be written from what is in the file"
    ],
    "at": "Appendix C"
  },
  {
    "key": "accept-with-conditions",
    "heading": "ACCEPT WITH CONDITIONS",
    "effect": null,
    "criteria": [
      "A site visit is needed, the engineer writes the job list",
      "No geotechnical report, the engineer states the assumed soil values or requires a report",
      "Existing conditions must be assumed, the engineer lists what the contractor verifies before work",
      "Part of the structure is designed by a manufacturer, the engineer states the loads and reviews the submittal"
    ],
    "at": "Appendix C"
  },
  {
    "key": "decline",
    "heading": "DECLINE",
    "effect": null,
    "criteria": [
      "Outside residential and light commercial work, or outside the engineer's area of competence",
      "Request to seal work prepared by others not under the engineer's supervision",
      "Request to design below the adopted code",
      "Open insurance claim or litigation over existing damage, decline, with a referral to an independent firm",
      "Client requests a predetermined conclusion, automatic decline, log verbatim request"
    ],
    "at": "Appendix C"
  },
  {
    "key": "issue-check",
    "heading": "ISSUE CHECK (before sealing)",
    "effect": "before sealing",
    "criteria": [
      "Design basis accepted by the client in writing, and the design matches it",
      "Code edition and design loads stated on the drawings",
      "Load path complete to the foundation, for gravity, wind, and uplift",
      "Every member and connection on the drawings has a calculation or a stated prescriptive basis",
      "Drawings checked against the calculations, sheet by sheet",
      "Existing conditions assumed, and items designed by others, stated on the drawings",
      "Revision number and date on every sheet"
    ],
    "at": "Appendix C"
  },
  {
    "key": "revise-and-reissue",
    "heading": "REVISE AND REISSUE",
    "effect": null,
    "criteria": [
      "Permit comment that changes the design",
      "Error or omission found after issue",
      "Site condition reported by the contractor that differs from the drawings",
      "Change requested by the client within the design basis"
    ],
    "at": "Appendix C"
  }
];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const DS001_BLANK_JOB_LIST_ITEMS = 5;
