/**
 * 254-MH-001 v1.1, Manufactured Home Foundation Certification Protocol.
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-MH-001_Manufactured_Home_Foundation_Certification_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 5c88c73d9815cfae6825ef82d4368dd66a98dce746deed91b3c351cf2df09d4a. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const MH001 = {
  "documentNumber": "254-MH-001",
  "title": "Manufactured Home Foundation Certification Protocol",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Aman Dhakal, P.E., Engineer of Record, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record",
  "appliesTo": "All manufactured home foundation certification engagements performed by 254 Engineering Services",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "manufactured-home-foundation-certifications",
  "serviceTier": null,
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-MH-001_Manufactured_Home_Foundation_Certification_Protocol_v1_1.pdf",
  "sourceSha256": "5c88c73d9815cfae6825ef82d4368dd66a98dce746deed91b3c351cf2df09d4a",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "job-information",
      "heading": "JOB INFORMATION",
      "at": "Appendix B"
    },
    {
      "key": "home-identification",
      "heading": "HOME IDENTIFICATION",
      "at": "Appendix B"
    },
    {
      "key": "site",
      "heading": "SITE",
      "at": "Appendix B"
    },
    {
      "key": "running-gear",
      "heading": "RUNNING GEAR",
      "at": "Appendix B"
    },
    {
      "key": "perimeter-enclosure",
      "heading": "PERIMETER ENCLOSURE",
      "at": "Appendix B"
    },
    {
      "key": "under-the-home",
      "heading": "UNDER THE HOME",
      "at": "Appendix B"
    },
    {
      "key": "anchorage",
      "heading": "ANCHORAGE",
      "at": "Appendix B"
    },
    {
      "key": "additions",
      "heading": "ADDITIONS",
      "at": "Appendix B"
    },
    {
      "key": "utilities",
      "heading": "UTILITIES",
      "at": "Appendix B"
    },
    {
      "key": "close-out",
      "heading": "CLOSE-OUT",
      "at": "Appendix B"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the home and any additions and mark North. Take a photo of it.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix B, PHOTOS"
    }
  ],
  "intakeQuestions": [
    {
      "number": 1,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Who requires the certification? (lender name and loan type: FHA / VA / USDA / conventional / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 2,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What does the lender's request say? (record exactly, or attach it)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 3,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Who will the certification be addressed to?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 4,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What deadline is the customer working against, if any?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 5,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property address and county",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 6,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Manufacturer and serial number, if known",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 7,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Single-section or multi-section",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 8,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Year the home was installed at this site",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 9,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "What the home sits on, as the customer understands it (piers and tie-downs / slab / perimeter wall / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 10,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Was the home built before June 15, 1976?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 11,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has the home been moved since it was first installed?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 12,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Are the HUD labels or the data plate missing?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 13,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has anything been added to the home? (room, porch, deck, carport, roof-over)",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 14,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Does the lender name a requirement other than the HUD Permanent Foundations Guide?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 15,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is the property in a flood zone?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 16,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has another engineer or inspector already declined to certify this foundation?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 17,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there an open insurance claim or litigation involving the foundation?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 18,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Is there an opening to get under the home, and is the space dry?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 19,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Occupied or vacant? Accessible if occupied?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 20,
      "group": "prior-paperwork",
      "groupHeading": "Prior paperwork prompt",
      "ask": "Do you have: the foundation plans the home was set on, an earlier foundation certification, installation report, tie-down or anchor paperwork, survey, flood elevation certificate, permits for additions?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    }
  ],
  "intakeUploads": [
    {
      "key": "photo-of-the-front-of-the-1",
      "what": "Photo of the front of the property (confirms address/structure)",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "the-lender-s-written-request-for-2",
      "what": "The lender's written request for the certification",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "foundation-plans-or-drawings-used-for-3",
      "what": "Foundation plans or drawings used for the home's foundation",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-earlier-foundation-certification-or-engineer-4",
      "what": "Any earlier foundation certification or engineer letter",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "flood-elevation-certificate-required-where-the-5",
      "what": "Flood elevation certificate (required where the property is in a flood zone)",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "installation-report-or-installer-paperwork-6",
      "what": "Installation report or installer paperwork",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "anchor-or-tie-down-system-paperwork-7",
      "what": "Anchor or tie-down system paperwork",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "permits-and-drawings-for-additions-8",
      "what": "Permits and drawings for additions",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "appraisal-pages-noting-additions-or-alterations-9",
      "what": "Appraisal pages noting additions or alterations",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    }
  ],
  "checklist": [
    {
      "key": "photo-of-address-marker-house-number",
      "section": "job-information",
      "label": "Photo of address marker (house number, street sign, or mailbox)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "all-four-elevations-of-the-home",
      "section": "home-identification",
      "label": "All four elevations of the home",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "hud-label-on-each-section-every",
      "section": "home-identification",
      "label": "HUD label on each section, every digit readable",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "data-plate-inside-the-home-kitchen",
      "section": "home-identification",
      "label": "Data plate inside the home (kitchen cabinet, bedroom closet, or electrical panel)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "serial-number-stamped-on-the-front",
      "section": "home-identification",
      "label": "Serial number stamped on the front cross member of the frame",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "ground-slope-and-drainage-on-each",
      "section": "site",
      "label": "Ground slope and drainage on each side of the home",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "standing-water-ponding-or-erosion-at",
      "section": "site",
      "label": "Standing water, ponding, or erosion at or under the home",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "downspout-and-drain-discharge-points",
      "section": "site",
      "label": "Downspout and drain discharge points",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "towing-hitch-removed-or-still-attached",
      "section": "running-gear",
      "label": "Towing hitch: removed or still attached",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "axles-and-wheels-removed-or-still",
      "section": "running-gear",
      "label": "Axles and wheels: removed or still attached",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "enclosure-on-each-side-material-and",
      "section": "perimeter-enclosure",
      "label": "Enclosure on each side: material and whether it is continuous",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "how-the-enclosure-is-fastened-at",
      "section": "perimeter-enclosure",
      "label": "How the enclosure is fastened at the top and what it sits on at the bottom",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "access-opening-tape-across-width-and",
      "section": "perimeter-enclosure",
      "label": "Access opening, tape across width and height",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-vent",
      "section": "perimeter-enclosure",
      "label": "Every vent",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "overview-from-the-access-opening-and",
      "section": "under-the-home",
      "label": "Overview from the access opening, and looking down the length of each chassis beam",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "clearance-from-ground-to-the-bottom",
      "section": "under-the-home",
      "label": "Clearance from ground to the bottom of the chassis beam at the lowest point, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "ground-cover-or-vapor-barrier-and",
      "section": "under-the-home",
      "label": "Ground cover or vapor barrier, and any wet soil",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "footings-typical-and-worst-tape-across",
      "section": "under-the-home",
      "label": "Footings: typical and worst, tape across length and width, thickness where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "piers-typical-and-worst-on-each",
      "section": "under-the-home",
      "label": "Piers: typical and worst on each chassis beam: material, how stacked, cap, and shims",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "tallest-pier-tape-in-frame",
      "section": "under-the-home",
      "label": "Tallest pier, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "pier-spacing-along-each-chassis-beam",
      "section": "under-the-home",
      "label": "Pier spacing along each chassis beam, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "piers-at-the-marriage-line-and",
      "section": "under-the-home",
      "label": "Piers at the marriage line and under exterior door and large window openings (multi-section)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-pier-that-is-leaning-cracked",
      "section": "under-the-home",
      "label": "Any pier that is leaning, cracked, loose, or not in contact with the beam",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "how-the-chassis-beam-is-connected",
      "section": "under-the-home",
      "label": "How the chassis beam is connected to the pier or foundation (bolted / welded / clamped / resting only)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-strap-or-tie-on-each",
      "section": "anchorage",
      "label": "Every strap or tie on each long side: where it attaches to the home and where it attaches to the ground or foundation",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "what-each-strap-is-anchored-to",
      "section": "anchorage",
      "label": "What each strap is anchored to (screw-in ground anchor / concrete footing or slab / concrete deadman / other)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "anchorage-at-each-end-of-the",
      "section": "anchorage",
      "label": "Anchorage at each end of the home, running lengthwise",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-strap-that-is-loose-rusted",
      "section": "anchorage",
      "label": "Any strap that is loose, rusted, cut, or missing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-engineered-bracing-system-with-its",
      "section": "anchorage",
      "label": "Any engineered bracing system, with its label or tag",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-addition-room-porch-deck-carport",
      "section": "additions",
      "label": "Every addition: room, porch, deck, carport, awning, roof-over",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "whether-each-addition-stands-on-its",
      "section": "additions",
      "label": "Whether each addition stands on its own supports or hangs on the home",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "footing-and-post-under-each-addition",
      "section": "additions",
      "label": "Footing and post under each addition",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "water-sewer-electric-and-gas-connections",
      "section": "utilities",
      "label": "Water, sewer, electric, and gas connections under and at the home",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "full-perimeter-walk-anything-unusual",
      "section": "close-out",
      "label": "Full perimeter walk: anything unusual",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exception-menu-cleared-for-every-non",
      "section": "close-out",
      "label": "Exception menu cleared for every non-applicable item",
      "photo": false,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    }
  ],
  "determinations": [
    {
      "key": "pass",
      "heading": "PASS",
      "effect": null,
      "criteria": [
        "Package complete: every checklist item present or properly excepted",
        "Home identified by HUD label or data plate, built on or after June 15, 1976",
        "Floor area of at least 400 square feet",
        "Towing hitch, axles, and wheels removed",
        "Footings and piers sound, plumb, capped, and in contact with the chassis, whether mortared or dry-stacked",
        "Home attached to the foundation by anchorage the engineer finds carries uplift, sliding, and overturning in both directions",
        "Perimeter enclosure of masonry, concrete, treated wood, vinyl, or metal that is continuous, secured, and vented, with an access opening",
        "Ground under the home drains and is dry",
        "In a flood zone: finished grade under the home at or above the 100-year flood elevation shown on the flood elevation certificate",
        "Every addition stands on its own supports, or its load on the home and foundation is accounted for",
        "Utilities permanently connected"
      ],
      "at": "Appendix C"
    },
    {
      "key": "revise",
      "heading": "REVISE",
      "effect": null,
      "criteria": [
        "Any required photo missing, blurry, or missing its tape",
        "HUD label or data plate photo that cannot be read",
        "Piers or straps recorded from the access opening only",
        "Worst-condition coverage doubtful (all photos look selectively favorable)",
        "Counts or measurements inconsistent with photos"
      ],
      "at": "Appendix C"
    },
    {
      "key": "repairs-required",
      "heading": "REPAIRS REQUIRED (certification withheld, sealed letter and repair list issued)",
      "effect": "certification withheld, sealed letter and repair list issued",
      "criteria": [
        "Towing hitch, axles, or wheels still attached",
        "No anchorage, or anchorage the engineer finds does not carry the loads",
        "Anchorage missing in the lengthwise direction",
        "A strap that is loose, rusted through, cut, or missing",
        "A pier that is leaning, cracked, loose, or not in contact with the beam",
        "A pier with no footing, or a footing that is cracked or undermined",
        "No perimeter enclosure, or one that is broken, unsecured, or not continuous",
        "Standing water or active erosion under the home",
        "An addition hanging on the home with no support of its own",
        "Certification proceeds only after repairs are verified on revisit"
      ],
      "at": "Appendix C"
    },
    {
      "key": "site-revisit",
      "heading": "SITE REVISIT (technician returns with an engineer-specified capture list)",
      "effect": "technician returns with an engineer-specified capture list",
      "criteria": [
        "Part of the underside not reached on the first visit, return to complete it",
        "Footing size or anchor type not established, return after the owner exposes one footing or anchor and photograph it",
        "Conflicting evidence (owner story vs. photos vs. uploads), return for the specific items that settle it",
        "Repairs required, return after repairs to verify each item on the repair list"
      ],
      "at": "Appendix C"
    },
    {
      "key": "decline",
      "heading": "DECLINE",
      "effect": null,
      "criteria": [
        "Home built before June 15, 1976",
        "Home not yet installed, or being moved",
        "Site-built or modular home, route to foundation certification line",
        "Open insurance claim or litigation, decline, with a referral to an independent firm",
        "Lender requirement this protocol's evidence cannot support",
        "In a flood zone: no flood elevation certificate, or finished grade under the home below the 100-year flood elevation",
        "No safe access under the home and customer refuses to provide it",
        "Customer requests a predetermined conclusion, automatic decline, log verbatim request"
      ],
      "at": "Appendix C"
    }
  ],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Manufactured Home Foundation Certification Protocol",
    "Document Value",
    "Title Manufactured Home Foundation Certification Protocol",
    "Document number 254-MH-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Aman Dhakal, P.E., Engineer of Record, 254 Engineering",
    "Services",
    "Approval Aman Dhakal, P.E., Engineer of Record",
    "Applies to All manufactured home foundation certification engagements",
    "performed by 254 Engineering Services",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services inspects the foundation of an existing",
    "manufactured home so that the engineer can issue a sealed certification that the foundation",
    "complies with a named published requirement, supported by an evidence package collected by a",
    "field technician under the engineer's supervision.",
    "The engineer signs and seals the certification personally and a lender relies on it to make a loan.",
    "Every requirement in this protocol exists so that the engineer can reach a determination from the",
    "evidence package alone.",
    "2. Scope",
    "This protocol applies to existing manufactured homes built to the HUD Code on or after June 15,",
    "1976, installed on a foundation in Texas, where a lender or loan program requires an engineer's",
    "certification of the foundation.",
    "The certification addresses the foundation, the anchorage, and the connection of the home to the",
    "foundation, and any addition or alteration as it bears on them.",
    "This protocol does not cover the home's own structure or its compliance with the HUD Code; the",
    "installer's licensing or installation report under Texas rules; the home's title or real property status;",
    "retrofit design, which is a separate service line; or site-built and modular homes, which are covered",
    "by the foundation certification protocol. The firm does not perform forensic or cause-of-loss",
    "investigation, geotechnical investigation, or subsurface soil testing under this or any protocol.",
    "3. Governing requirements",
    "• The certification is written against HUD's Permanent Foundations Guide for Manufactured",
    "Housing, HUD-7584, September 1996 (PFGMH). This is the firm's default on every job.",
    "Another requirement is used only where the lender names it in writing, it is recorded verbatim",
    "at intake, and the engineer approves it before dispatch.",
    "• FHA Single Family Housing Policy Handbook 4000.1 requires a certification by an engineer or",
    "architect licensed in the state where the home is located, attesting to compliance with the",
    "PFGMH. The certification is site specific and carries the engineer's signature, seal, and license",
    "number.",
    "• Where the appraiser notes an addition or alteration to the home, Handbook 4000.1 requires",
    "the certification to address it.",
    "• A lender may reuse an earlier certification where there has been no alteration or observable",
    "damage since. That is the lender's decision. The firm does not re-date or re-address a",
    "certification.",
    "• Where the lender names a requirement other than the PFGMH, the engineer decides before",
    "dispatch whether this protocol's evidence can support it.",
    "• The certification is the engineer's professional opinion based on a visual, non-invasive",
    "inspection. It is not a warranty or a representation about concealed or below-grade conditions.",
    "4. Roles and responsibilities",
    "Only the Engineer of Record determines the outcome of a job and the wording of the certification.",
    "The field technician and the coordinator relay the engineer's written determination without",
    "interpretation, addition, or estimate of when a certification will issue.",
    "5. Personnel qualifications",
    "Field Technician",
    "• At least two years of documented experience in manufactured home installation, foundation",
    "inspection, or residential construction, or equivalent experience the engineer accepts in writing.",
    "• Completion of the engineer's training on this protocol and Appendix B, with a supervised",
    "inspection before independent work.",
    "• Confined-space awareness training, because every job requires going under the home.",
    "• Annual refresher training when the governing requirement, this protocol, or Appendix B",
    "changes.",
    "Engineer of Record",
    "• Active Texas P.E. license. A copy, with expiration date, is held in the firm's compliance file.",
    "6. Intake",
    "• The coordinator opens a job file for each property. The file records the intake answers and",
    "customer uploads required by Appendix A.",
    "• The coordinator records who requires the certification and their requirement exactly as given.",
    "The certification is addressed only to that recipient and written only against that requirement.",
    "• A yes to any flag question in Appendix A routes the job to the engineer before dispatch. The",
    "engineer records accept, accept with conditions, or decline.",
    "• A job is not dispatched until intake is complete and every upload required by Appendix A has",
    "been received.",
    "• The engineer records any condition of acceptance in the job file, including any item the",
    "technician must capture beyond Appendix B.",
    "7. Scheduling and dispatch",
    "• The coordinator schedules an accepted job within two business days. The engineer may set a",
    "different interval for a job in the job file.",
    "• The technician confirms access under the home, occupancy, and access to the interior data",
    "plate before travel.",
    "• Where site conditions prevent complete capture, including weather, access, safety, or standing",
    "water under the home, the technician records each item that could not be observed and the",
    "reason. No item is estimated, assumed, or left blank.",
    "• Where the space under the home cannot be safely entered, the technician does not enter it.",
    "The engineer decides from the evidence collected whether a determination is possible.",
    "8. Field inspection",
    "The technician completes every item of Appendix B for the property, in the order listed, and follows",
    "the photo procedure printed at the head of that checklist.",
    "• Before starting, the technician makes a rough sketch of the home and any additions, marks",
    "North, and photographs the sketch.",
    "• The technician ticks the item being photographed, photographs the checklist, then takes the",
    "photographs for that item, and moves to the next item the same way.",
    "• An item that does not apply to the property is marked with the reason it does not apply.",
    "• The counts and measurements called for on the checklist are recorded as counts and",
    "measurements, not as descriptions.",
    "• The technician goes under the home on every job. Piers, footings, and anchorage are",
    "recorded along the full length of each chassis beam, not from the access opening.",
    "9. Evidence standard and engineer review",
    "Evidence package",
    "Each job produces one evidence package in the firm's field application, consisting of the completed",
    "Appendix B checklist, the photographs, and the technician's notes.",
    "• Every checklist item has at least one wide photograph placing the item on the home and one",
    "close photograph showing its condition.",
    "• Where a size, spacing, height, or clearance governs, a tape is in frame.",
    "• The worst pier, the worst footing, and the worst strap or anchor on each side of the home are",
    "photographed. A representative sample selected for appearance is not acceptable.",
    "• The HUD label on each section and the data plate are photographed so that every line can be",
    "read.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location. Photographs sent by text or messaging app,",
    "or taken on another device, are not accepted.",
    "• An observation that cannot be made is recorded as not observed with the reason.",
    "• A package that does not cover every checklist item, with the photographs and measurements",
    "each item calls for, is rejected without review.",
    "Engineer review",
    "• The engineer reviews each evidence package and records one of the five determinations in",
    "Appendix C: pass, revise, repairs required, site revisit, or decline.",
    "• Where foundation plans were supplied, the engineer compares the foundation as observed",
    "against them and records any difference.",
    "• The engineer's review record identifies the checklist items and photographs relied on for the",
    "determination, and states the basis for accepting the anchorage.",
    "• A package that does not allow the engineer to verify a required item is returned for revision or",
    "a site revisit.",
    "10. Deficiencies and repairs",
    "• On a repairs required determination, the engineer issues a written repair list identifying each",
    "item, what governs it, and what is required to close it.",
    "• Where closing an item needs an engineered retrofit, the repair list says so. The retrofit design",
    "is a separate engagement.",
    "• Repairs are performed by others. 254 Engineering Services does not perform, supervise, or",
    "recommend a contractor for the repair work.",
    "• Corrections are verified on a site revisit to the same evidence standard, and the engineer",
    "closes each item individually.",
    "• On a repairs required determination, the engineer also issues a sealed letter stating that the",
    "foundation did not comply, with the repair list. No certification is issued with an open repair",
    "item. There is no conditional certification.",
    "11. Certification letter",
    "• On a pass determination, the engineer issues a sealed certification addressed to the recipient",
    "recorded at intake.",
    "• On a repairs required determination, the engineer issues a sealed letter to the same recipient",
    "stating that the foundation did not comply with the named requirement, with the repair list. The",
    "certification follows only after the corrections are verified on a site revisit.",
    "• The certification identifies the property, the home by manufacturer, serial number, HUD label",
    "numbers, and date of manufacture, the date of inspection, the foundation and anchorage as",
    "observed, and every addition.",
    "• The certification names the requirement it is written against and states that the foundation",
    "complies with it. It names no other requirement.",
    "• The certification states that the inspection was visual and non-invasive, that it reflects condition",
    "on the date of inspection only, and that no representation is made about concealed or below-",
    "grade conditions.",
    "• The certification does not address the home's own structure, and does not forecast future",
    "performance of the foundation.",
    "• A copy of an issued certification may be sent again to the same recipient. It is not re-dated, re-",
    "addressed, or issued for another loan. A new inspection is required.",
    "• The engineer does not certify a foundation that was not inspected under this protocol by this",
    "firm.",
    "12. Exclusions",
    "The following are declined or routed to another service line under its own engagement terms. The",
    "coordinator records the routing in the job file and informs the customer in writing.",
    "• A home built before June 15, 1976. Declined.",
    "• A home that is not yet installed, or is being moved. Declined until installation is complete.",
    "• A site-built or modular home. Routed to the foundation certification line.",
    "• An open insurance claim on the foundation, or active or threatened litigation involving it.",
    "Declined, with a referral to an independent firm.",
    "• A lender requirement the engineer finds this protocol's evidence cannot support. Declined.",
    "• A home in a flood zone with no flood elevation certificate, or with finished grade under the",
    "home below the 100-year flood elevation. Declined.",
    "• No safe access under the home where the customer refuses to provide it. Declined.",
    "• A customer request for a predetermined conclusion. This is an automatic decline and the",
    "request is logged verbatim.",
    "13. Records and retention",
    "• Each job file contains: the intake record and customer uploads, the engineer's acceptance",
    "record, the dispatch record, the completed Appendix B checklist, all photographs, the",
    "technician's notes, the engineer's review record and determination, any repair list and its",
    "closure records, and the issued certification.",
    "• Job files are retained for ten years from the date of the certification. For a job that produces no",
    "certification, the ten years runs from the date of the engineer's last recorded determination or",
    "closure.",
    "• Ten years is the firm's floor, reviewed against TBPELS rules.",
    "• The compliance file holds the engineer's license records, technician qualification and training",
    "records, and every issued version of this protocol.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the",
    "governing requirement or to the firm's field application.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table.",
    "• This document follows the firm's house protocol format. The portal's four parts are carried in",
    "Appendices A through C. Appendix A carries both the intake questions and the customer",
    "uploads. Appendix D is the reference list.",
    "Appendix A. Intake questions and customer uploads",
    "Asked and collected by the coordinator before the job is created. A job is not dispatched until every",
    "required item is present.",
    "PART 1: INTAKE QUESTIONS",
    "Purpose & recipient",
    "1. Who requires the certification? (lender name and loan type: FHA / VA / USDA / conventional /",
    "other)",
    "Answer: ____________________________________________________",
    "2. What does the lender's request say? (record exactly, or attach it)",
    "Answer: ____________________________________________________",
    "3. Who will the certification be addressed to?",
    "Answer: ____________________________________________________",
    "4. What deadline is the customer working against, if any?",
    "Answer: ____________________________________________________",
    "Property basics",
    "5. Property address and county",
    "Answer: ____________________________________________________",
    "6. Manufacturer and serial number, if known",
    "Answer: ____________________________________________________",
    "7. Single-section or multi-section",
    "Answer: ____________________________________________________",
    "8. Year the home was installed at this site",
    "Answer: ____________________________________________________",
    "9. What the home sits on, as the customer understands it (piers and tie-downs / slab / perimeter wall",
    "/ other)",
    "Answer: ____________________________________________________",
    "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
    "10. Was the home built before June 15, 1976?",
    "Yes No If yes, describe: ____________________________________________________",
    "11. Has the home been moved since it was first installed?",
    "Yes No If yes, describe: ____________________________________________________",
    "12. Are the HUD labels or the data plate missing?",
    "Yes No If yes, describe: ____________________________________________________",
    "13. Has anything been added to the home? (room, porch, deck, carport, roof-over)",
    "Yes No If yes, describe: ____________________________________________________",
    "14. Does the lender name a requirement other than the HUD Permanent Foundations Guide?",
    "Yes No If yes, describe: ____________________________________________________",
    "15. Is the property in a flood zone?",
    "Yes No If yes, describe: ____________________________________________________",
    "16. Has another engineer or inspector already declined to certify this foundation?",
    "Yes No If yes, describe: ____________________________________________________",
    "17. Is there an open insurance claim or litigation involving the foundation?",
    "Yes No If yes, describe: ____________________________________________________",
    "Access & safety (decides dispatch feasibility)",
    "18. Is there an opening to get under the home, and is the space dry?",
    "Answer: ____________________________________________________",
    "19. Occupied or vacant? Accessible if occupied?",
    "Answer: ____________________________________________________",
    "Prior paperwork prompt",
    "20. Do you have: the foundation plans the home was set on, an earlier foundation certification,",
    "installation report, tie-down or anchor paperwork, survey, flood elevation certificate, permits for",
    "additions?",
    "Answer: ____________________________________________________",
    "PART 2: CUSTOMER UPLOADS (collected at intake, before dispatch)",
    "Required",
    "-- Photo of the front of the property (confirms address/structure)",
    "-- The lender's written request for the certification",
    "Required if it exists",
    "-- Foundation plans or drawings used for the home's foundation",
    "-- Any earlier foundation certification or engineer letter",
    "Collect when applicable",
    "-- Flood elevation certificate (required where the property is in a flood zone)",
    "-- Installation report or installer paperwork",
    "-- Anchor or tie-down system paperwork",
    "-- Permits and drawings for additions",
    "-- Appraisal pages noting additions or alterations",
    "Appendix B. Technician on-site checklist",
    "Completed on site by the technician. The checklist cannot be submitted incomplete.",
    "PHOTOS",
    "-- Before starting, make a rough sketch of the home and any additions and mark North. Take a photo",
    "of it.",
    "-- Tick the item you are about to photograph, take a photo of the checklist, then take the photos for",
    "that item.",
    "-- Move on to the next item the same way.",
    "JOB INFORMATION",
    "Job / Dispatch No.: ____________________________",
    "Property address (full, incl. county):",
    "__________________________________________________________",
    "Technician name: ______________________________________",
    "Date / arrival time / departure time: ________________________________________",
    "Weather during visit: ________________________________________",
    "Contact on site (name, role, phone): ________________________________________________",
    "[ ] Photo of address marker (house number, street sign, or mailbox) [PHOTO]",
    "HOME IDENTIFICATION",
    "[ ] All four elevations of the home [PHOTO]",
    "[ ] HUD label on each section, every digit readable [PHOTO]",
    "[ ] Data plate inside the home (kitchen cabinet, bedroom closet, or electrical panel) [PHOTO]",
    "[ ] Serial number stamped on the front cross member of the frame [PHOTO]",
    "HUD label numbers: __________________________________",
    "Manufacturer / date of manufacture / serial number: __________________________________",
    "Wind zone and roof load zone from the data plate: __________________________________",
    "Number of sections ____ length (ft) ____ width of each section (ft) ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "SITE",
    "[ ] Ground slope and drainage on each side of the home [PHOTO]",
    "[ ] Standing water, ponding, or erosion at or under the home [PHOTO]",
    "[ ] Downspout and drain discharge points [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "RUNNING GEAR",
    "[ ] Towing hitch: removed or still attached [PHOTO]",
    "[ ] Axles and wheels: removed or still attached [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "PERIMETER ENCLOSURE",
    "[ ] Enclosure on each side: material and whether it is continuous [PHOTO]",
    "[ ] How the enclosure is fastened at the top and what it sits on at the bottom [PHOTO]",
    "[ ] Access opening, tape across width and height [PHOTO]",
    "[ ] Every vent [PHOTO]",
    "Enclosure material (masonry / concrete / treated wood / vinyl / metal / none): ________________",
    "Access opening width x height (in.): ________ vents, count ____ typical size (in.) ________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "UNDER THE HOME",
    "[ ] Overview from the access opening, and looking down the length of each chassis beam [PHOTO]",
    "[ ] Clearance from ground to the bottom of the chassis beam at the lowest point, tape in frame",
    "[PHOTO]",
    "[ ] Ground cover or vapor barrier, and any wet soil [PHOTO]",
    "[ ] Footings: typical and worst, tape across length and width, thickness where visible [PHOTO]",
    "[ ] Piers: typical and worst on each chassis beam: material, how stacked, cap, and shims [PHOTO]",
    "[ ] Tallest pier, tape in frame [PHOTO]",
    "[ ] Pier spacing along each chassis beam, tape in frame [PHOTO]",
    "[ ] Piers at the marriage line and under exterior door and large window openings (multi-section)",
    "[PHOTO]",
    "[ ] Any pier that is leaning, cracked, loose, or not in contact with the beam [PHOTO]",
    "[ ] How the chassis beam is connected to the pier or foundation (bolted / welded / clamped / resting",
    "only) [PHOTO]",
    "Footing size (in.): ________ pier material: ________ mortared or dry-stacked: ________",
    "Pier spacing (ft), each beam: ________ tallest pier (in.): ________ lowest clearance (in.): ________",
    "Piers counted ____ piers with a deficiency ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "ANCHORAGE",
    "[ ] Every strap or tie on each long side: where it attaches to the home and where it attaches to the",
    "ground or foundation [PHOTO]",
    "[ ] What each strap is anchored to (screw-in ground anchor / concrete footing or slab / concrete",
    "deadman / other) [PHOTO]",
    "[ ] Anchorage at each end of the home, running lengthwise [PHOTO]",
    "[ ] Any strap that is loose, rusted, cut, or missing [PHOTO]",
    "[ ] Any engineered bracing system, with its label or tag [PHOTO]",
    "Straps each long side: ____ / ____ spacing (ft): ________ straps each end: ____ / ____",
    "Straps with a deficiency ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "ADDITIONS",
    "[ ] Every addition: room, porch, deck, carport, awning, roof-over [PHOTO]",
    "[ ] Whether each addition stands on its own supports or hangs on the home [PHOTO]",
    "[ ] Footing and post under each addition [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "UTILITIES",
    "[ ] Water, sewer, electric, and gas connections under and at the home [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CLOSE-OUT",
    "[ ] Full perimeter walk: anything unusual [PHOTO]",
    "[ ] Exception menu cleared for every non-applicable item",
    "Total photos: ______________",
    "Technician signature / date: ____________________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Appendix C. Engineer decision rules",
    "Applied by the engineer to each evidence package. One determination is recorded per review. The",
    "rules below state the PFGMH and Handbook 4000.1 requirements as the engineer applies them.",
    "Where the lender names another requirement, the engineer records the rules for that job in the job",
    "file.",
    "PASS",
    "-- Package complete: every checklist item present or properly excepted",
    "-- Home identified by HUD label or data plate, built on or after June 15, 1976",
    "-- Floor area of at least 400 square feet",
    "-- Towing hitch, axles, and wheels removed",
    "-- Footings and piers sound, plumb, capped, and in contact with the chassis, whether mortared or",
    "dry-stacked",
    "-- Home attached to the foundation by anchorage the engineer finds carries uplift, sliding, and",
    "overturning in both directions",
    "-- Perimeter enclosure of masonry, concrete, treated wood, vinyl, or metal that is continuous,",
    "secured, and vented, with an access opening",
    "-- Ground under the home drains and is dry",
    "-- In a flood zone: finished grade under the home at or above the 100-year flood elevation shown on",
    "the flood elevation certificate",
    "-- Every addition stands on its own supports, or its load on the home and foundation is accounted for",
    "-- Utilities permanently connected",
    "REVISE",
    "-- Any required photo missing, blurry, or missing its tape",
    "-- HUD label or data plate photo that cannot be read",
    "-- Piers or straps recorded from the access opening only",
    "-- Worst-condition coverage doubtful (all photos look selectively favorable)",
    "-- Counts or measurements inconsistent with photos",
    "REPAIRS REQUIRED (certification withheld, sealed letter and repair list issued)",
    "-- Towing hitch, axles, or wheels still attached",
    "-- No anchorage, or anchorage the engineer finds does not carry the loads",
    "-- Anchorage missing in the lengthwise direction",
    "-- A strap that is loose, rusted through, cut, or missing",
    "-- A pier that is leaning, cracked, loose, or not in contact with the beam",
    "-- A pier with no footing, or a footing that is cracked or undermined",
    "-- No perimeter enclosure, or one that is broken, unsecured, or not continuous",
    "-- Standing water or active erosion under the home",
    "-- An addition hanging on the home with no support of its own",
    "-- Certification proceeds only after repairs are verified on revisit",
    "SITE REVISIT (technician returns with an engineer-specified capture list)",
    "-- Part of the underside not reached on the first visit, return to complete it",
    "-- Footing size or anchor type not established, return after the owner exposes one footing or anchor",
    "and photograph it",
    "-- Conflicting evidence (owner story vs. photos vs. uploads), return for the specific items that settle it",
    "-- Repairs required, return after repairs to verify each item on the repair list",
    "DECLINE",
    "-- Home built before June 15, 1976",
    "-- Home not yet installed, or being moved",
    "-- Site-built or modular home, route to foundation certification line",
    "-- Open insurance claim or litigation, decline, with a referral to an independent firm",
    "-- Lender requirement this protocol's evidence cannot support",
    "-- In a flood zone: no flood elevation certificate, or finished grade under the home below the 100-year",
    "flood elevation",
    "-- No safe access under the home and customer refuses to provide it",
    "-- Customer requests a predetermined conclusion, automatic decline, log verbatim request",
    "Appendix D. References",
    "Item Location",
    "Permanent Foundations",
    "Guide for Manufactured",
    "Housing, HUD-7584",
    "(Handbook 4930.3G),",
    "September 1996",
    "huduser.gov",
    "FHA Single Family Housing",
    "Policy Handbook 4000.1,",
    "Manufactured Housing",
    "hud.gov",
    "24 CFR 203.43f, Eligibility",
    "of Mortgages Covering",
    "Manufactured Homes",
    "ecfr.gov",
    "Manufactured Home",
    "Construction and Safety",
    "Standards, 24 CFR Part",
    "3280",
    "ecfr.gov",
    "Model Manufactured Home",
    "Installation Standards, 24",
    "CFR Part 3285",
    "ecfr.gov",
    "Texas Manufactured",
    "Housing Rules, 10 TAC",
    "Chapter 80",
    "tdhca.texas.gov",
    "Texas Engineering Practice",
    "Act, Texas Occupations",
    "Code Chapter 1001",
    "statutes.capitol.texas.gov",
    "TBPELS rules, 22 TAC",
    "Chapter 137",
    "pels.texas.gov",
    "254-RC-001 Roof",
    "Certification Protocol, v1.1,",
    "issued September 18, 2026",
    "Firm document",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const MH001_COUNTS = [
  {
    "key": "field-1",
    "prompt": "Job / Dispatch No.: ____________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-2",
    "prompt": "Property address (full, incl. county):",
    "at": "Appendix B"
  },
  {
    "key": "field-3",
    "prompt": "Technician name: ______________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-4",
    "prompt": "Date / arrival time / departure time: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-5",
    "prompt": "Weather during visit: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-6",
    "prompt": "Contact on site (name, role, phone): ________________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-7",
    "prompt": "HUD label numbers: __________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-8",
    "prompt": "Manufacturer / date of manufacture / serial number: __________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-9",
    "prompt": "Wind zone and roof load zone from the data plate: __________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-10",
    "prompt": "Number of sections ____ length (ft) ____ width of each section (ft) ____",
    "at": "Appendix B"
  },
  {
    "key": "field-11",
    "prompt": "Enclosure material (masonry / concrete / treated wood / vinyl / metal / none): ________________",
    "at": "Appendix B"
  },
  {
    "key": "field-12",
    "prompt": "Access opening width x height (in.): ________ vents, count ____ typical size (in.) ________",
    "at": "Appendix B"
  },
  {
    "key": "field-13",
    "prompt": "Footing size (in.): ________ pier material: ________ mortared or dry-stacked: ________",
    "at": "Appendix B"
  },
  {
    "key": "field-14",
    "prompt": "Pier spacing (ft), each beam: ________ tallest pier (in.): ________ lowest clearance (in.): ________",
    "at": "Appendix B"
  },
  {
    "key": "field-15",
    "prompt": "Piers counted ____ piers with a deficiency ____",
    "at": "Appendix B"
  },
  {
    "key": "field-16",
    "prompt": "Straps each long side: ____ / ____ spacing (ft): ________ straps each end: ____ / ____",
    "at": "Appendix B"
  },
  {
    "key": "field-17",
    "prompt": "Straps with a deficiency ____",
    "at": "Appendix B"
  },
  {
    "key": "field-18",
    "prompt": "Total photos: ______________",
    "at": "Appendix B"
  },
  {
    "key": "field-19",
    "prompt": "Technician signature / date: ____________________________________________",
    "at": "Appendix B"
  }
];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const MH001_OTHER_RULES = [];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const MH001_BLANK_JOB_LIST_ITEMS = 0;
