/**
 * 254-PL-001 v1.1, Structural Letter Protocol for Permits.
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-PL-001_Structural_Letter_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 f1ff2e5883aac06ac1b468a74ea09535c074a468a31de4c04297bf4c74b11387. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const PL001 = {
  "documentNumber": "254-PL-001",
  "title": "Structural Letter Protocol for Permits",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Aman Dhakal, P.E., Engineer of Record, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record",
  "appliesTo": "All structural letter engagements for permitting performed by 254 Engineering Services",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "structural-letters",
  "serviceTier": null,
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-PL-001_Structural_Letter_Protocol_v1_1.pdf",
  "sourceSha256": "f1ff2e5883aac06ac1b468a74ea09535c074a468a31de4c04297bf4c74b11387",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "job-information",
      "heading": "JOB INFORMATION",
      "at": "Appendix B"
    },
    {
      "key": "context",
      "heading": "CONTEXT (every job)",
      "at": "Appendix B"
    },
    {
      "key": "the-element",
      "heading": "THE ELEMENT",
      "at": "Appendix B"
    },
    {
      "key": "engineer-s-job-list",
      "heading": "ENGINEER'S JOB LIST",
      "at": "Appendix B"
    },
    {
      "key": "close-out",
      "heading": "CLOSE-OUT",
      "at": "Appendix B"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the structure, mark where the element is, and mark North. Take a photo of it.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix B, PHOTOS"
    }
  ],
  "intakeQuestions": [
    {
      "number": 1,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Which city or county is the permit with, and what is the permit or application number?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 2,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What did the permitting authority ask for? (record exactly, and attach it)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 3,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Which code edition does the authority enforce?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 4,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What deadline is the customer working against, if any?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 5,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property address and county",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 6,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property type (single family / duplex / townhome / small commercial) and number of stories",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 7,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "What is the letter about? (beam / wall removal / deck / patio cover / framing / foundation / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 8,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Is the work already built, partly built, or not started?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 9,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Who did or will do the work? (contractor name and phone)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 10,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is the work covered up so it cannot be seen?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 11,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Was the work done without a permit?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 12,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Has the permitting authority issued a stop work order or a failed inspection?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 13,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Has another engineer already declined to issue a letter for this work?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 14,
      "group": "flags",
      "groupHeading": "Flags: recorded for the engineer's acceptance review",
      "ask": "Is there an open insurance claim or litigation involving this work?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 15,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Where is the element, and how is it reached? (attic / crawlspace / interior / exterior)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 16,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Occupied or vacant? Accessible if occupied?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 17,
      "group": "prior-paperwork",
      "groupHeading": "Prior paperwork prompt",
      "ask": "Do you have: plans, product data, contractor invoices, inspection reports, an earlier engineer letter, photos taken during the work?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    }
  ],
  "intakeUploads": [
    {
      "key": "the-permitting-authority-s-written-request-1",
      "what": "The permitting authority's written request, comment, or correction notice",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "photo-of-the-front-of-the-2",
      "what": "Photo of the front of the property (confirms address/structure)",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "plans-drawings-or-specifications-for-the-3",
      "what": "Plans, drawings, or specifications for the element",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-failed-inspection-report-or-stop-4",
      "what": "Any failed inspection report or stop work order",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-earlier-engineer-letter-5",
      "what": "Any earlier engineer letter",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "photos-taken-during-the-work-before-6",
      "what": "Photos taken during the work, before it was covered",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "product-data-for-manufactured-members-connectors-7",
      "what": "Product data for manufactured members, connectors, or hangers",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "contractor-invoice-describing-the-work-8",
      "what": "Contractor invoice describing the work",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    }
  ],
  "checklist": [
    {
      "key": "photo-of-address-marker-house-number",
      "section": "job-information",
      "label": "Photo of address marker (house number, street sign, or mailbox)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "all-four-elevations-of-the-structure",
      "section": "context",
      "label": "All four elevations of the structure",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-room-or-area-the-element",
      "section": "context",
      "label": "The room or area the element is in, from two directions",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-element-overall-showing-both-ends",
      "section": "context",
      "label": "The element overall, showing both ends",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "material-and-any-stamp-label-or",
      "section": "the-element",
      "label": "Material and any stamp, label, or marking on it",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "depth-and-width-tape-in-frame",
      "section": "the-element",
      "label": "Depth and width, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "length-or-span-between-supports-tape",
      "section": "the-element",
      "label": "Length or span between supports, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "spacing-where-there-is-more-than",
      "section": "the-element",
      "label": "Spacing, where there is more than one member, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-support-what-the-element-sits",
      "section": "the-element",
      "label": "Each support: what the element sits on at each end and in between",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-connection-hanger-connector-bolts-nails",
      "section": "the-element",
      "label": "Each connection: hanger, connector, bolts, nails, or screws, with any marking",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "what-the-element-carries-what-sits",
      "section": "the-element",
      "label": "What the element carries: what sits on it or frames into it",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "what-is-below-each-support-down",
      "section": "the-element",
      "label": "What is below each support, down to the foundation where it can be seen",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-split-crack-sag-notch-hole",
      "section": "the-element",
      "label": "Any split, crack, sag, notch, hole, rot, rust, or earlier repair",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "full-perimeter-walk-anything-unusual",
      "section": "close-out",
      "label": "Full perimeter walk: anything unusual",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exception-menu-cleared-for-every-non",
      "section": "close-out",
      "label": "Exception menu cleared for every non-applicable item",
      "photo": false,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    }
  ],
  "determinations": [
    {
      "key": "pass",
      "heading": "PASS",
      "effect": null,
      "criteria": [
        "Site job: every checklist item and every job list item present or properly excepted",
        "Desk job: every drawing and document the engineer asked for is in the file",
        "The authority's request is in the file as written",
        "The element, its supports, and its connections are established from the evidence",
        "The element satisfies the requirement the authority named, by the adopted code and the engineer's calculation where one is needed",
        "No damage or alteration that affects the opinion",
        "Where the opinion depends on a condition, the letter states the condition in an attached schedule"
      ],
      "at": "Appendix C"
    },
    {
      "key": "revise",
      "heading": "REVISE",
      "effect": null,
      "criteria": [
        "Any required photo missing, blurry, or missing its tape",
        "A support or connection with no photo",
        "A job list item not completed",
        "A drawing or document the engineer asked for not supplied",
        "Counts or measurements inconsistent with photos"
      ],
      "at": "Appendix C"
    },
    {
      "key": "repairs-required",
      "heading": "REPAIRS REQUIRED (sealed letter states does not satisfy, repair list issued)",
      "effect": "sealed letter states does not satisfy, repair list issued",
      "criteria": [
        "The element does not satisfy the requirement the authority named",
        "A support or connection is missing, undersized, or not installed to its manufacturer's instructions",
        "Damage or alteration that affects the element",
        "A letter stating that the element satisfies the requirement proceeds only after repairs are verified on revisit"
      ],
      "at": "Appendix C"
    },
    {
      "key": "site-revisit",
      "heading": "SITE REVISIT (technician returns with an engineer-specified capture list)",
      "effect": "technician returns with an engineer-specified capture list",
      "criteria": [
        "A concealed support or connection governs the result, return after the owner's contractor opens it and photograph it",
        "The first visit showed something the job list did not cover, return with an added list",
        "Conflicting evidence (plans vs. photos vs. measurements), return for the specific items that settle it",
        "Repairs required, return after repairs to verify each item on the repair list"
      ],
      "at": "Appendix C"
    },
    {
      "key": "decline",
      "heading": "DECLINE",
      "effect": null,
      "criteria": [
        "No written request from the permitting authority",
        "Request needs drawings or a repair method, route to design or repair specification line",
        "Request covered by another protocol, route to that line",
        "Concealed element and the owner will not have it opened",
        "Open insurance claim or litigation, decline, with a referral to an independent firm",
        "Customer requests a predetermined conclusion, automatic decline, log verbatim request"
      ],
      "at": "Appendix C"
    }
  ],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Structural Letter Protocol",
    "Document Value",
    "Title Structural Letter Protocol for Permits",
    "Document number 254-PL-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Aman Dhakal, P.E., Engineer of Record, 254 Engineering",
    "Services",
    "Approval Aman Dhakal, P.E., Engineer of Record",
    "Applies to All structural letter engagements for permitting performed by 254",
    "Engineering Services",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services prepares a structural letter for a permit so",
    "that the engineer can issue a sealed letter to a permitting authority, supported by the documents the",
    "customer supplies and, where existing construction is involved, an evidence package collected by a",
    "field technician under the engineer's supervision.",
    "The engineer signs and seals the letter personally and the permitting authority relies on that opinion.",
    "Every requirement in this protocol exists so that the engineer can reach a determination from the job",
    "file alone.",
    "2. Scope",
    "This protocol applies to residential and light commercial structures where a permitting authority has",
    "asked, in writing, for an engineer's letter on a described structure or element, to issue or close a",
    "permit.",
    "A structural letter for permit is a sealed letter addressed to the permitting authority stating the",
    "engineer's opinion that the described structure or element satisfies the requirement the authority",
    "named.",
    "This protocol does not cover solar structural letters, roof certifications, foundation certifications, or",
    "windstorm certifications, each of which has its own protocol; work that needs drawings or a",
    "specification, which is design or repair specification; or a letter for any reader other than a permitting",
    "authority. The firm does not perform forensic or cause-of-loss investigation under this or any",
    "protocol.",
    "3. Governing requirements",
    "• The building code adopted by the permitting authority. The coordinator records the authority",
    "and the code edition at intake. The engineer confirms both.",
    "• The authority's written request, recorded verbatim. The letter answers that request and nothing",
    "else.",
    "• Texas Engineering Practice Act and TBPELS rules, 22 TAC Chapter 137.",
    "• The letter is the engineer's professional opinion on the element described, based on the",
    "evidence and documents named in it. It is not a warranty and not an opinion on the rest of the",
    "structure.",
    "4. Roles and responsibilities",
    "Only the Engineer of Record determines whether a job is accepted, what evidence it needs, the",
    "outcome, and the wording of the letter. The field technician and the coordinator relay the engineer's",
    "written determination without interpretation, addition, or estimate of when a letter will issue.",
    "5. Personnel qualifications",
    "Field Technician",
    "• At least two years of documented experience in residential construction, framing, or structural",
    "inspection, or equivalent experience the engineer accepts in writing.",
    "• Completion of the engineer's training on this protocol and Appendix B, with a supervised",
    "inspection before independent work.",
    "• Demonstrated ability to read plans and locate items in the field against them.",
    "• Annual refresher training when the adopted code, this protocol, or Appendix B changes.",
    "Engineer of Record",
    "• Active Texas P.E. license. A copy, with expiration date, is held in the firm's compliance file.",
    "6. Intake",
    "• The coordinator opens a job file for each request. The file records the intake answers and",
    "customer uploads required by Appendix A.",
    "• The coordinator records what the permitting authority asked for exactly as written, and",
    "attaches the authority's written request. A request the customer can only describe is not",
    "accepted.",
    "• The engineer triages every job within one business day of the order, and records accept,",
    "accept with conditions, or decline.",
    "• On acceptance the engineer records whether the job is a site job or a desk job. A site job is",
    "any job where the letter concerns existing construction. A desk job is one where the letter can",
    "be answered from drawings and documents alone. Photographs supplied by the customer do",
    "not replace a technician visit.",
    "• For a site job, the engineer writes the job list, which is the items the technician captures for that",
    "element in addition to the standing items of Appendix B.",
    "• A site job is not dispatched until intake is complete, every upload required by Appendix A has",
    "been received, and the engineer's job list is in the job file.",
    "7. Scheduling and dispatch",
    "• The coordinator schedules a site job within two business days of the engineer's job list. The",
    "engineer may set a different interval for a job in the job file.",
    "• The technician confirms access and occupancy before travel, and confirms that the element",
    "can be seen.",
    "• Where site conditions prevent complete capture, including weather, access, or safety, the",
    "technician records each item that could not be observed and the reason. No item is estimated,",
    "assumed, or left blank.",
    "• A desk job is not dispatched.",
    "8. Field inspection",
    "On a site job the technician completes every item of Appendix B and every item on the engineer's",
    "job list, in the order listed, and follows the photo procedure printed at the head of that checklist.",
    "• Before starting, the technician makes a rough sketch of the structure, marks North, marks",
    "where the element is, and photographs the sketch.",
    "• The technician ticks the item being photographed, photographs the checklist, then takes the",
    "photographs for that item, and moves to the next item the same way.",
    "• An item that does not apply is marked with the reason it does not apply.",
    "• The counts and measurements called for are recorded as counts and measurements, not as",
    "descriptions.",
    "• The inspection is visual and non-destructive. The technician does not remove or open any",
    "finish. An item that is covered up is recorded as concealed.",
    "9. Evidence standard and engineer review",
    "Evidence package",
    "Each site job produces one evidence package in the firm's field application, consisting of the",
    "completed Appendix B checklist, the engineer's job list, the photographs, and the technician's notes.",
    "Each desk job produces a document package consisting of the authority's request and the drawings",
    "and documents reviewed.",
    "• Every checklist item has at least one wide photograph placing the item on the structure and",
    "one close photograph showing its condition.",
    "• Every measurement has the tape in frame.",
    "• Every connection and every support of the element is photographed individually.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location. Photographs sent by text or messaging app,",
    "or taken on another device, are not accepted.",
    "• An observation that cannot be made is recorded as not observed with the reason.",
    "• A package that does not cover every checklist item and every item on the engineer's job list is",
    "rejected without review.",
    "Engineer review",
    "• The engineer reviews each package, performs any calculation the opinion needs, and records",
    "one of the five determinations in Appendix C: pass, revise, repairs required, site revisit, or",
    "decline.",
    "• The engineer's review record identifies the photographs, documents, and calculation relied on",
    "for the determination. The calculation is kept in the job file.",
    "• A package that does not allow the engineer to verify a required item is returned for revision or",
    "a site revisit.",
    "10. Deficiencies and repairs",
    "• On a repairs required determination, the engineer issues a written repair list identifying each",
    "item, what governs it, and what is required to close it.",
    "• Where closing an item needs drawings or a specification, the list says so. That work is a",
    "separate engagement.",
    "• Repairs are performed by others. 254 Engineering Services does not perform, supervise, or",
    "recommend a contractor for the repair work.",
    "• Corrections are verified on a site revisit to the same evidence standard, and the engineer",
    "closes each item individually.",
    "• On a repairs required determination, the engineer also issues a sealed letter stating that the",
    "element does not satisfy the requirement, with the repair list. No letter stating that the element",
    "satisfies the requirement is issued with an open repair item.",
    "11. Structural letter",
    "• On a pass determination, the engineer issues a sealed letter addressed to the permitting",
    "authority recorded at intake.",
    "• Where the element satisfies the requirement subject to conditions, the letter says so and states",
    "each condition in an attached schedule.",
    "• On a repairs required determination, the engineer issues a sealed letter stating that the",
    "element does not satisfy the requirement, with the repair list.",
    "• The letter gives the property, the permit number, the authority's request as written, the element",
    "described, the adopted code, and the evidence and documents the opinion is based on, with",
    "the date of inspection for a site job.",
    "• The letter states the engineer's opinion on the element against the request. It gives no opinion",
    "on anything the authority did not ask about.",
    "• The letter states that it does not cover the rest of the structure or any concealed condition, and",
    "that it reflects condition on the date of inspection only.",
    "• The letter does not forecast future performance.",
    "• The letter is not reassigned to another permit or another authority. A new job is required.",
    "12. Exclusions",
    "The following are declined or routed to another service line under its own engagement terms. The",
    "coordinator records the routing in the job file and informs the customer in writing.",
    "• No written request from the permitting authority. Not accepted until one is supplied.",
    "• A request that needs drawings, calculations for new work, or a repair method. Routed to the",
    "design or repair specification line.",
    "• A request covered by another protocol: solar, roof, foundation, or windstorm. Routed to that",
    "line.",
    "• An element that is concealed where the owner will not have it opened. Declined.",
    "• An open insurance claim or litigation involving the element. Declined, with a referral to an",
    "independent firm.",
    "• A customer request for a predetermined conclusion. This is an automatic decline and the",
    "request is logged verbatim.",
    "13. Records and retention",
    "• Each job file contains: the intake record and customer uploads, the authority's written request,",
    "the engineer's acceptance record and job list, the dispatch record, the completed Appendix B",
    "checklist, all photographs, the technician's notes, the documents reviewed, the engineer's",
    "calculation, review record and determination, any repair list and its closure records, and the",
    "issued letter.",
    "• Job files are retained for ten years from the date of the letter. For a job that produces no letter,",
    "the ten years runs from the date of the engineer's last recorded determination or closure.",
    "• Ten years is the firm's floor, reviewed against TBPELS rules.",
    "• The compliance file holds the engineer's license records, technician qualification and training",
    "records, and every issued version of this protocol.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the firm's",
    "field application.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table.",
    "• This document follows the firm's house protocol format. The portal's four parts are carried in",
    "Appendices A through C. Appendix A carries both the intake questions and the customer",
    "uploads. Appendix D is the reference list.",
    "Appendix A. Intake questions and customer uploads",
    "Asked and collected by the coordinator before the job is created. Every job goes to the engineer",
    "before it is accepted.",
    "PART 1: INTAKE QUESTIONS",
    "Purpose & recipient",
    "1. Which city or county is the permit with, and what is the permit or application number?",
    "Answer: ____________________________________________________",
    "2. What did the permitting authority ask for? (record exactly, and attach it)",
    "Answer: ____________________________________________________",
    "3. Which code edition does the authority enforce?",
    "Answer: ____________________________________________________",
    "4. What deadline is the customer working against, if any?",
    "Answer: ____________________________________________________",
    "Property basics",
    "5. Property address and county",
    "Answer: ____________________________________________________",
    "6. Property type (single family / duplex / townhome / small commercial) and number of stories",
    "Answer: ____________________________________________________",
    "7. What is the letter about? (beam / wall removal / deck / patio cover / framing / foundation / other)",
    "Answer: ____________________________________________________",
    "8. Is the work already built, partly built, or not started?",
    "Answer: ____________________________________________________",
    "9. Who did or will do the work? (contractor name and phone)",
    "Answer: ____________________________________________________",
    "Flags: recorded for the engineer's acceptance review",
    "10. Is the work covered up so it cannot be seen?",
    "Yes No If yes, describe: ____________________________________________________",
    "11. Was the work done without a permit?",
    "Yes No If yes, describe: ____________________________________________________",
    "12. Has the permitting authority issued a stop work order or a failed inspection?",
    "Yes No If yes, describe: ____________________________________________________",
    "13. Has another engineer already declined to issue a letter for this work?",
    "Yes No If yes, describe: ____________________________________________________",
    "14. Is there an open insurance claim or litigation involving this work?",
    "Yes No If yes, describe: ____________________________________________________",
    "Access & safety (decides dispatch feasibility)",
    "15. Where is the element, and how is it reached? (attic / crawlspace / interior / exterior)",
    "Answer: ____________________________________________________",
    "16. Occupied or vacant? Accessible if occupied?",
    "Answer: ____________________________________________________",
    "Prior paperwork prompt",
    "17. Do you have: plans, product data, contractor invoices, inspection reports, an earlier engineer",
    "letter, photos taken during the work?",
    "Answer: ____________________________________________________",
    "PART 2: CUSTOMER UPLOADS (collected at intake)",
    "Required",
    "-- The permitting authority's written request, comment, or correction notice",
    "-- Photo of the front of the property (confirms address/structure)",
    "Required if it exists",
    "-- Plans, drawings, or specifications for the element",
    "-- Any failed inspection report or stop work order",
    "-- Any earlier engineer letter",
    "Collect when applicable",
    "-- Photos taken during the work, before it was covered",
    "-- Product data for manufactured members, connectors, or hangers",
    "-- Contractor invoice describing the work",
    "Appendix B. Technician on-site checklist",
    "Completed on site by the technician on a site job. The checklist cannot be submitted incomplete.",
    "PHOTOS",
    "-- Before starting, make a rough sketch of the structure, mark where the element is, and mark North.",
    "Take a photo of it.",
    "-- Tick the item you are about to photograph, take a photo of the checklist, then take the photos for",
    "that item.",
    "-- Move on to the next item the same way.",
    "JOB INFORMATION",
    "Job / Dispatch No.: ____________________________",
    "Property address (full, incl. county):",
    "__________________________________________________________",
    "Technician name: ______________________________________",
    "Date / arrival time / departure time: ________________________________________",
    "Weather during visit: ________________________________________",
    "Contact on site (name, role, phone): ________________________________________________",
    "[ ] Photo of address marker (house number, street sign, or mailbox) [PHOTO]",
    "CONTEXT (every job)",
    "[ ] All four elevations of the structure [PHOTO]",
    "[ ] The room or area the element is in, from two directions [PHOTO]",
    "[ ] The element overall, showing both ends [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "THE ELEMENT",
    "[ ] Material and any stamp, label, or marking on it [PHOTO]",
    "[ ] Depth and width, tape in frame [PHOTO]",
    "[ ] Length or span between supports, tape in frame [PHOTO]",
    "[ ] Spacing, where there is more than one member, tape in frame [PHOTO]",
    "[ ] Each support: what the element sits on at each end and in between [PHOTO]",
    "[ ] Each connection: hanger, connector, bolts, nails, or screws, with any marking [PHOTO]",
    "[ ] What the element carries: what sits on it or frames into it [PHOTO]",
    "[ ] What is below each support, down to the foundation where it can be seen [PHOTO]",
    "[ ] Any split, crack, sag, notch, hole, rot, rust, or earlier repair [PHOTO]",
    "Material ________________ size (in.) ________ x ________ span (ft-in.) ________ spacing (in.)",
    "________",
    "Supports ____ connections ____ items concealed ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "ENGINEER'S JOB LIST",
    "Written by the engineer for this job. Each line is completed like any other item.",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "[ ] ______________________________________________________________ [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CLOSE-OUT",
    "[ ] Full perimeter walk: anything unusual [PHOTO]",
    "[ ] Exception menu cleared for every non-applicable item",
    "Total photos: ______________",
    "Technician signature / date: ____________________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Appendix C. Engineer decision rules",
    "Applied by the engineer to each package. One determination is recorded per review.",
    "PASS",
    "-- Site job: every checklist item and every job list item present or properly excepted",
    "-- Desk job: every drawing and document the engineer asked for is in the file",
    "-- The authority's request is in the file as written",
    "-- The element, its supports, and its connections are established from the evidence",
    "-- The element satisfies the requirement the authority named, by the adopted code and the",
    "engineer's calculation where one is needed",
    "-- No damage or alteration that affects the opinion",
    "-- Where the opinion depends on a condition, the letter states the condition in an attached schedule",
    "REVISE",
    "-- Any required photo missing, blurry, or missing its tape",
    "-- A support or connection with no photo",
    "-- A job list item not completed",
    "-- A drawing or document the engineer asked for not supplied",
    "-- Counts or measurements inconsistent with photos",
    "REPAIRS REQUIRED (sealed letter states does not satisfy, repair list issued)",
    "-- The element does not satisfy the requirement the authority named",
    "-- A support or connection is missing, undersized, or not installed to its manufacturer's instructions",
    "-- Damage or alteration that affects the element",
    "-- A letter stating that the element satisfies the requirement proceeds only after repairs are verified",
    "on revisit",
    "SITE REVISIT (technician returns with an engineer-specified capture list)",
    "-- A concealed support or connection governs the result, return after the owner's contractor opens it",
    "and photograph it",
    "-- The first visit showed something the job list did not cover, return with an added list",
    "-- Conflicting evidence (plans vs. photos vs. measurements), return for the specific items that settle it",
    "-- Repairs required, return after repairs to verify each item on the repair list",
    "DECLINE",
    "-- No written request from the permitting authority",
    "-- Request needs drawings or a repair method, route to design or repair specification line",
    "-- Request covered by another protocol, route to that line",
    "-- Concealed element and the owner will not have it opened",
    "-- Open insurance claim or litigation, decline, with a referral to an independent firm",
    "-- Customer requests a predetermined conclusion, automatic decline, log verbatim request",
    "Appendix D. References",
    "Item Location",
    "International Residential",
    "Code",
    "As adopted by the authority having jurisdiction",
    "International Building Code As adopted by the authority having jurisdiction",
    "International Existing",
    "Building Code",
    "As adopted by the authority having jurisdiction",
    "ASCE 7, Minimum Design",
    "Loads and Associated",
    "Criteria for Buildings and",
    "Other Structures",
    "Edition referenced by the adopted code",
    "Texas Engineering Practice statutes.capitol.texas.gov",
    "Act, Texas Occupations",
    "Code Chapter 1001",
    "TBPELS rules, 22 TAC",
    "Chapter 137",
    "pels.texas.gov",
    "254-RC-001 Roof",
    "Certification Protocol, v1.1,",
    "issued September 18, 2026",
    "Firm document",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const PL001_COUNTS = [
  {
    "key": "field-1",
    "prompt": "Job / Dispatch No.: ____________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-2",
    "prompt": "Property address (full, incl. county):",
    "at": "Appendix B"
  },
  {
    "key": "field-3",
    "prompt": "Technician name: ______________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-4",
    "prompt": "Date / arrival time / departure time: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-5",
    "prompt": "Weather during visit: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-6",
    "prompt": "Contact on site (name, role, phone): ________________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-7",
    "prompt": "Material ________________ size (in.) ________ x ________ span (ft-in.) ________ spacing (in.)",
    "at": "Appendix B"
  },
  {
    "key": "field-8",
    "prompt": "Supports ____ connections ____ items concealed ____",
    "at": "Appendix B"
  },
  {
    "key": "field-9",
    "prompt": "Total photos: ______________",
    "at": "Appendix B"
  },
  {
    "key": "field-10",
    "prompt": "Technician signature / date: ____________________________________________",
    "at": "Appendix B"
  }
];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const PL001_OTHER_RULES = [];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const PL001_BLANK_JOB_LIST_ITEMS = 5;
