/**
 * 254-RS-001 v1.1, Repair Specification Protocol for Existing Structures.
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-RS-001_Repair_Specification_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 c7913d6637f2a08b1cd09a49c1767c682895db864143005a07bba99def8c2dd2. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const RS001 = {
  "documentNumber": "254-RS-001",
  "title": "Repair Specification Protocol for Existing Structures",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Aman Dhakal, P.E., Engineer of Record, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record",
  "appliesTo": "All repair specification engagements performed by 254 Engineering Services",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "repair-specifications",
  "serviceTier": null,
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-RS-001_Repair_Specification_Protocol_v1_1.pdf",
  "sourceSha256": "c7913d6637f2a08b1cd09a49c1767c682895db864143005a07bba99def8c2dd2",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "job-information",
      "heading": "JOB INFORMATION",
      "at": "Appendix B"
    },
    {
      "key": "context",
      "heading": "CONTEXT (every job)",
      "at": "Appendix B"
    },
    {
      "key": "the-damage",
      "heading": "THE DAMAGE (each location)",
      "at": "Appendix B"
    },
    {
      "key": "adjacent-construction",
      "heading": "ADJACENT CONSTRUCTION (each location)",
      "at": "Appendix B"
    },
    {
      "key": "foundation-damage",
      "heading": "FOUNDATION DAMAGE (only where the damage is to the foundation)",
      "at": "Appendix B"
    },
    {
      "key": "close-out",
      "heading": "CLOSE-OUT",
      "at": "Appendix B"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the structure, mark every damaged location, and mark North. Take a photo of it.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix B, PHOTOS"
    }
  ],
  "intakeQuestions": [
    {
      "number": 1,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What does the customer believe is wrong, and where? (record exactly)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 2,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Who is the repair for? (owner / buyer / lender / insurer / permitting authority / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 3,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "If someone else requires the repair, what does their request say? (record exactly, or attach it)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 4,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What deadline is the customer working against, if any?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 5,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property address and county",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 6,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property type (single family / duplex / townhome / small commercial) and number of stories",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 7,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Year built",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 8,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "What is damaged? (roof framing / floor framing / wall / beam or post / deck / foundation / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 9,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "When was the damage first noticed, and has it changed since?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 10,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Did this come from another 254 job? If yes, the job number",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 11,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there an OPEN insurance claim on this damage?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 12,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there active or threatened litigation involving this damage?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 13,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is any part of the structure shored, braced, or unsafe to enter?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 14,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has a repair already been started or attempted?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 15,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has another engineer already issued a report or repair plan for this damage?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 16,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Will the repair need a permit?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 17,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Where is the damage, and how is it reached? (attic / crawlspace / interior / exterior)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 18,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Occupied or vacant? Accessible if occupied?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 19,
      "group": "prior-paperwork",
      "groupHeading": "Prior paperwork prompt",
      "ask": "Do you have: plans, an inspection report, a contractor's estimate, an earlier engineer report, photos of the damage?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    }
  ],
  "intakeUploads": [
    {
      "key": "photo-of-the-front-of-the-1",
      "what": "Photo of the front of the property (confirms address/structure)",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "customer-s-own-photos-of-the-2",
      "what": "Customer's own photos of the damage",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-report-on-the-damage-from-3",
      "what": "Any report on the damage from an engineer, inspector, or insurer",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-third-party-s-written-request-4",
      "what": "Any third party's written request for the repair",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "plans-or-drawings-of-the-structure-5",
      "what": "Plans or drawings of the structure",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "contractor-s-estimate-or-proposed-repair-6",
      "what": "Contractor's estimate or proposed repair",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "permit-or-correction-notice-7",
      "what": "Permit or correction notice",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    }
  ],
  "checklist": [
    {
      "key": "photo-of-address-marker-house-number",
      "section": "job-information",
      "label": "Photo of address marker (house number, street sign, or mailbox)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "all-four-elevations-of-the-structure",
      "section": "context",
      "label": "All four elevations of the structure",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-room-or-area-each-damaged",
      "section": "context",
      "label": "The room or area each damaged location is in, from two directions",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-shoring-bracing-or-temporary-support",
      "section": "context",
      "label": "Any shoring, bracing, or temporary support in place",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-damaged-member-or-area-overall",
      "section": "the-damage",
      "label": "The damaged member or area overall",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-damage-close-up-ruler-in",
      "section": "the-damage",
      "label": "The damage close up, ruler in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "where-the-damage-starts-and-where",
      "section": "the-damage",
      "label": "Where the damage starts and where it ends, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-sag-lean-or-movement-with",
      "section": "the-damage",
      "label": "Any sag, lean, or movement, with a level or string line in frame",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-water-stain-rot-rust-or",
      "section": "the-damage",
      "label": "Any water, stain, rot, rust, or insect evidence at or near the damage",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-earlier-repair-at-or-near",
      "section": "the-damage",
      "label": "Any earlier repair at or near the damage",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-same-member-beyond-the-damage",
      "section": "adjacent-construction",
      "label": "The same member beyond the damage, to its supports at each end",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "span-between-supports-and-spacing-to",
      "section": "adjacent-construction",
      "label": "Span between supports and spacing to the next members, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-support-and-connection-of-the",
      "section": "adjacent-construction",
      "label": "Each support and connection of the damaged member",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "what-the-damaged-member-carries-what",
      "section": "adjacent-construction",
      "label": "What the damaged member carries: what sits on it or frames into it",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "what-is-below-each-support-down",
      "section": "adjacent-construction",
      "label": "What is below each support, down to the foundation where it can be seen",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "working-room-around-the-damage-pipes",
      "section": "adjacent-construction",
      "label": "Working room around the damage: pipes, wires, ducts, and finishes in the way",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-crack-in-the-foundation-wide",
      "section": "foundation-damage",
      "label": "Every crack in the foundation, wide and close, with a ruler or crack comparator card in frame",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "relative-elevation-survey-equipment-and-benchmark",
      "section": "foundation-damage",
      "label": "Relative elevation survey: equipment and benchmark photographed in place, reading points marked on the sketch no more than 20 ft apart",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "the-reading-at-each-point-or",
      "section": "foundation-damage",
      "label": "The reading at each point, or the summary printout",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-pier-beam-and-girder-at",
      "section": "foundation-damage",
      "label": "Every pier, beam, and girder at the damage, from the crawlspace (pier-and-beam only)",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "standing-water-wet-soil-and-drainage",
      "section": "foundation-damage",
      "label": "Standing water, wet soil, and drainage at the damaged side",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "any-earlier-foundation-repair-tags-plates",
      "section": "foundation-damage",
      "label": "Any earlier foundation repair: tags, plates, or patches",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "full-perimeter-walk-anything-unusual",
      "section": "close-out",
      "label": "Full perimeter walk: anything unusual",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exception-menu-cleared-for-every-non",
      "section": "close-out",
      "label": "Exception menu cleared for every non-applicable item",
      "photo": false,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    }
  ],
  "determinations": [
    {
      "key": "pass",
      "heading": "PASS (specification issued)",
      "effect": "specification issued",
      "criteria": [
        "Package complete: every checklist item present or properly excepted for every damaged location",
        "The extent of the damage is established at every location",
        "The sound construction the repair ties into is established: size, span, supports, and connections",
        "The repair can be specified to the adopted code from the evidence and the engineer's calculation"
      ],
      "at": "Appendix C"
    },
    {
      "key": "revise",
      "heading": "REVISE",
      "effect": null,
      "criteria": [
        "Any required photo missing, blurry, or missing its tape",
        "A damaged location with no record of where the damage ends",
        "A support or connection of the damaged member with no photo",
        "Counts or measurements inconsistent with photos"
      ],
      "at": "Appendix C"
    },
    {
      "key": "repairs-required",
      "heading": "REPAIRS REQUIRED (verification only, completion letter withheld, list issued)",
      "effect": "verification only, completion letter withheld, list issued",
      "criteria": [
        "Completed work does not match the specification in material, size, fastening, or location",
        "Work was covered with no photograph, or a hold point was passed without release",
        "Damage found during the work was not reported and repaired",
        "The completion letter proceeds only after each item is verified on revisit"
      ],
      "at": "Appendix C"
    },
    {
      "key": "site-revisit",
      "heading": "SITE REVISIT (technician returns with an engineer-specified capture list)",
      "effect": "technician returns with an engineer-specified capture list",
      "criteria": [
        "The damage runs into a concealed area, return after the owner's contractor opens it and photograph it",
        "A support that could not be seen governs the repair, return to find and measure it",
        "The contractor reports a condition that differs from the specification, return and capture it",
        "Verification ordered, return after the work to capture each item of the specification"
      ],
      "at": "Appendix C"
    },
    {
      "key": "decline",
      "heading": "DECLINE",
      "effect": null,
      "criteria": [
        "Not a repair: new construction, addition, or alteration, route to design line",
        "Open insurance claim where the specification would function as claim leverage, decline, with a referral to an independent firm",
        "Active or threatened litigation, decline",
        "Request is for the cause of the damage, decline, with a referral to an independent firm",
        "Foundation repair the engineer does not accept at intake, decline, with a referral to a foundation engineer",
        "Repair depends on a geotechnical opinion, decline, with a referral to a geotechnical engineer",
        "Damage cannot be reached or seen and the owner will not provide access",
        "Structure unsafe to enter",
        "Customer requests a predetermined conclusion, automatic decline, log verbatim request"
      ],
      "at": "Appendix C"
    }
  ],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Repair Specification Protocol",
    "Document Value",
    "Title Repair Specification Protocol for Existing Structures",
    "Document number 254-RS-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Aman Dhakal, P.E., Engineer of Record, 254 Engineering",
    "Services",
    "Approval Aman Dhakal, P.E., Engineer of Record",
    "Applies to All repair specification engagements performed by 254",
    "Engineering Services",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services prepares a repair specification for an",
    "existing structure so that the engineer can issue a sealed specification that a contractor can price",
    "and build from, supported by an evidence package collected by a field technician under the",
    "engineer's supervision.",
    "The engineer signs and seals the specification personally. Every requirement in this protocol exists",
    "so that the engineer can specify the repair from the evidence package alone.",
    "2. Scope",
    "This protocol applies to repair of a structural element of an existing residential or light commercial",
    "structure: roof, floor, and wall framing, beams, headers, posts, and decks. Foundation repair is taken",
    "only where the engineer accepts the job at intake.",
    "A repair specification is a sealed document that states what is to be repaired, with what materials",
    "and sizes, how it is fastened and supported, in what order, and what the contractor photographs",
    "before it is covered.",
    "A repair specification is not the repair list issued under a certification protocol. A repair list names",
    "what is deficient and what must be achieved. A repair specification says how.",
    "This protocol does not cover new construction or additions, which are design; repair of roof",
    "coverings, finishes, plumbing, or drainage; or geotechnical work. The firm does not perform forensic",
    "or cause-of-loss investigation under this or any protocol.",
    "3. Governing requirements",
    "• The building code adopted by the authority having jurisdiction, including the International",
    "Existing Building Code where adopted. The coordinator records the authority and the code",
    "edition at intake. The engineer confirms both.",
    "• Where a third party requires the repair, their requirement is recorded verbatim at intake.",
    "• Texas Engineering Practice Act and TBPELS rules, 22 TAC Chapter 137.",
    "• The specification addresses the condition observed on the inspection date. It is not a warranty",
    "that the repair will prevent future damage, and it does not state the cause of the damage.",
    "4. Roles and responsibilities",
    "Only the Engineer of Record determines what is repaired, how, and the wording of the specification.",
    "The field technician and the coordinator relay the engineer's written determination without",
    "interpretation, addition, or estimate of when a specification will issue.",
    "• The contractor is responsible for means and methods, temporary shoring, and site safety. The",
    "specification says so.",
    "5. Personnel qualifications",
    "Field Technician",
    "• At least two years of documented experience in residential construction, framing, foundation",
    "repair, or structural inspection, or equivalent experience the engineer accepts in writing.",
    "• Completion of the engineer's training on this protocol and Appendix B, with a supervised",
    "inspection before independent work.",
    "• Confined-space awareness training where crawlspace access is required.",
    "• Annual refresher training when the adopted code, this protocol, or Appendix B changes.",
    "Engineer of Record",
    "• Active Texas P.E. license. A copy, with expiration date, is held in the firm's compliance file.",
    "6. Intake",
    "• The coordinator opens a job file for each request. The file records the intake answers and",
    "customer uploads required by Appendix A.",
    "• The coordinator records what the customer believes is wrong, who the repair is for, and any",
    "third party requirement, exactly as given.",
    "• A job may also be opened from a repairs required determination on another service line. The",
    "existing job file is attached, and the engineer decides whether its evidence is enough or a visit",
    "is needed.",
    "• A yes to any flag question in Appendix A, or damage to the foundation, routes the job to the",
    "engineer before dispatch. The engineer records accept, accept with conditions, or decline.",
    "• A job is not dispatched until intake is complete and every upload required by Appendix A has",
    "been received.",
    "• The engineer records any condition of acceptance in the job file, including any item the",
    "technician must capture beyond Appendix B.",
    "7. Scheduling and dispatch",
    "• The coordinator schedules an accepted job within two business days. The engineer may set a",
    "different interval for a job in the job file.",
    "• The technician confirms access and occupancy before travel, and confirms that the damaged",
    "element can be reached.",
    "• Where site conditions prevent complete capture, including weather, access, or safety, the",
    "technician records each item that could not be observed and the reason. No item is estimated,",
    "assumed, or left blank.",
    "• A specification is not written without a technician visit, except where an earlier job file of this",
    "firm already holds the evidence and the engineer finds it is still current.",
    "8. Field inspection",
    "The technician completes every item of Appendix B, in the order listed, and follows the photo",
    "procedure printed at the head of that checklist.",
    "• Before starting, the technician makes a rough sketch of the structure, marks North, marks",
    "every damaged location, and photographs the sketch.",
    "• The technician ticks the item being photographed, photographs the checklist, then takes the",
    "photographs for that item, and moves to the next item the same way.",
    "• An item that does not apply is marked with the reason it does not apply.",
    "• The counts and measurements called for are recorded as counts and measurements, not as",
    "descriptions.",
    "• The technician records the damage, how far it extends, and the sound construction next to it",
    "that the repair will tie into.",
    "• The technician gives no opinion on the cause of the damage or on how it should be repaired.",
    "9. Evidence standard and engineer review",
    "Evidence package",
    "Each job produces one evidence package in the firm's field application, consisting of the completed",
    "Appendix B checklist, the photographs, and the technician's notes.",
    "• Every checklist item has at least one wide photograph placing the item on the structure and",
    "one close photograph showing its condition.",
    "• Every measurement has the tape in frame.",
    "• Every damaged location is photographed individually, to the full extent of the damage.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location. Photographs sent by text or messaging app,",
    "or taken on another device, are not accepted.",
    "• An observation that cannot be made is recorded as not observed with the reason.",
    "• A package that does not cover every checklist item is rejected without review.",
    "Engineer review",
    "• The engineer reviews each evidence package, performs the calculation the repair needs, and",
    "records one of the five determinations in Appendix C: pass, revise, repairs required, site revisit,",
    "or decline.",
    "• On this service line a pass means the evidence supports a specification, and repairs required",
    "is used only when completed work is verified.",
    "• The engineer's review record identifies the photographs and calculation relied on. The",
    "calculation is kept in the job file.",
    "10. Deficiencies and repairs",
    "• Repairs are performed by others. 254 Engineering Services does not perform, supervise, or",
    "recommend a contractor for the repair work.",
    "• Where an item will be covered by later work, the contractor photographs it before it is covered",
    "and keeps the photographs for verification. The engineer may set a hold point on a single item",
    "where a photograph is not enough. Work stops at that item until a verification visit is ordered",
    "and the engineer releases it.",
    "• Verification of completed repairs is not part of the specification. It is ordered separately. When",
    "it is ordered, the technician returns after the work, captures each item of the specification to",
    "the same evidence standard along with the contractor's photographs of covered work, and the",
    "engineer closes each item individually.",
    "• Where the completed work does not match the specification, the engineer records repairs",
    "required and issues a written list of each item and what is required to close it.",
    "• On verification with every item closed, the engineer issues a sealed letter stating that the",
    "repairs observed conform to the specification. No completion letter is issued with an open item.",
    "11. Repair specification",
    "• On a pass determination, the engineer issues a sealed repair specification addressed to the",
    "customer recorded at intake.",
    "• The specification identifies the property, the date of inspection, each damaged location, and for",
    "each one: the location, the work, the material and standard, and the quantity where it can be",
    "measured. Items are performed in the order listed unless an item says otherwise.",
    "• The specification includes the sketches or details the contractor needs to build it.",
    "• The specification covers the locations it names only. It states that other damage may exist",
    "where the structure was concealed, and that the contractor stops and reports any condition",
    "that differs from the specification.",
    "• The specification states that it does not determine the cause of the damage. Where the",
    "damage will return unless something outside the firm's scope is corrected, such as a leak or",
    "drainage, the specification says so.",
    "• The specification does not warrant the repair and does not forecast future performance.",
    "• The specification is based on condition on the inspection date and says so.",
    "12. Exclusions",
    "The following are declined or routed to another service line under its own engagement terms. The",
    "coordinator records the routing in the job file and informs the customer in writing.",
    "• New construction, an addition, or a change to the structure that is not a repair. Routed to the",
    "design line.",
    "• An open insurance claim on the damage, where the specification would function as claim",
    "leverage. Declined, with a referral to an independent firm.",
    "• Active or threatened litigation involving the damage. Declined.",
    "• A request to state the cause of the damage. Declined, with a referral to an independent firm.",
    "• A foundation repair the engineer does not accept at intake. Declined, with a referral to a",
    "foundation engineer.",
    "• A repair that depends on a geotechnical opinion or soil testing. Declined, with a referral to a",
    "geotechnical engineer.",
    "• Damage that cannot be reached or seen where the owner will not provide access. Declined.",
    "• A structure that is unsafe to enter. Declined. The coordinator tells the customer in writing the",
    "same day.",
    "• A customer request for a predetermined conclusion. This is an automatic decline and the",
    "request is logged verbatim.",
    "13. Records and retention",
    "• Each job file contains: the intake record and customer uploads, any job file from another",
    "service line the job came from, the engineer's acceptance record, the dispatch record, the",
    "completed Appendix B checklist, all photographs, the technician's notes, the engineer's",
    "calculation, review record and determination, the issued specification, and any verification",
    "record, list, and completion letter.",
    "• Job files are retained for ten years from the date of the specification, or from the date of the",
    "completion letter where there is one. For a job that produces no specification, the ten years",
    "runs from the date of the engineer's last recorded determination or closure.",
    "• Ten years is the firm's floor, reviewed against TBPELS rules.",
    "• The compliance file holds the engineer's license records, technician qualification and training",
    "records, and every issued version of this protocol.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the",
    "adopted code or to the firm's field application.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table.",
    "• This document follows the firm's house protocol format. The portal's four parts are carried in",
    "Appendices A through C. Appendix A carries both the intake questions and the customer",
    "uploads. Appendix D is the reference list.",
    "Appendix A. Intake questions and customer uploads",
    "Asked and collected by the coordinator before the job is created. A job is not dispatched until every",
    "required item is present.",
    "PART 1: INTAKE QUESTIONS",
    "Purpose & recipient",
    "1. What does the customer believe is wrong, and where? (record exactly)",
    "Answer: ____________________________________________________",
    "2. Who is the repair for? (owner / buyer / lender / insurer / permitting authority / other)",
    "Answer: ____________________________________________________",
    "3. If someone else requires the repair, what does their request say? (record exactly, or attach it)",
    "Answer: ____________________________________________________",
    "4. What deadline is the customer working against, if any?",
    "Answer: ____________________________________________________",
    "Property basics",
    "5. Property address and county",
    "Answer: ____________________________________________________",
    "6. Property type (single family / duplex / townhome / small commercial) and number of stories",
    "Answer: ____________________________________________________",
    "7. Year built",
    "Answer: ____________________________________________________",
    "8. What is damaged? (roof framing / floor framing / wall / beam or post / deck / foundation / other)",
    "Answer: ____________________________________________________",
    "9. When was the damage first noticed, and has it changed since?",
    "Answer: ____________________________________________________",
    "10. Did this come from another 254 job? If yes, the job number",
    "Answer: ____________________________________________________",
    "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
    "11. Is there an OPEN insurance claim on this damage?",
    "Yes No If yes, describe: ____________________________________________________",
    "12. Is there active or threatened litigation involving this damage?",
    "Yes No If yes, describe: ____________________________________________________",
    "13. Is any part of the structure shored, braced, or unsafe to enter?",
    "Yes No If yes, describe: ____________________________________________________",
    "14. Has a repair already been started or attempted?",
    "Yes No If yes, describe: ____________________________________________________",
    "15. Has another engineer already issued a report or repair plan for this damage?",
    "Yes No If yes, describe: ____________________________________________________",
    "16. Will the repair need a permit?",
    "Yes No If yes, describe: ____________________________________________________",
    "Access & safety (decides dispatch feasibility)",
    "17. Where is the damage, and how is it reached? (attic / crawlspace / interior / exterior)",
    "Answer: ____________________________________________________",
    "18. Occupied or vacant? Accessible if occupied?",
    "Answer: ____________________________________________________",
    "Prior paperwork prompt",
    "19. Do you have: plans, an inspection report, a contractor's estimate, an earlier engineer report,",
    "photos of the damage?",
    "Answer: ____________________________________________________",
    "PART 2: CUSTOMER UPLOADS (collected at intake, before dispatch)",
    "Required",
    "-- Photo of the front of the property (confirms address/structure)",
    "-- Customer's own photos of the damage",
    "Required if it exists",
    "-- Any report on the damage from an engineer, inspector, or insurer",
    "-- Any third party's written request for the repair",
    "Collect when applicable",
    "-- Plans or drawings of the structure",
    "-- Contractor's estimate or proposed repair",
    "-- Permit or correction notice",
    "Appendix B. Technician on-site checklist",
    "Completed on site by the technician. The checklist cannot be submitted incomplete. Complete the",
    "damage and adjacent construction sections once for each damaged location.",
    "PHOTOS",
    "-- Before starting, make a rough sketch of the structure, mark every damaged location, and mark",
    "North. Take a photo of it.",
    "-- Tick the item you are about to photograph, take a photo of the checklist, then take the photos for",
    "that item.",
    "-- Move on to the next item the same way.",
    "JOB INFORMATION",
    "Job / Dispatch No.: ____________________________",
    "Property address (full, incl. county):",
    "__________________________________________________________",
    "Technician name: ______________________________________",
    "Date / arrival time / departure time: ________________________________________",
    "Weather during visit: ________________________________________",
    "Contact on site (name, role, phone): ________________________________________________",
    "[ ] Photo of address marker (house number, street sign, or mailbox) [PHOTO]",
    "CONTEXT (every job)",
    "[ ] All four elevations of the structure [PHOTO]",
    "[ ] The room or area each damaged location is in, from two directions [PHOTO]",
    "[ ] Any shoring, bracing, or temporary support in place [PHOTO]",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "THE DAMAGE (each location)",
    "[ ] The damaged member or area overall [PHOTO]",
    "[ ] The damage close up, ruler in frame [PHOTO]",
    "[ ] Where the damage starts and where it ends, tape in frame [PHOTO]",
    "[ ] Any sag, lean, or movement, with a level or string line in frame [PHOTO]",
    "[ ] Any water, stain, rot, rust, or insect evidence at or near the damage [PHOTO]",
    "[ ] Any earlier repair at or near the damage [PHOTO]",
    "Member material ________________ size (in.) ________ x ________ length of damage (ft-in.)",
    "________",
    "Sag or lean measured (in.) ________ over (ft) ________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "ADJACENT CONSTRUCTION (each location)",
    "[ ] The same member beyond the damage, to its supports at each end [PHOTO]",
    "[ ] Span between supports and spacing to the next members, tape in frame [PHOTO]",
    "[ ] Each support and connection of the damaged member [PHOTO]",
    "[ ] What the damaged member carries: what sits on it or frames into it [PHOTO]",
    "[ ] What is below each support, down to the foundation where it can be seen [PHOTO]",
    "[ ] Working room around the damage: pipes, wires, ducts, and finishes in the way [PHOTO]",
    "Span (ft-in.) ________ spacing (in.) ________ supports ____ connections ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "FOUNDATION DAMAGE (only where the damage is to the foundation)",
    "[ ] Every crack in the foundation, wide and close, with a ruler or crack comparator card in frame",
    "[PHOTO]",
    "[ ] Relative elevation survey: equipment and benchmark photographed in place, reading points",
    "marked on the sketch no more than 20 ft apart [PHOTO]",
    "[ ] The reading at each point, or the summary printout [PHOTO]",
    "[ ] Every pier, beam, and girder at the damage, from the crawlspace (pier-and-beam only) [PHOTO]",
    "[ ] Standing water, wet soil, and drainage at the damaged side [PHOTO]",
    "[ ] Any earlier foundation repair: tags, plates, or patches [PHOTO]",
    "Benchmark location: ________________ largest difference between two points (in.): ________ over",
    "(ft): ________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CLOSE-OUT",
    "[ ] Full perimeter walk: anything unusual [PHOTO]",
    "[ ] Exception menu cleared for every non-applicable item",
    "Total photos: ______________",
    "Technician signature / date: ____________________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Appendix C. Engineer decision rules",
    "Applied by the engineer to each evidence package. One determination is recorded per review.",
    "PASS (specification issued)",
    "-- Package complete: every checklist item present or properly excepted for every damaged location",
    "-- The extent of the damage is established at every location",
    "-- The sound construction the repair ties into is established: size, span, supports, and connections",
    "-- The repair can be specified to the adopted code from the evidence and the engineer's calculation",
    "REVISE",
    "-- Any required photo missing, blurry, or missing its tape",
    "-- A damaged location with no record of where the damage ends",
    "-- A support or connection of the damaged member with no photo",
    "-- Counts or measurements inconsistent with photos",
    "REPAIRS REQUIRED (verification only, completion letter withheld, list issued)",
    "-- Completed work does not match the specification in material, size, fastening, or location",
    "-- Work was covered with no photograph, or a hold point was passed without release",
    "-- Damage found during the work was not reported and repaired",
    "-- The completion letter proceeds only after each item is verified on revisit",
    "SITE REVISIT (technician returns with an engineer-specified capture list)",
    "-- The damage runs into a concealed area, return after the owner's contractor opens it and",
    "photograph it",
    "-- A support that could not be seen governs the repair, return to find and measure it",
    "-- The contractor reports a condition that differs from the specification, return and capture it",
    "-- Verification ordered, return after the work to capture each item of the specification",
    "DECLINE",
    "-- Not a repair: new construction, addition, or alteration, route to design line",
    "-- Open insurance claim where the specification would function as claim leverage, decline, with a",
    "referral to an independent firm",
    "-- Active or threatened litigation, decline",
    "-- Request is for the cause of the damage, decline, with a referral to an independent firm",
    "-- Foundation repair the engineer does not accept at intake, decline, with a referral to a foundation",
    "engineer",
    "-- Repair depends on a geotechnical opinion, decline, with a referral to a geotechnical engineer",
    "-- Damage cannot be reached or seen and the owner will not provide access",
    "-- Structure unsafe to enter",
    "-- Customer requests a predetermined conclusion, automatic decline, log verbatim request",
    "Appendix D. References",
    "Item Location",
    "International Residential",
    "Code",
    "As adopted by the authority having jurisdiction",
    "International Building Code As adopted by the authority having jurisdiction",
    "International Existing",
    "Building Code",
    "As adopted by the authority having jurisdiction",
    "ASCE 7, Minimum Design",
    "Loads and Associated",
    "Criteria for Buildings and",
    "Other Structures",
    "Edition referenced by the adopted code",
    "National Design",
    "Specification for Wood",
    "Construction, American",
    "Wood Council",
    "Edition referenced by the adopted code",
    "ACI 318, Building Code",
    "Requirements for Structural",
    "Concrete",
    "Edition referenced by the adopted code",
    "Texas Engineering Practice",
    "Act, Texas Occupations",
    "Code Chapter 1001",
    "statutes.capitol.texas.gov",
    "TBPELS rules, 22 TAC",
    "Chapter 137",
    "pels.texas.gov",
    "254-RC-001 Roof",
    "Certification Protocol, v1.1,",
    "issued September 18, 2026",
    "Firm document",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const RS001_COUNTS = [
  {
    "key": "field-1",
    "prompt": "Job / Dispatch No.: ____________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-2",
    "prompt": "Property address (full, incl. county):",
    "at": "Appendix B"
  },
  {
    "key": "field-3",
    "prompt": "Technician name: ______________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-4",
    "prompt": "Date / arrival time / departure time: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-5",
    "prompt": "Weather during visit: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-6",
    "prompt": "Contact on site (name, role, phone): ________________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-7",
    "prompt": "Member material ________________ size (in.) ________ x ________ length of damage (ft-in.)",
    "at": "Appendix B"
  },
  {
    "key": "field-8",
    "prompt": "Sag or lean measured (in.) ________ over (ft) ________",
    "at": "Appendix B"
  },
  {
    "key": "field-9",
    "prompt": "Span (ft-in.) ________ spacing (in.) ________ supports ____ connections ____",
    "at": "Appendix B"
  },
  {
    "key": "field-10",
    "prompt": "Benchmark location: ________________ largest difference between two points (in.): ________ over",
    "at": "Appendix B"
  },
  {
    "key": "field-11",
    "prompt": "(ft): ________",
    "at": "Appendix B"
  },
  {
    "key": "field-12",
    "prompt": "Total photos: ______________",
    "at": "Appendix B"
  },
  {
    "key": "field-13",
    "prompt": "Technician signature / date: ____________________________________________",
    "at": "Appendix B"
  }
];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const RS001_OTHER_RULES = [];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const RS001_BLANK_JOB_LIST_ITEMS = 0;
