/**
 * 254-SL-001 v1.1, Solar Structural Letter Protocol for Existing Roofs.
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-SL-001_Solar_Structural_Letter_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 7bac29a7021086a7a40906021de5be9c2c2efaba747db33877410dd7b5c4e8f3. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const SL001 = {
  "documentNumber": "254-SL-001",
  "title": "Solar Structural Letter Protocol for Existing Roofs",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Aman Dhakal, P.E., Engineer of Record, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record",
  "appliesTo": "All solar structural letter engagements performed by 254 Engineering Services",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "solar-structural-letters",
  "serviceTier": null,
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-SL-001_Solar_Structural_Letter_Protocol_v1_1.pdf",
  "sourceSha256": "7bac29a7021086a7a40906021de5be9c2c2efaba747db33877410dd7b5c4e8f3",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "job-information",
      "heading": "JOB INFORMATION",
      "at": "Appendix B"
    },
    {
      "key": "context",
      "heading": "CONTEXT (every job)",
      "at": "Appendix B"
    },
    {
      "key": "framing",
      "heading": "FRAMING (each plane)",
      "at": "Appendix B"
    },
    {
      "key": "condition",
      "heading": "CONDITION (each plane)",
      "at": "Appendix B"
    },
    {
      "key": "close-out",
      "heading": "CLOSE-OUT",
      "at": "Appendix B"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the roof, mark the planes the array will occupy, and mark North. Take a photo of it.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix B, PHOTOS"
    }
  ],
  "intakeQuestions": [
    {
      "number": 1,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What is the letter for? (permit / installer / lender / other, record exactly)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 2,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Who will the letter be addressed to?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 3,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "Which city or county issues the permit, and which code edition does it enforce?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 4,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & recipient",
      "ask": "What deadline is the customer working against, if any?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 5,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property address and county",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 6,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property type (single family / duplex / townhome / small commercial) and number of stories",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 7,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Year built",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 8,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Roof framing, if known (rafters / trusses / other)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 9,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Roof covering type",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 10,
      "group": "property-basics",
      "groupHeading": "Proposed array",
      "ask": "Installer name, contact, and the installer's engineer if there is one",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 11,
      "group": "property-basics",
      "groupHeading": "Proposed array",
      "ask": "Module make and model, number of modules, and weight of each",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 12,
      "group": "property-basics",
      "groupHeading": "Proposed array",
      "ask": "Racking make and model, attachment type, and attachment spacing",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 13,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there already solar or other equipment on the roof planes the array will use?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 14,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has the roof framing been cut, altered, or repaired, or is any sag or damage known?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 15,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there more than one layer of roof covering?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 16,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is the roof framed with something other than wood? (steel, concrete)",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 17,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is the roof flat or low-slope?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 18,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there no attic or other way to see the roof framing?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 19,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there an open insurance claim or litigation involving the roof?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 20,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has another engineer already declined to issue a letter for this roof?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 21,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Where is the attic access, and is the attic clear enough to move through?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 22,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Occupied or vacant? Accessible if occupied?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 23,
      "group": "prior-paperwork",
      "groupHeading": "Prior paperwork prompt",
      "ask": "Do you have: house plans, truss drawings, an earlier engineer letter, the permit application, the installer's site survey?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    }
  ],
  "intakeUploads": [
    {
      "key": "photo-of-the-front-of-the-1",
      "what": "Photo of the front of the property (confirms address/structure)",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "array-layout-showing-the-module-locations-2",
      "what": "Array layout showing the module locations on each roof plane, with its date",
      "tier": "before-calculation",
      "when": null,
      "tierHeading": "Required before the engineer calculates",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "module-and-racking-data-sheets-3",
      "what": "Module and racking data sheets",
      "tier": "before-calculation",
      "when": null,
      "tierHeading": "Required before the engineer calculates",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "attachment-type-and-spacing-from-the-4",
      "what": "Attachment type and spacing, from the installer",
      "tier": "before-calculation",
      "when": null,
      "tierHeading": "Required before the engineer calculates",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "house-plans-or-truss-drawings-5",
      "what": "House plans or truss drawings",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-earlier-engineer-letter-on-this-6",
      "what": "Any earlier engineer letter on this roof",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "permit-application-and-any-comment-from-7",
      "what": "Permit application and any comment from the permitting authority",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "installer-s-site-survey-photos-required-8",
      "what": "Installer's site survey photos (required where the engineer accepts them in place of a visit)",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "data-for-existing-rooftop-equipment-on-9",
      "what": "Data for existing rooftop equipment on the same planes",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    }
  ],
  "checklist": [
    {
      "key": "photo-of-address-marker-house-number",
      "section": "job-information",
      "label": "Photo of address marker (house number, street sign, or mailbox)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "all-four-elevations-of-the-structure",
      "section": "context",
      "label": "All four elevations of the structure",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-roof-plane-the-array-will",
      "section": "context",
      "label": "Each roof plane the array will occupy, from the ground or the roof",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "roof-covering-at-an-edge-showing",
      "section": "context",
      "label": "Roof covering at an edge, showing type and number of layers",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "everything-already-on-those-planes-vents",
      "section": "context",
      "label": "Everything already on those planes: vents, equipment, existing solar",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "framing-overall-from-the-attic-access",
      "section": "framing",
      "label": "Framing overall from the attic access",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "framing-type-rafter-truss-other",
      "section": "framing",
      "label": "Framing type (rafter / truss / other)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "member-depth-and-width-tape-in",
      "section": "framing",
      "label": "Member depth and width, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "spacing-center-to-center-measured-at",
      "section": "framing",
      "label": "Spacing center to center, measured at three places, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "span-tape-from-one-support-to",
      "section": "framing",
      "label": "Span: tape from one support to the next, both ends in the photos",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "what-supports-the-member-at-each",
      "section": "framing",
      "label": "What supports the member at each end and in between (wall, ridge, purlin, brace, knee wall)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "lumber-grade-stamp-if-one-can",
      "section": "framing",
      "label": "Lumber grade stamp, if one can be found",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "trusses-tag-or-stamp-web-pattern",
      "section": "framing",
      "label": "Trusses: tag or stamp, web pattern from the side, and one metal plate close up",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "ridge-board-or-beam-collar-ties",
      "section": "framing",
      "label": "Ridge board or beam, collar ties, and ceiling joists: size and spacing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "roof-sheathing-type-and-thickness-from",
      "section": "framing",
      "label": "Roof sheathing type and thickness, from a stamp or an exposed edge",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "sight-line-along-the-ridge-and",
      "section": "condition",
      "label": "Sight line along the ridge and down the plane, showing any sag",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-split-crack-notch-or-cut",
      "section": "condition",
      "label": "Every split, crack, notch, or cut member",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-truss-member-that-has-been",
      "section": "condition",
      "label": "Every truss member that has been cut, removed, or altered",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-earlier-repair-or-added-member",
      "section": "condition",
      "label": "Every earlier repair or added member",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-water-stain-rot-or-insect",
      "section": "condition",
      "label": "Every water stain, rot, or insect damage on the framing or sheathing",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "full-perimeter-walk-anything-unusual",
      "section": "close-out",
      "label": "Full perimeter walk: anything unusual",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exception-menu-cleared-for-every-non",
      "section": "close-out",
      "label": "Exception menu cleared for every non-applicable item",
      "photo": false,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    }
  ],
  "determinations": [
    {
      "key": "pass",
      "heading": "PASS",
      "effect": null,
      "criteria": [
        "Package complete: every checklist item present or properly excepted for every plane the array will occupy",
        "Array design complete: module, count, weight, racking, attachment type, spacing, and layout",
        "Calculated gravity load on every framing member checked is within its capacity under the adopted code, with the array in place",
        "No damaged, cut, or altered member under the array"
      ],
      "at": "Appendix C"
    },
    {
      "key": "revise",
      "heading": "REVISE",
      "effect": null,
      "criteria": [
        "Any required photo missing, blurry, or missing its tape",
        "Member size recorded as a nominal size, or spacing measured at fewer than three places",
        "Span photo does not show both supports",
        "A plane the array will occupy has no framing record",
        "Array design missing an item needed to calculate",
        "Counts or measurements inconsistent with photos"
      ],
      "at": "Appendix C"
    },
    {
      "key": "repairs-required",
      "heading": "REPAIRS REQUIRED (sealed letter states not adequate, list issued)",
      "effect": "sealed letter states not adequate, list issued",
      "criteria": [
        "Array change required: calculated gravity load is over capacity and a change in module count, layout, or attachment spacing would bring it within",
        "Strengthening required: calculated gravity load is over capacity and no array change would bring it within",
        "A damaged, cut, or altered member under the array",
        "Active leak or rot in the framing or sheathing under the array",
        "A letter stating adequacy proceeds only after a revised array design is recalculated, or repairs are verified on revisit"
      ],
      "at": "Appendix C"
    },
    {
      "key": "site-revisit",
      "heading": "SITE REVISIT (technician returns with an engineer-specified capture list)",
      "effect": "technician returns with an engineer-specified capture list",
      "criteria": [
        "A support that could not be seen governs the result, return to find and measure it",
        "Framing differs from one part of a plane to another and only one was captured, return for the rest",
        "Array layout changed to a plane that was not captured, return for that plane",
        "Conflicting evidence (plans vs. photos vs. measurements), return for the specific items that settle it",
        "Repairs required, return after repairs to verify each item on the list"
      ],
      "at": "Appendix C"
    },
    {
      "key": "decline",
      "heading": "DECLINE",
      "effect": null,
      "criteria": [
        "Roof framing cannot be seen",
        "Ground-mounted array, carport, or canopy, route to design line",
        "Open insurance claim or litigation, decline, with a referral to an independent firm",
        "Customer requests a predetermined conclusion, automatic decline, log verbatim request"
      ],
      "at": "Appendix C"
    }
  ],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Solar Structural Letter Protocol",
    "Document Value",
    "Title Solar Structural Letter Protocol for Existing Roofs",
    "Document number 254-SL-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Aman Dhakal, P.E., Engineer of Record, 254 Engineering",
    "Services",
    "Approval Aman Dhakal, P.E., Engineer of Record",
    "Applies to All solar structural letter engagements performed by 254",
    "Engineering Services",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services evaluates an existing roof structure for a",
    "proposed rooftop solar array so that the engineer can issue a sealed letter, supported by an",
    "evidence package collected by a field technician under the engineer's supervision and by the",
    "engineer's own calculation.",
    "The technician establishes what the existing structure is. The engineer decides by calculation",
    "whether it carries the proposed array. The engineer signs and seals the letter personally and the",
    "permitting authority relies on that opinion.",
    "2. Scope",
    "This protocol applies to existing roofs on residential and light commercial structures where an owner",
    "or installer needs an engineer's opinion that the roof structure can support a proposed rooftop-",
    "mounted photovoltaic array.",
    "This protocol does not cover ground-mounted arrays, carports, or canopies, which are design work;",
    "the design of the modules, racking, or attachment hardware, which is the manufacturer's and",
    "installer's; electrical work, fire setbacks, or waterproofing of roof penetrations; the condition of the",
    "roof covering, which is covered by the roof certification protocol; or strengthening design, which is a",
    "separate service line. The firm does not perform forensic or cause-of-loss investigation under this or",
    "any protocol.",
    "3. Governing requirements",
    "• The building code adopted by the authority having jurisdiction, and the edition of ASCE 7 it",
    "references. The coordinator records the authority and the code edition at intake. The engineer",
    "confirms both before calculating.",
    "• The racking manufacturer's installation manual and engineering for attachment capacity and",
    "attachment spacing.",
    "• Texas Engineering Practice Act and TBPELS rules, 22 TAC Chapter 137.",
    "• The letter is the engineer's professional opinion on the existing roof structure under the",
    "proposed array as described in the array design recorded in the job file. It is not an opinion on",
    "any other array.",
    "4. Roles and responsibilities",
    "Only the Engineer of Record determines the outcome of a job and the wording of the letter. The field",
    "technician and the coordinator relay the engineer's written determination without interpretation,",
    "addition, or estimate of when a letter will issue.",
    "• The technician records and measures what is there. The technician gives no opinion on",
    "whether the framing is adequate, and the checklist does not ask for one.",
    "• The installer supplies the array design. The firm does not prepare or revise it.",
    "5. Personnel qualifications",
    "Field Technician",
    "• At least two years of documented experience in residential framing, roofing, solar installation",
    "site survey, or home inspection, or equivalent experience the engineer accepts in writing.",
    "• Completion of the engineer's training on this protocol and Appendix B, with a supervised",
    "inspection before independent work.",
    "• Demonstrated ability to tell a rafter from a truss, and to measure member size, spacing, and",
    "span.",
    "• Annual refresher training when the adopted code, this protocol, or Appendix B changes.",
    "Engineer of Record",
    "• Active Texas P.E. license. A copy, with expiration date, is held in the firm's compliance file.",
    "6. Intake",
    "• The coordinator opens a job file for each property. The file records the intake answers and",
    "customer uploads required by Appendix A.",
    "• The coordinator records the purpose of the letter and the recipient exactly as given at intake.",
    "The letter is addressed only to that recipient and issued only for that purpose.",
    "• An order is accepted without the array design. No calculation is started and no letter is issued",
    "until it is received.",
    "• There is no default. On every job the engineer decides at intake whether a technician visits or",
    "the job rests on the installer's site survey photographs. Installer photographs are accepted only",
    "where they cover every item of Appendix B.",
    "• A yes to any flag question in Appendix A routes the job to the engineer before dispatch. The",
    "engineer records accept, accept with conditions, or decline.",
    "• A technician is dispatched only on the engineer's decision, and not until intake is complete and",
    "every upload required by Appendix A has been received.",
    "• The engineer records any condition of acceptance in the job file, including any item the",
    "technician must capture beyond Appendix B.",
    "7. Scheduling and dispatch",
    "• Where the engineer calls for a visit, the coordinator schedules it within two business days of",
    "that decision. The engineer may set a different interval for a job in the job file.",
    "• The technician confirms access, occupancy, and attic availability before travel, and carries the",
    "array layout where one has been received.",
    "• Where site conditions prevent complete capture, including weather, access, or safety, the",
    "technician records each item that could not be observed and the reason. No item is estimated,",
    "assumed, or left blank.",
    "8. Field inspection",
    "The technician completes every item of Appendix B for each roof plane the array will occupy, or for",
    "every roof plane that could take an array where no array design has been received, in the order",
    "listed, and follows the photo procedure printed at the head of that checklist.",
    "• Before starting, the technician makes a rough sketch of the roof, marks North, marks the",
    "planes the array will occupy, and photographs the sketch.",
    "• The technician ticks the item being photographed, photographs the checklist, then takes the",
    "photographs for that item, and moves to the next item the same way.",
    "• An item that does not apply to the property is marked with the reason it does not apply.",
    "• Member size, spacing, and span are measured with a tape, to the nearest 1/8 inch for member",
    "size and the nearest inch for spacing and span. Nothing is recorded as a nominal size or an",
    "estimate.",
    "• Where a support is not visible, the technician records what is visible, measures to the last",
    "visible point, and measures the outside width of the building.",
    "9. Evidence standard and engineer review",
    "Evidence package",
    "Each job produces one evidence package in the firm's field application, consisting of the completed",
    "Appendix B checklist, the photographs, the technician's notes, and the array design.",
    "• Every checklist item has at least one wide photograph placing the item on the structure and",
    "one close photograph showing its condition.",
    "• Every measurement has the tape in frame.",
    "• Every damaged, cut, notched, or repaired member is photographed individually.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location. Photographs sent by text or messaging app,",
    "or taken on another device, are not accepted from the technician.",
    "• Installer site survey photographs are accepted only on the engineer's decision at intake, and",
    "are held in the job file as received.",
    "• An observation that cannot be made is recorded as not observed with the reason.",
    "• A package that does not cover every checklist item for every plane the array will occupy is",
    "rejected without review.",
    "Engineer review",
    "• The engineer reviews the evidence package first. A package that is not complete is returned",
    "as revise or site revisit before any calculation.",
    "• The engineer then calculates the existing roof structure under the proposed array, to the",
    "adopted code: gravity load on the framing, including the load at each attachment. Wind uplift is",
    "not calculated, and the letter says so.",
    "• The engineer records one of the five determinations in Appendix C: pass, revise, repairs",
    "required, site revisit, or decline.",
    "• The engineer's review record identifies the checklist items and photographs relied on, the array",
    "design by its date and revision, and the calculation. The calculation is kept in the job file. It is",
    "issued with the letter only where the permitting authority asks for it.",
    "10. Deficiencies and repairs",
    "• On a repairs required determination, the engineer issues a written list identifying each item,",
    "what governs it, and what is required to close it.",
    "• Where the array must change, the list goes to the customer for the installer. When a revised",
    "array design is received, the engineer recalculates. No site revisit is needed.",
    "• Where the structure must be repaired or strengthened, the list says so. The strengthening",
    "design is a separate engagement. Completed work is verified on a site revisit to the same",
    "evidence standard.",
    "• Repairs are performed by others. 254 Engineering Services does not perform, supervise, or",
    "recommend a contractor for the work.",
    "• On a repairs required determination, the engineer also issues a sealed letter stating that the",
    "existing roof structure is not adequate for the array as described, with the list. No letter stating",
    "adequacy is issued with an open item. There is no conditional letter.",
    "11. Structural letter",
    "• On a pass determination, the engineer issues a sealed letter addressed to the recipient",
    "recorded at intake, for the purpose recorded at intake.",
    "• On a repairs required determination, the engineer issues a sealed letter to the same recipient",
    "stating that the existing roof structure is not adequate to support the array as described, with",
    "the list.",
    "• The letter states the date the site evidence was collected. It does not name the person who",
    "collected it.",
    "• The letter identifies the property, the date of inspection or of the installer's survey, the existing",
    "roof framing as observed, the adopted code and the loads used, and the array design by its",
    "date and revision: module, module count, racking, attachment type, attachment spacing, and",
    "layout.",
    "• The letter states the engineer's opinion that the existing roof structure is adequate to support",
    "the array as described.",
    "• The letter states that it is void if the modules, racking, attachment pattern, or layout change",
    "from the array design it names.",
    "• The letter states that it does not cover the design of the modules, racking, or attachment",
    "hardware, the waterproofing of penetrations, the electrical work, the condition of the roof",
    "covering, or wind uplift on the array or on the framing.",
    "• The letter reflects condition on the date of inspection only and does not forecast future",
    "performance.",
    "• The engineer does not issue a letter on evidence that was not reviewed under this protocol.",
    "12. Exclusions",
    "The following are declined or routed to another service line under its own engagement terms. The",
    "coordinator records the routing in the job file and informs the customer in writing.",
    "• No array design. No letter is issued until one is supplied.",
    "• Roof framing that cannot be seen from an attic or from below. Declined. The firm does not",
    "issue a solar letter from drawings alone.",
    "• A ground-mounted array, carport, or canopy. Routed to the design line.",
    "• A roof that needs strengthening design. Routed to the design line after the repairs required list",
    "is issued.",
    "• An open insurance claim or litigation involving the roof structure. Declined, with a referral to an",
    "independent firm.",
    "• A customer request for a predetermined conclusion. This is an automatic decline and the",
    "request is logged verbatim.",
    "13. Records and retention",
    "• Each job file contains: the intake record and customer uploads, every revision of the array",
    "design received, the engineer's acceptance record, the dispatch record, the completed",
    "Appendix B checklist, all photographs, the technician's notes, the engineer's calculation,",
    "review record and determination, any repairs required list and its closure records, and the",
    "issued letter.",
    "• Job files are retained for ten years from the date of the letter. For a job that produces no letter,",
    "the ten years runs from the date of the engineer's last recorded determination or closure.",
    "• Ten years is the firm's floor, reviewed against TBPELS rules.",
    "• The compliance file holds the engineer's license records, technician qualification and training",
    "records, and every issued version of this protocol.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the",
    "adopted code or to the firm's field application.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table.",
    "• This document follows the firm's house protocol format. The portal's four parts are carried in",
    "Appendices A through C. Appendix A carries both the intake questions and the customer",
    "uploads. Appendix D is the reference list.",
    "Appendix A. Intake questions and customer uploads",
    "Asked and collected by the coordinator before the job is created. A job is not dispatched until every",
    "required item is present.",
    "PART 1: INTAKE QUESTIONS",
    "Purpose & recipient",
    "1. What is the letter for? (permit / installer / lender / other, record exactly)",
    "Answer: ____________________________________________________",
    "2. Who will the letter be addressed to?",
    "Answer: ____________________________________________________",
    "3. Which city or county issues the permit, and which code edition does it enforce?",
    "Answer: ____________________________________________________",
    "4. What deadline is the customer working against, if any?",
    "Answer: ____________________________________________________",
    "Property basics",
    "5. Property address and county",
    "Answer: ____________________________________________________",
    "6. Property type (single family / duplex / townhome / small commercial) and number of stories",
    "Answer: ____________________________________________________",
    "7. Year built",
    "Answer: ____________________________________________________",
    "8. Roof framing, if known (rafters / trusses / other)",
    "Answer: ____________________________________________________",
    "9. Roof covering type",
    "Answer: ____________________________________________________",
    "Proposed array",
    "10. Installer name, contact, and the installer's engineer if there is one",
    "Answer: ____________________________________________________",
    "11. Module make and model, number of modules, and weight of each",
    "Answer: ____________________________________________________",
    "12. Racking make and model, attachment type, and attachment spacing",
    "Answer: ____________________________________________________",
    "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
    "13. Is there already solar or other equipment on the roof planes the array will use?",
    "Yes No If yes, describe: ____________________________________________________",
    "14. Has the roof framing been cut, altered, or repaired, or is any sag or damage known?",
    "Yes No If yes, describe: ____________________________________________________",
    "15. Is there more than one layer of roof covering?",
    "Yes No If yes, describe: ____________________________________________________",
    "16. Is the roof framed with something other than wood? (steel, concrete)",
    "Yes No If yes, describe: ____________________________________________________",
    "17. Is the roof flat or low-slope?",
    "Yes No If yes, describe: ____________________________________________________",
    "18. Is there no attic or other way to see the roof framing?",
    "Yes No If yes, describe: ____________________________________________________",
    "19. Is there an open insurance claim or litigation involving the roof?",
    "Yes No If yes, describe: ____________________________________________________",
    "20. Has another engineer already declined to issue a letter for this roof?",
    "Yes No If yes, describe: ____________________________________________________",
    "Access & safety (decides dispatch feasibility)",
    "21. Where is the attic access, and is the attic clear enough to move through?",
    "Answer: ____________________________________________________",
    "22. Occupied or vacant? Accessible if occupied?",
    "Answer: ____________________________________________________",
    "Prior paperwork prompt",
    "23. Do you have: house plans, truss drawings, an earlier engineer letter, the permit application, the",
    "installer's site survey?",
    "Answer: ____________________________________________________",
    "PART 2: CUSTOMER UPLOADS (collected at intake, before dispatch)",
    "Required",
    "-- Photo of the front of the property (confirms address/structure)",
    "Required before the engineer calculates",
    "-- Array layout showing the module locations on each roof plane, with its date",
    "-- Module and racking data sheets",
    "-- Attachment type and spacing, from the installer",
    "Required if it exists",
    "-- House plans or truss drawings",
    "-- Any earlier engineer letter on this roof",
    "Collect when applicable",
    "-- Permit application and any comment from the permitting authority",
    "-- Installer's site survey photos (required where the engineer accepts them in place of a visit)",
    "-- Data for existing rooftop equipment on the same planes",
    "Appendix B. Technician on-site checklist",
    "Completed on site by the technician. The checklist cannot be submitted incomplete. Complete the",
    "framing and condition sections once for each roof plane the array will occupy, or for every roof plane",
    "where no array layout has been received.",
    "PHOTOS",
    "-- Before starting, make a rough sketch of the roof, mark the planes the array will occupy, and mark",
    "North. Take a photo of it.",
    "-- Tick the item you are about to photograph, take a photo of the checklist, then take the photos for",
    "that item.",
    "-- Move on to the next item the same way.",
    "JOB INFORMATION",
    "Job / Dispatch No.: ____________________________",
    "Property address (full, incl. county):",
    "__________________________________________________________",
    "Technician name: ______________________________________",
    "Date / arrival time / departure time: ________________________________________",
    "Weather during visit: ________________________________________",
    "Contact on site (name, role, phone): ________________________________________________",
    "[ ] Photo of address marker (house number, street sign, or mailbox) [PHOTO]",
    "CONTEXT (every job)",
    "[ ] All four elevations of the structure [PHOTO]",
    "[ ] Each roof plane the array will occupy, from the ground or the roof [PHOTO]",
    "[ ] Roof covering at an edge, showing type and number of layers [PHOTO]",
    "[ ] Everything already on those planes: vents, equipment, existing solar [PHOTO]",
    "Roof pitch, measured, each plane: __________________________________",
    "Covering type ________________ layers ____ outside width of building under each plane (ft):",
    "________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "FRAMING (each plane)",
    "[ ] Framing overall from the attic access [PHOTO]",
    "[ ] Framing type (rafter / truss / other) [PHOTO]",
    "[ ] Member depth and width, tape in frame [PHOTO]",
    "[ ] Spacing center to center, measured at three places, tape in frame [PHOTO]",
    "[ ] Span: tape from one support to the next, both ends in the photos [PHOTO]",
    "[ ] What supports the member at each end and in between (wall, ridge, purlin, brace, knee wall)",
    "[PHOTO]",
    "[ ] Lumber grade stamp, if one can be found [PHOTO]",
    "[ ] Trusses: tag or stamp, web pattern from the side, and one metal plate close up [PHOTO]",
    "[ ] Ridge board or beam, collar ties, and ceiling joists: size and spacing [PHOTO]",
    "[ ] Roof sheathing type and thickness, from a stamp or an exposed edge [PHOTO]",
    "Member size, measured (in.): ________ x ________ spacing (in.): ____ ____ ____",
    "Span (ft-in.): ________ sheathing: ________________ supports: ________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CONDITION (each plane)",
    "[ ] Sight line along the ridge and down the plane, showing any sag [PHOTO]",
    "[ ] Every split, crack, notch, or cut member [PHOTO]",
    "[ ] Every truss member that has been cut, removed, or altered [PHOTO]",
    "[ ] Every earlier repair or added member [PHOTO]",
    "[ ] Every water stain, rot, or insect damage on the framing or sheathing [PHOTO]",
    "Damaged or altered members ____ earlier repairs ____ stains ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CLOSE-OUT",
    "[ ] Full perimeter walk: anything unusual [PHOTO]",
    "[ ] Exception menu cleared for every non-applicable item",
    "Total photos: ______________",
    "Technician signature / date: ____________________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Appendix C. Engineer decision rules",
    "Applied by the engineer to each evidence package and calculation. One determination is recorded",
    "per review.",
    "PASS",
    "-- Package complete: every checklist item present or properly excepted for every plane the array will",
    "occupy",
    "-- Array design complete: module, count, weight, racking, attachment type, spacing, and layout",
    "-- Calculated gravity load on every framing member checked is within its capacity under the adopted",
    "code, with the array in place",
    "-- No damaged, cut, or altered member under the array",
    "REVISE",
    "-- Any required photo missing, blurry, or missing its tape",
    "-- Member size recorded as a nominal size, or spacing measured at fewer than three places",
    "-- Span photo does not show both supports",
    "-- A plane the array will occupy has no framing record",
    "-- Array design missing an item needed to calculate",
    "-- Counts or measurements inconsistent with photos",
    "REPAIRS REQUIRED (sealed letter states not adequate, list issued)",
    "-- Array change required: calculated gravity load is over capacity and a change in module count,",
    "layout, or attachment spacing would bring it within",
    "-- Strengthening required: calculated gravity load is over capacity and no array change would bring it",
    "within",
    "-- A damaged, cut, or altered member under the array",
    "-- Active leak or rot in the framing or sheathing under the array",
    "-- A letter stating adequacy proceeds only after a revised array design is recalculated, or repairs are",
    "verified on revisit",
    "SITE REVISIT (technician returns with an engineer-specified capture list)",
    "-- A support that could not be seen governs the result, return to find and measure it",
    "-- Framing differs from one part of a plane to another and only one was captured, return for the rest",
    "-- Array layout changed to a plane that was not captured, return for that plane",
    "-- Conflicting evidence (plans vs. photos vs. measurements), return for the specific items that settle it",
    "-- Repairs required, return after repairs to verify each item on the list",
    "DECLINE",
    "-- Roof framing cannot be seen",
    "-- Ground-mounted array, carport, or canopy, route to design line",
    "-- Open insurance claim or litigation, decline, with a referral to an independent firm",
    "-- Customer requests a predetermined conclusion, automatic decline, log verbatim request",
    "Appendix D. References",
    "Item Location",
    "International Residential",
    "Code, Section R324, Solar",
    "Energy Systems",
    "As adopted by the authority having jurisdiction",
    "International Building",
    "Code, Chapter 16,",
    "Structural Design",
    "As adopted by the authority having jurisdiction",
    "International Existing",
    "Building Code",
    "As adopted by the authority having jurisdiction",
    "ASCE 7, Minimum Design",
    "Loads and Associated",
    "Criteria for Buildings and",
    "Other Structures",
    "Edition referenced by the adopted code",
    "National Design",
    "Specification for Wood",
    "Construction, American",
    "Wood Council",
    "Edition referenced by the adopted code",
    "Racking manufacturer's Supplied with the array design",
    "installation manual and",
    "engineering",
    "Texas Engineering Practice",
    "Act, Texas Occupations",
    "Code Chapter 1001",
    "statutes.capitol.texas.gov",
    "TBPELS rules, 22 TAC",
    "Chapter 137",
    "pels.texas.gov",
    "254-RC-001 Roof",
    "Certification Protocol, v1.1,",
    "issued September 18, 2026",
    "Firm document",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const SL001_COUNTS = [
  {
    "key": "field-1",
    "prompt": "Job / Dispatch No.: ____________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-2",
    "prompt": "Property address (full, incl. county):",
    "at": "Appendix B"
  },
  {
    "key": "field-3",
    "prompt": "Technician name: ______________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-4",
    "prompt": "Date / arrival time / departure time: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-5",
    "prompt": "Weather during visit: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-6",
    "prompt": "Contact on site (name, role, phone): ________________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-7",
    "prompt": "Roof pitch, measured, each plane: __________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-8",
    "prompt": "Covering type ________________ layers ____ outside width of building under each plane (ft):",
    "at": "Appendix B"
  },
  {
    "key": "field-9",
    "prompt": "Member size, measured (in.): ________ x ________ spacing (in.): ____ ____ ____",
    "at": "Appendix B"
  },
  {
    "key": "field-10",
    "prompt": "Span (ft-in.): ________ sheathing: ________________ supports: ________________",
    "at": "Appendix B"
  },
  {
    "key": "field-11",
    "prompt": "Damaged or altered members ____ earlier repairs ____ stains ____",
    "at": "Appendix B"
  },
  {
    "key": "field-12",
    "prompt": "Total photos: ______________",
    "at": "Appendix B"
  },
  {
    "key": "field-13",
    "prompt": "Technician signature / date: ____________________________________________",
    "at": "Appendix B"
  }
];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const SL001_OTHER_RULES = [];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const SL001_BLANK_JOB_LIST_ITEMS = 0;
