/**
 * 254-WP-001 v1.1, Windstorm Inspection Protocol for Certificates of Compliance (Form WPI-8), Ongoing Construction.
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-WP-001_Windstorm_Inspection_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 e7515b42a3d319483c40dc2ded4d07527f8ada932410d64ad69ec9c45ccb3040. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const WP001 = {
  "documentNumber": "254-WP-001",
  "title": "Windstorm Inspection Protocol for Certificates of Compliance (Form WPI-8), Ongoing Construction",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Robert Reyna, Principal, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record and Appointed Qualified Inspector. The engineer may amend this protocol at any time by issuing a revised version.",
  "appliesTo": "All windstorm inspection engagements performed by 254 Engineering Services in the TDI Designated Catastrophe Areas",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "windstorm-wpi-8",
  "serviceTier": "ongoing",
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-WP-001_Windstorm_Inspection_Protocol_v1_1.pdf",
  "sourceSha256": "e7515b42a3d319483c40dc2ded4d07527f8ada932410d64ad69ec9c45ccb3040",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "stage-1",
      "heading": "Stage 1. Foundation and anchorage",
      "at": "Appendix A"
    },
    {
      "key": "stage-2",
      "heading": "Stage 2. Wall framing and shear",
      "at": "Appendix A"
    },
    {
      "key": "stage-3",
      "heading": "Stage 3. Roof framing and connections",
      "at": "Appendix A"
    },
    {
      "key": "stage-4",
      "heading": "Stage 4. Roof deck",
      "at": "Appendix A"
    },
    {
      "key": "stage-5",
      "heading": "Stage 5. Roof covering",
      "at": "Appendix A"
    },
    {
      "key": "stage-6",
      "heading": "Stage 6. Openings and windborne debris protection",
      "at": "Appendix A"
    },
    {
      "key": "stage-7",
      "heading": "Stage 7. Exterior covering",
      "at": "Appendix A"
    },
    {
      "key": "stage-8",
      "heading": "Stage 8. Mechanical equipment",
      "at": "Appendix A"
    },
    {
      "key": "stage-9",
      "heading": "Stage 9. Final",
      "at": "Appendix A"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the structure and mark North. Take a photo of it.",
      "at": "Appendix A"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix A"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix A"
    }
  ],
  "intakeQuestions": [],
  "intakeUploads": [],
  "checklist": [
    {
      "key": "stage-1-anchor-bolts",
      "section": "stage-1",
      "label": "Anchor bolts",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-1-anchor-bolts-record",
        "prompt": "Diameter, embedment, spacing, distance from plate ends and corners, plate washer size and type, nut engagement. Measure at every corner and at three intermediate locations per wall line.",
        "kind": "text"
      },
      "reference": "IRC R403.1.6; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-1-alternative-anchorage",
      "section": "stage-1",
      "label": "Alternative anchorage",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-1-alternative-anchorage-record",
        "prompt": "Strap or cast-in anchor product, manufacturer, model, spacing, embedment, and nailing to plate.",
        "kind": "text"
      },
      "reference": "Manufacturer evaluation; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-1-hold-downs",
      "section": "stage-1",
      "label": "Hold-downs",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-1-hold-downs-record",
        "prompt": "Location against the construction documents, product and model, anchor rod diameter and embedment, post size.",
        "kind": "text"
      },
      "reference": "IRC R602.10; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-1-sill-plate",
      "section": "stage-1",
      "label": "Sill plate",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-1-sill-plate-record",
        "prompt": "Species, grade stamp, preservative treatment where in contact with concrete or masonry, sill sealer.",
        "kind": "text"
      },
      "reference": "IRC R317, R403.1.6",
      "at": "Appendix A"
    },
    {
      "key": "stage-1-foundation-condition",
      "section": "stage-1",
      "label": "Foundation condition",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-1-foundation-condition-record",
        "prompt": "Cracking, honeycombing, or damage at anchorage locations. Pier and beam: pier connections and post bases.",
        "kind": "text"
      },
      "reference": "Construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-studs-and-plates",
      "section": "stage-2",
      "label": "Studs and plates",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-studs-and-plates-record",
        "prompt": "Size, spacing, species and grade stamps, top plate lap length and nailing, bottom plate nailing.",
        "kind": "text"
      },
      "reference": "IRC R602.3, Table R602.3(1)",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-headers",
      "section": "stage-2",
      "label": "Headers",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-headers-record",
        "prompt": "Size and span against construction documents, bearing, jack stud count.",
        "kind": "text"
      },
      "reference": "IRC R602.7; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-wall-sheathing",
      "section": "stage-2",
      "label": "Wall sheathing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-wall-sheathing-record",
        "prompt": "Panel type, thickness, span rating and grade stamp, panel edge blocking where required.",
        "kind": "text"
      },
      "reference": "IRC R602.3, R602.10",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-sheathing-fastening",
      "section": "stage-2",
      "label": "Sheathing fastening",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-sheathing-fastening-record",
        "prompt": "Nail type, size, and spacing at panel edges and in the field. Measure three edge and three field locations per elevation; record overdriven or missed nails.",
        "kind": "text"
      },
      "reference": "IRC Table R602.3(1); construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-wall-bracing-and-shear-walls",
      "section": "stage-2",
      "label": "Wall bracing and shear walls",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-wall-bracing-and-shear-walls-record",
        "prompt": "Braced wall panel locations, lengths, and method against the construction documents; shear wall nailing where designed.",
        "kind": "text"
      },
      "reference": "IRC R602.10; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-load-path-hardware",
      "section": "stage-2",
      "label": "Load path hardware",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-load-path-hardware-record",
        "prompt": "Straps, ties, and hold-downs from foundation through each floor to roof: product, model, location, and nailing complete.",
        "kind": "text"
      },
      "reference": "IRC R602.3.5, R602.10; manufacturer evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-2-openings-framing",
      "section": "stage-2",
      "label": "Openings framing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-2-openings-framing-record",
        "prompt": "Rough opening framing and king and jack studs at each opening; strapping at large openings where designed.",
        "kind": "text"
      },
      "reference": "Construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-rafters-or-trusses",
      "section": "stage-3",
      "label": "Rafters or trusses",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-rafters-or-trusses-record",
        "prompt": "Size, spacing, span, species and grade stamps; truss manufacturer, truss identification, and truss design drawings on site.",
        "kind": "text"
      },
      "reference": "IRC R802; truss design drawings",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-uplift-connections",
      "section": "stage-3",
      "label": "Uplift connections",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-uplift-connections-record",
        "prompt": "Rafter or truss to top plate connector product, model, location at every bearing point, and nailing complete. Photograph a representative run on each bearing wall and every connector at corners and gable ends.",
        "kind": "text"
      },
      "reference": "IRC R802.11; manufacturer evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-ridge-hip-valley",
      "section": "stage-3",
      "label": "Ridge, hip, valley",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-ridge-hip-valley-record",
        "prompt": "Member size, bearing, and connection.",
        "kind": "text"
      },
      "reference": "IRC R802",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-gable-end-bracing",
      "section": "stage-3",
      "label": "Gable end bracing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-gable-end-bracing-record",
        "prompt": "Gable end wall framing, bracing to roof framing, and connection to the wall below.",
        "kind": "text"
      },
      "reference": "IRC R802.10, R602.10; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-truss-bracing",
      "section": "stage-3",
      "label": "Truss bracing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-truss-bracing-record",
        "prompt": "Permanent bracing installed as the truss design drawings and bracing plan require.",
        "kind": "text"
      },
      "reference": "Truss design drawings",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-collar-ties-and-purlins",
      "section": "stage-3",
      "label": "Collar ties and purlins",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-collar-ties-and-purlins-record",
        "prompt": "Where used, size, spacing, and connection.",
        "kind": "text"
      },
      "reference": "IRC R802",
      "at": "Appendix A"
    },
    {
      "key": "stage-3-porches-carports-and-patio-covers",
      "section": "stage-3",
      "label": "Porches, carports, and patio covers",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-3-porches-carports-and-patio-covers-record",
        "prompt": "Post size, connection at the top and at the bottom of every post, beam size and connection, and uplift connectors.",
        "kind": "text"
      },
      "reference": "Construction documents; manufacturer evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-4-sheathing",
      "section": "stage-4",
      "label": "Sheathing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-4-sheathing-record",
        "prompt": "Panel type, thickness, span rating and grade stamp, panel orientation, H-clips or blocking where required.",
        "kind": "text"
      },
      "reference": "IRC R803.2; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-4-fastening",
      "section": "stage-4",
      "label": "Fastening",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-4-fastening-record",
        "prompt": "Nail type (ring shank where required), size, spacing at panel edges and in the field, and enhanced spacing at eaves, ridges, and gable ends where required. Measure three edge and three field locations per roof plane, plus one location at each eave and gable end.",
        "kind": "text"
      },
      "reference": "IRC R803.2.3, Table R602.3(1); construction documents; TDI amendments",
      "at": "Appendix A"
    },
    {
      "key": "stage-4-deck-condition",
      "section": "stage-4",
      "label": "Deck condition",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-4-deck-condition-record",
        "prompt": "Overdriven or missed nails, panel damage, gaps, unsupported edges.",
        "kind": "text"
      },
      "reference": "IRC R803",
      "at": "Appendix A"
    },
    {
      "key": "stage-4-drone-stills",
      "section": "stage-4",
      "label": "Drone stills",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-4-drone-stills-record",
        "prompt": "Every roof plane; low-altitude pass along each eave and gable.",
        "kind": "text"
      },
      "reference": "Section 9",
      "at": "Appendix A"
    },
    {
      "key": "stage-5-underlayment",
      "section": "stage-5",
      "label": "Underlayment",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-5-underlayment-record",
        "prompt": "Product, TDI evaluation or code compliance, lap and fastening, self-adhering membrane at eaves, valleys, and penetrations where required.",
        "kind": "text"
      },
      "reference": "IRC R905.1.1, R905.2.7; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-5-roof-covering-product",
      "section": "stage-5",
      "label": "Roof covering product",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-5-roof-covering-product-record",
        "prompt": "Manufacturer, product, wind rating, and TDI product evaluation report number; bundle wrapper or panel label photographed.",
        "kind": "text"
      },
      "reference": "IRC R905; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-5-fastening",
      "section": "stage-5",
      "label": "Fastening",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-5-fastening-record",
        "prompt": "Fastener type, size, count per shingle or panel, and placement per the evaluation report and the adopted code high-wind provisions. Photograph exposed fastening on each roof plane before it is covered by the next course.",
        "kind": "text"
      },
      "reference": "IRC R905.2.5, R905.2.6; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-5-starter-ridge-hip-edge",
      "section": "stage-5",
      "label": "Starter, ridge, hip, edge",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-5-starter-ridge-hip-edge-record",
        "prompt": "Starter strip product and fastening, ridge and hip cap product and fastening, drip edge and its fastening, rake and eave details.",
        "kind": "text"
      },
      "reference": "IRC R905.2.8; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-5-flashing",
      "section": "stage-5",
      "label": "Flashing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-5-flashing-record",
        "prompt": "Step, headwall, valley, and penetration flashing installed and sealed.",
        "kind": "text"
      },
      "reference": "IRC R903.2, R905.2.8",
      "at": "Appendix A"
    },
    {
      "key": "stage-5-drone-stills",
      "section": "stage-5",
      "label": "Drone stills",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-5-drone-stills-record",
        "prompt": "Every roof plane; low-altitude pass along each eave and gable.",
        "kind": "text"
      },
      "reference": "Section 9",
      "at": "Appendix A"
    },
    {
      "key": "stage-6-windows-and-skylights",
      "section": "stage-6",
      "label": "Windows and skylights",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-6-windows-and-skylights-record",
        "prompt": "Manufacturer, product, design pressure rating against the required pressure for the opening, TDI product evaluation report number, label photographed.",
        "kind": "text"
      },
      "reference": "IRC R301.2.1, R609; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-6-doors-and-garage-doors",
      "section": "stage-6",
      "label": "Doors and garage doors",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-6-doors-and-garage-doors-record",
        "prompt": "Same as windows; garage door wind rating and reinforcement per the evaluation.",
        "kind": "text"
      },
      "reference": "IRC R609; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-6-installation",
      "section": "stage-6",
      "label": "Installation",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-6-installation-record",
        "prompt": "Fastener type, size, spacing, and location per the evaluation report and manufacturer installation instructions; shimming; flashing integration.",
        "kind": "text"
      },
      "reference": "TDI product evaluation; manufacturer instructions",
      "at": "Appendix A"
    },
    {
      "key": "stage-6-windborne-debris-protection",
      "section": "stage-6",
      "label": "Windborne debris protection",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-6-windborne-debris-protection-record",
        "prompt": "Where the site is in the windborne debris region: impact-rated glazing labels, or shutters or wood structural panels with thickness, span, and attachment hardware present for every opening.",
        "kind": "text"
      },
      "reference": "IRC R301.2.1.2; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-7-covering-product",
      "section": "stage-7",
      "label": "Covering product",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-7-covering-product-record",
        "prompt": "Siding, panel, stucco, or masonry veneer product and TDI product evaluation report number where applicable.",
        "kind": "text"
      },
      "reference": "IRC R703; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-7-attachment",
      "section": "stage-7",
      "label": "Attachment",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-7-attachment-record",
        "prompt": "Fastener type, size, and spacing; brick tie spacing; lath attachment; measured at three locations per elevation.",
        "kind": "text"
      },
      "reference": "IRC R703; TDI product evaluation; manufacturer instructions",
      "at": "Appendix A"
    },
    {
      "key": "stage-7-soffit-and-trim",
      "section": "stage-7",
      "label": "Soffit and trim",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-7-soffit-and-trim-record",
        "prompt": "Soffit product and attachment; trim attachment at rakes and eaves.",
        "kind": "text"
      },
      "reference": "IRC R703; TDI product evaluation",
      "at": "Appendix A"
    },
    {
      "key": "stage-8-exterior-equipment",
      "section": "stage-8",
      "label": "Exterior equipment",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-8-exterior-equipment-record",
        "prompt": "Every condenser, heat pump, generator, and other exterior unit: location, manufacturer, model, and labeled weight.",
        "kind": "text"
      },
      "reference": "Construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-8-anchorage",
      "section": "stage-8",
      "label": "Anchorage",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-8-anchorage-record",
        "prompt": "Tie-down or anchor product, count, size, and attachment to the pad, stand, or structure, for every unit. Photograph each side of each unit.",
        "kind": "text"
      },
      "reference": "Adopted code; manufacturer instructions; construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-8-pad-or-stand",
      "section": "stage-8",
      "label": "Pad or stand",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-8-pad-or-stand-record",
        "prompt": "Pad size and condition. Stand or platform framing and its connection to the structure where the unit is elevated.",
        "kind": "text"
      },
      "reference": "Construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-8-roof-mounted-equipment",
      "section": "stage-8",
      "label": "Roof-mounted equipment",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-8-roof-mounted-equipment-record",
        "prompt": "Curb or stand and its attachment to the roof framing, where present.",
        "kind": "text"
      },
      "reference": "Construction documents",
      "at": "Appendix A"
    },
    {
      "key": "stage-9-stage-closure",
      "section": "stage-9",
      "label": "Stage closure",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-9-stage-closure-record",
        "prompt": "Every prior stage shows a closed determination in the file.",
        "kind": "text"
      },
      "reference": "Section 9",
      "at": "Appendix A"
    },
    {
      "key": "stage-9-deficiencies",
      "section": "stage-9",
      "label": "Deficiencies",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-9-deficiencies-record",
        "prompt": "Every deficiency shows a closure with re-inspection evidence.",
        "kind": "text"
      },
      "reference": "Section 10",
      "at": "Appendix A"
    },
    {
      "key": "stage-9-scope-match",
      "section": "stage-9",
      "label": "Scope match",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-9-scope-match-record",
        "prompt": "Structure as built matches the WPI-1 description and the construction documents; any change recorded and accepted by the engineer.",
        "kind": "text"
      },
      "reference": "Section 6",
      "at": "Appendix A"
    },
    {
      "key": "stage-9-overall-photographs",
      "section": "stage-9",
      "label": "Overall photographs",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": {
        "key": "stage-9-overall-photographs-record",
        "prompt": "All elevations and all roof planes.",
        "kind": "text"
      },
      "reference": "Section 9",
      "at": "Appendix A"
    }
  ],
  "determinations": [],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Windstorm Inspection Protocol",
    "Document Value",
    "Title Windstorm Inspection Protocol for Certificates of Compliance (Form WPI-8),",
    "Ongoing Construction",
    "Document number 254-WP-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Robert Reyna, Principal, 254 Engineering Services",
    "Approval Aman Dhakal, P.E., Engineer of Record and Appointed Qualified Inspector.",
    "The engineer may amend this protocol at any time by issuing a revised",
    "version.",
    "Applies to All windstorm inspection engagements performed by 254 Engineering",
    "Services in the TDI Designated Catastrophe Areas",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services performs windstorm inspections of ongoing",
    "construction so that the Engineer of Record, as a Texas Department of Insurance appointed",
    "qualified inspector, can certify compliance on Form WPI-2 and the owner can obtain a Certificate of",
    "Compliance, Form WPI-8, from TDI. A WPI-8 is required for windstorm and hail coverage through",
    "the Texas Windstorm Insurance Association on structures in the Designated Catastrophe Areas.",
    "The engineer signs and seals the WPI-2 personally and TDI relies on that certification. Every",
    "requirement in this protocol exists so that the engineer can reconstruct and defend each certification",
    "from the job file alone.",
    "2. Scope",
    "This protocol applies to ongoing construction: new structures, additions, alterations, repairs, and re-",
    "roofs for which the first inspection occurs before the structure becomes a completed improvement as",
    "defined in Insurance Code Section 2210.251 and 28 TAC Chapter 5, Subchapter E. Completed",
    "improvements are outside this protocol; Section 12 governs how such requests are handled.",
    "This protocol does not cover structural design, plan review for permitting, or engineering letters",
    "unrelated to the windstorm program. Those are separate engagements with their own protocols.",
    "3. Governing requirements",
    "Authority Application",
    "Texas Insurance Code, Chapter",
    "2210, Subchapter F (Sections",
    "2210.251 through 2210.2581)",
    "Windstorm building standards, inspection requirements, appointed",
    "qualified inspectors, certificates of compliance for ongoing and completed",
    "improvements.",
    "Authority Application",
    "28 TAC Sections 5.4008",
    "through 5.4013",
    "Designated Catastrophe Areas and the applicable building code standards",
    "by construction start date.",
    "28 TAC Sections 5.4601",
    "through 5.4642",
    "Inspections for windstorm and hail insurance: definitions, adopted forms",
    "(Section 5.4603), inspection and certification procedures, and electronic",
    "submission through the TDI Windstorm system.",
    "2024 International Residential",
    "Code and 2024 International",
    "Building Code, as adopted by",
    "TDI",
    "Applicable to construction, repairs, and additions that begin on or after",
    "April 1, 2026, per the TDI adoption order published in the Texas Register",
    "(50 TexReg 7505) and the TDI Adopted Building Codes page.",
    "Construction that began September 1, 2020 through March 31, 2026 is",
    "certified to the 2018 IRC or 2018 IBC. The engineer determines the",
    "applicable edition from the construction start date recorded on the WPI-1.",
    "ASCE 7 as referenced by the",
    "adopted code",
    "Wind loads. Design wind speeds and the windborne debris region are",
    "determined using the TDI web-based wind speed tools referenced on the",
    "TDI Adopted Building Codes page and the code wind speed maps, not",
    "from assumed zone values.",
    "TDI Product Evaluations Roof coverings, exterior coverings, windows, doors, garage doors,",
    "shutters, and other evaluated components must be installed in",
    "accordance with the applicable TDI product evaluation report or an",
    "equivalent evaluation the engineer accepts under the adopted code.",
    "TDI Windstorm Inspection",
    "Program administrative",
    "requirements",
    "One WPI-1 and one WPI-2 per detached structure at an address. Forms",
    "submitted electronically through the TDI Windstorm system by the",
    "appointed inspector. TDI may require verification where there is a",
    "substantial gap between the commencement of construction and the first",
    "inspection.",
    "Texas Engineering Practice Act",
    "and TBPELS rules, 22 TAC",
    "Chapter 137",
    "Responsible charge, sealing, and professional conduct of the Engineer of",
    "Record.",
    "The engineer records the applicable code edition, the design wind speed, the exposure category,",
    "and whether the site is in the windborne debris region in the job file at intake. Inspections are",
    "conducted against the recorded criteria and the approved construction documents.",
    "4. Roles and responsibilities",
    "Role Responsibility Holder",
    "Engineer of Record",
    "(EOR)",
    "TDI appointed qualified inspector. Approves this protocol and every",
    "job-specific inspection plan. Determines applicable code and design",
    "criteria. Reviews every evidence package and issues every",
    "compliance determination. Issues deficiency notices. Signs, seals,",
    "and submits the WPI-2. Responds to TDI. May reject any package,",
    "order re-inspection, or decline any job.",
    "Aman",
    "Dhakal,",
    "P.E.",
    "Field Technician The engineer's designated representative under 28 TAC 5.4621.",
    "Collects evidence on site in accordance with the job inspection plan",
    "and Appendix A. Reports observations and flags concerns to the",
    "EOR. Makes no compliance determination and communicates none",
    "to any party. Signs nothing directed to TDI.",
    "Personn",
    "el",
    "qualified",
    "under",
    "Section 5",
    "Coordinator Intake, job file, scheduling, written communication with contractor and",
    "owner, evidence package assembly, data entry in the TDI Windstorm",
    "system under the EOR's direction, certificate delivery, invoicing, and",
    "Robert",
    "Reyna or",
    "delegate",
    "Role Responsibility Holder",
    "records.",
    "Only the Engineer of Record determines compliance. Field technicians and the coordinator relay the",
    "engineer's written determinations and nothing else. A technician who indicates on site that work is",
    "acceptable has exceeded this protocol, and the coordinator reports the occurrence to the engineer",
    "the same day.",
    "5. Personnel qualifications",
    "Field Technician",
    "• At least two years of documented residential or light commercial construction experience in",
    "framing, roofing, or building envelope work, or an engineering degree with EIT certification, or",
    "equivalent experience the engineer accepts in writing.",
    "• Completion of the engineer's training on this protocol, Appendix A, and the field application,",
    "with a supervised inspection on at least two stages before working alone.",
    "• For drone operation, a current FAA Part 107 Remote Pilot Certificate on file.",
    "• Demonstrated ability to read plans and locate items in the field against them.",
    "• Annual refresher training when the adopted code, TDI rules, or this protocol change.",
    "Engineer of Record",
    "• Active Texas P.E. license and active TDI appointment as a qualified inspector. Copies of both,",
    "with expiration dates, are kept in the firm's compliance file and checked monthly by the",
    "coordinator.",
    "6. Intake and the WPI-1",
    "1. The coordinator opens a job file for each detached structure. The file records the owner,",
    "contractor, site address, county, structure type and occupancy, scope of work, construction",
    "documents received, construction start date, and the expected construction sequence.",
    "2. The engineer reviews the intake and records in the file: accept, accept with conditions, or",
    "decline. A structure that has already passed a stage that must be inspected is declined for the",
    "ongoing path and handled under Section 12.",
    "3. The engineer records the design criteria for the job: applicable code edition by construction",
    "start date, design wind speed and exposure from the TDI tools and code maps, windborne",
    "debris region status, and any Texas or TDI amendments that apply.",
    "4. The engineer reviews the design documents for the job as 28 TAC 5.4623 requires, including",
    "the design criteria, wind loads, plans, and building product specifications, before the first",
    "inspection.",
    "5. Form WPI-1, Application for Windstorm Building Inspection, is submitted to TDI before",
    "construction begins or as soon as possible after, naming the Engineer of Record as the",
    "appointed inspector. The firm files it through the engineer's TDI Windstorm system login. The",
    "engineer confirms it is on file in the TDI Windstorm system before the first inspection and",
    "records the application identifier in the job file.",
    "6. The engineer issues a job inspection plan listing the required stages for the scope, drawn from",
    "Section 8 and Appendix A, and the coordinator delivers it to the contractor in writing with the",
    "notice requirements of Section 7.",
    "7. The coordinator records the construction start date and the first inspection date. Where the",
    "interval between them is more than thirty days, the engineer documents the reason in the file",
    "and addresses it in the WPI-2 remarks, since TDI may require verification of that interval",
    "before issuing the certificate.",
    "7. Scheduling and notice",
    "• The contractor must request each stage inspection before the work of that stage is covered.",
    "The coordinator confirms every inspection in writing to the contractor stating the stage, the",
    "date, and what must be complete, visible, and accessible.",
    "• The firm schedules a requested inspection within two business days of the request. The",
    "engineer may set a different interval for a specific job in the inspection plan.",
    "• Work covered before its stage inspection is not certified on the basis of the contractor's",
    "representation. The engineer determines whether the work can be exposed and inspected; if it",
    "cannot, the ongoing path for that structure is closed and the coordinator informs the owner and",
    "contractor in writing.",
    "• If site conditions prevent a complete inspection (access, safety, weather, work not ready), the",
    "technician records the condition, collects whatever evidence is available, and the coordinator",
    "reschedules. An incomplete stage is not closed.",
    "8. Inspection stages",
    "The engineer selects the stages for each job from the following list according to the scope and adds",
    "stages where the construction requires them. Each stage is inspected once the work of that stage is",
    "complete and before it is concealed. The detailed field checklist for each stage is Appendix A.",
    "Stage Purpose",
    "1. Foundation and",
    "anchorage",
    "Verify the connection of the structure to the foundation before framing conceals",
    "it.",
    "2. Wall framing and shear Verify wall framing, sheathing, fastening, bracing, and the continuous load path",
    "hardware before insulation or interior finish.",
    "3. Roof framing and",
    "connections",
    "Verify roof structure, uplift connections, and gable and truss bracing before roof",
    "deck fastening conceals connectors.",
    "4. Roof deck Verify roof sheathing and its fastening before underlayment is applied.",
    "5. Roof covering Verify underlayment, roof covering product, fastening, and edge and flashing",
    "details.",
    "6. Openings and",
    "windborne debris",
    "protection",
    "Verify window, door, garage door, and skylight products, ratings, and",
    "installation, and the presence and attachment of required opening protection.",
    "7. Exterior covering Verify exterior wall covering product and attachment.",
    "8. Mechanical equipment Verify the anchorage of exterior mechanical equipment to its pad, stand, or the",
    "structure.",
    "Stage Purpose",
    "9. Final Confirm all stages closed, all deficiencies corrected and re-inspected, and the",
    "structure consistent with the WPI-1 and the construction documents.",
    "For re-roof scope only, stages 4 and 5 apply, with stage 3 added where the engineer determines",
    "rafter connections are exposed or affected. For additions, every stage applies to the addition and to",
    "any existing construction the addition ties into where the adopted code requires it.",
    "One job includes four stage visits. The engineer groups the stages into those visits in the job",
    "inspection plan. Any further visit is made on an as-required basis as an additional visit.",
    "9. Evidence standard and engineer review",
    "Evidence package",
    "Each stage produces one evidence package in the firm's field application, consisting of the",
    "completed Appendix A checklist, photographs, measurements, and the technician's flagged",
    "concerns. Packages are locked on submission and cannot be edited afterward.",
    "• Every checklist item has at least one wide photograph placing the item in the structure and one",
    "close photograph showing the detail with a tape or scale in frame.",
    "• Fastener spacing is photographed with a tape along the panel edge and across the field at",
    "each location where the checklist requires a measurement. Fastener heads must be",
    "identifiable as to type, size, seating, and whether they struck framing.",
    "• Every connector, strap, anchor, and hold-down is photographed with fastening visible and",
    "manufacturer identification legible.",
    "• Every product subject to a TDI product evaluation is photographed with its label, stamp, or",
    "rating legible, and the evaluation report number is recorded on the checklist.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location. Photographs from other devices are not",
    "accepted.",
    "• Minimum photograph counts per stage are set in Appendix B. A package below the minimum",
    "is rejected without review.",
    "• Observations that cannot be made are recorded as not observed with the reason. No item is",
    "estimated, assumed, or left blank.",
    "• Drone imagery is taken at stages 4 and 5 where airspace rules and weather allow, and",
    "consists of stills of every roof plane and a low-altitude pass along each eave and gable. Where",
    "a drone cannot be flown, every roof plane, eave, and gable is photographed from the roof, a",
    "ladder, or the ground, and the reason is recorded. Drone imagery supplements and does not",
    "replace close photographs of fastening.",
    "Engineer review",
    "• The engineer reviews each package before the next stage is scheduled and records one of",
    "three determinations in the file with the date: stage closed, deficiency notice issued, or re-",
    "inspection ordered.",
    "• The engineer's review record identifies which checklist items and photographs the engineer",
    "relied on for the determination.",
    "• A package that does not allow the engineer to verify a required item is rejected and the stage",
    "is re-inspected. The technician's assessment is not a substitute for the evidence.",
    "Engineer supervision",
    "• The engineer does not attend the site. Evidence is collected by the field technician as the",
    "engineer's designated representative, under the engineer's direct supervision.",
    "• The engineer is available to the technician by phone or live video during an inspection when",
    "the technician needs a decision, and may direct additional observations.",
    "10. Deficiencies",
    "1. The engineer issues a written deficiency notice to the contractor and owner identifying each",
    "item, the governing requirement, the observation, the photographs, and the required",
    "correction.",
    "2. Corrections are re-inspected to the same evidence standard. The engineer reviews the re-",
    "inspection package and closes the deficiency in the file with the closing evidence and date.",
    "3. A deficiency concealed before re-inspection is treated as covered work under Section 7.",
    "4. No WPI-2 is submitted with an open deficiency. There is no conditional certification.",
    "11. Certification",
    "• After the final stage is closed, the engineer completes Form WPI-2, Inspection Verification,",
    "listing every inspection date, the applicable code edition, and the certification of compliance,",
    "then signs and seals it. The coordinator may enter the inspection data in the TDI Windstorm",
    "system; the engineer reviews the entry and submits the signed and sealed form as TDI",
    "requires.",
    "• TDI issues the WPI-8. The coordinator retrieves it from the Windstorm system, delivers it to the",
    "owner and contractor with the job file summary, and closes the file.",
    "• The engineer does not certify a structure that was not inspected stage by stage under this",
    "protocol by this firm. Requests to certify work inspected by another engineer or firm are",
    "declined.",
    "• If TDI requests verification or additional information, the engineer responds from the job file.",
    "The coordinator tracks the request and the response with dates.",
    "12. Completed improvements",
    "A structure is a completed improvement when title has transferred from the builder to the initial",
    "owner before the first inspection, or when the final framing stage, including attachment of component",
    "and cladding items and installation of windborne debris protection, was completed before the first",
    "inspection. TDI's published flowchart determines the path. Completed improvements obtain",
    "certification through TWIA (Form WPI-3 and Certificate WPI-8-C) or through TDI's post-construction",
    "process under Insurance Code Section 2210.2515 (Form WPI-2E and Certificate WPI-8E, supported",
    "by a sealed post-construction inspection report or sealed design).",
    "Completed improvements are certified under the firm's completed construction windstorm protocol,",
    "not this one. The coordinator opens each such request as a job on that line.",
    "13. Records and retention",
    "• Each job file contains: intake record and design criteria, WPI-1 confirmation and application",
    "identifier, job inspection plan, every evidence package, every engineer review record, every",
    "deficiency notice and closure, the submitted WPI-2, the issued WPI-8, and all correspondence",
    "with the owner, contractor, and TDI.",
    "• Job files are retained for ten years from the date of the WPI-8, or longer where required by",
    "TBPELS rules or a litigation hold. No record in a job file is altered or deleted.",
    "• The compliance file holds the engineer's license and appointment records, technician",
    "qualification records, training records, this protocol and every superseded version, and the",
    "annual protocol review record.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the",
    "adopted code, TDI rules, TDI forms, or the TDI product evaluation program. The coordinator",
    "monitors the TDI Windstorm Inspection Program page and newsletters monthly and forwards",
    "changes to the engineer.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table. Jobs in progress continue under the version",
    "in force at their WPI-1 date unless the engineer directs otherwise in writing.",
    "• This document is the template for every other inspection and certification protocol the firm",
    "issues. Each follows the same structure: governing requirements, roles, qualifications, intake,",
    "stages, evidence standard, engineer review, deficiencies, certification, records, and",
    "maintenance.",
    "Appendix A. Field checklist by stage",
    "The technician completes every item for the stage. Code references are to the 2024 IRC as adopted",
    "by TDI for construction beginning on or after April 1, 2026; the engineer records the corresponding",
    "2018 IRC or IBC references in the job inspection plan where an earlier edition or the IBC applies.",
    "Each item is verified against the approved construction documents and the recorded design criteria.",
    "• Before starting, make a rough sketch of the structure and mark North. Take a photo of it.",
    "• Tick the item you are about to photograph, take a photo of the checklist, then take the photos",
    "for that item.",
    "• Move on to the next item the same way.",
    "Stage 1. Foundation and anchorage",
    "Item Record Reference",
    "Anchor bolts Diameter, embedment, spacing, distance from plate",
    "ends and corners, plate washer size and type, nut",
    "engagement. Measure at every corner and at three",
    "intermediate locations per wall line.",
    "IRC R403.1.6;",
    "construction documents",
    "Alternative anchorage Strap or cast-in anchor product, manufacturer, model,",
    "spacing, embedment, and nailing to plate.",
    "Manufacturer evaluation;",
    "construction documents",
    "Hold-downs Location against the construction documents, product",
    "and model, anchor rod diameter and embedment, post",
    "size.",
    "IRC R602.10;",
    "construction documents",
    "Sill plate Species, grade stamp, preservative treatment where",
    "in contact with concrete or masonry, sill sealer.",
    "IRC R317, R403.1.6",
    "Foundation condition Cracking, honeycombing, or damage at anchorage",
    "locations. Pier and beam: pier connections and post",
    "bases.",
    "Construction documents",
    "Stage 2. Wall framing and shear",
    "Item Record Reference",
    "Studs and plates Size, spacing, species and grade stamps, top plate lap",
    "length and nailing, bottom plate nailing.",
    "IRC R602.3, Table",
    "R602.3(1)",
    "Headers Size and span against construction documents,",
    "bearing, jack stud count.",
    "IRC R602.7; construction",
    "documents",
    "Wall sheathing Panel type, thickness, span rating and grade stamp,",
    "panel edge blocking where required.",
    "IRC R602.3, R602.10",
    "Sheathing fastening Nail type, size, and spacing at panel edges and in the",
    "field. Measure three edge and three field locations per",
    "elevation; record overdriven or missed nails.",
    "IRC Table R602.3(1);",
    "construction documents",
    "Wall bracing and shear",
    "walls",
    "Braced wall panel locations, lengths, and method",
    "against the construction documents; shear wall nailing",
    "where designed.",
    "IRC R602.10;",
    "construction documents",
    "Load path hardware Straps, ties, and hold-downs from foundation through",
    "each floor to roof: product, model, location, and nailing",
    "complete.",
    "IRC R602.3.5, R602.10;",
    "manufacturer evaluation",
    "Openings framing Rough opening framing and king and jack studs at Construction documents",
    "Item Record Reference",
    "each opening; strapping at large openings where",
    "designed.",
    "Stage 3. Roof framing and connections",
    "Item Record Reference",
    "Rafters or trusses Size, spacing, span, species and grade stamps; truss",
    "manufacturer, truss identification, and truss design",
    "drawings on site.",
    "IRC R802; truss design",
    "drawings",
    "Uplift connections Rafter or truss to top plate connector product, model,",
    "location at every bearing point, and nailing complete.",
    "Photograph a representative run on each bearing wall",
    "and every connector at corners and gable ends.",
    "IRC R802.11;",
    "manufacturer evaluation",
    "Ridge, hip, valley Member size, bearing, and connection. IRC R802",
    "Gable end bracing Gable end wall framing, bracing to roof framing, and",
    "connection to the wall below.",
    "IRC R802.10, R602.10;",
    "construction documents",
    "Truss bracing Permanent bracing installed as the truss design",
    "drawings and bracing plan require.",
    "Truss design drawings",
    "Collar ties and purlins Where used, size, spacing, and connection. IRC R802",
    "Porches, carports, and",
    "patio covers",
    "Post size, connection at the top and at the bottom of",
    "every post, beam size and connection, and uplift",
    "connectors.",
    "Construction documents;",
    "manufacturer evaluation",
    "Stage 4. Roof deck",
    "Item Record Reference",
    "Sheathing Panel type, thickness, span rating and grade stamp,",
    "panel orientation, H-clips or blocking where required.",
    "IRC R803.2; construction",
    "documents",
    "Fastening Nail type (ring shank where required), size, spacing at",
    "panel edges and in the field, and enhanced spacing at",
    "eaves, ridges, and gable ends where required.",
    "Measure three edge and three field locations per roof",
    "plane, plus one location at each eave and gable end.",
    "IRC R803.2.3, Table",
    "R602.3(1); construction",
    "documents; TDI",
    "amendments",
    "Deck condition Overdriven or missed nails, panel damage, gaps,",
    "unsupported edges.",
    "IRC R803",
    "Drone stills Every roof plane; low-altitude pass along each eave",
    "and gable.",
    "Section 9",
    "Stage 5. Roof covering",
    "Item Record Reference",
    "Underlayment Product, TDI evaluation or code compliance, lap and",
    "fastening, self-adhering membrane at eaves, valleys,",
    "and penetrations where required.",
    "IRC R905.1.1, R905.2.7;",
    "TDI product evaluation",
    "Roof covering product Manufacturer, product, wind rating, and TDI product",
    "evaluation report number; bundle wrapper or panel",
    "label photographed.",
    "IRC R905; TDI product",
    "evaluation",
    "Fastening Fastener type, size, count per shingle or panel, and IRC R905.2.5, R905.2.6;",
    "Item Record Reference",
    "placement per the evaluation report and the adopted",
    "code high-wind provisions. Photograph exposed",
    "fastening on each roof plane before it is covered by",
    "the next course.",
    "TDI product evaluation",
    "Starter, ridge, hip, edge Starter strip product and fastening, ridge and hip cap",
    "product and fastening, drip edge and its fastening,",
    "rake and eave details.",
    "IRC R905.2.8; TDI",
    "product evaluation",
    "Flashing Step, headwall, valley, and penetration flashing",
    "installed and sealed.",
    "IRC R903.2, R905.2.8",
    "Drone stills Every roof plane; low-altitude pass along each eave",
    "and gable.",
    "Section 9",
    "Stage 6. Openings and windborne debris protection",
    "Item Record Reference",
    "Windows and skylights Manufacturer, product, design pressure rating against",
    "the required pressure for the opening, TDI product",
    "evaluation report number, label photographed.",
    "IRC R301.2.1, R609; TDI",
    "product evaluation",
    "Doors and garage",
    "doors",
    "Same as windows; garage door wind rating and",
    "reinforcement per the evaluation.",
    "IRC R609; TDI product",
    "evaluation",
    "Installation Fastener type, size, spacing, and location per the",
    "evaluation report and manufacturer installation",
    "instructions; shimming; flashing integration.",
    "TDI product evaluation;",
    "manufacturer instructions",
    "Windborne debris",
    "protection",
    "Where the site is in the windborne debris region:",
    "impact-rated glazing labels, or shutters or wood",
    "structural panels with thickness, span, and attachment",
    "hardware present for every opening.",
    "IRC R301.2.1.2; TDI",
    "product evaluation",
    "Stage 7. Exterior covering",
    "Item Record Reference",
    "Covering product Siding, panel, stucco, or masonry veneer product and",
    "TDI product evaluation report number where",
    "applicable.",
    "IRC R703; TDI product",
    "evaluation",
    "Attachment Fastener type, size, and spacing; brick tie spacing;",
    "lath attachment; measured at three locations per",
    "elevation.",
    "IRC R703; TDI product",
    "evaluation; manufacturer",
    "instructions",
    "Soffit and trim Soffit product and attachment; trim attachment at",
    "rakes and eaves.",
    "IRC R703; TDI product",
    "evaluation",
    "Stage 8. Mechanical equipment",
    "Item Record Reference",
    "Exterior equipment Every condenser, heat pump, generator, and other",
    "exterior unit: location, manufacturer, model, and",
    "labeled weight.",
    "Construction documents",
    "Anchorage Tie-down or anchor product, count, size, and",
    "attachment to the pad, stand, or structure, for every",
    "unit. Photograph each side of each unit.",
    "Adopted code;",
    "manufacturer",
    "instructions; construction",
    "Item Record Reference",
    "documents",
    "Pad or stand Pad size and condition. Stand or platform framing and",
    "its connection to the structure where the unit is",
    "elevated.",
    "Construction documents",
    "Roof-mounted",
    "equipment",
    "Curb or stand and its attachment to the roof framing,",
    "where present.",
    "Construction documents",
    "Stage 9. Final",
    "Item Record Reference",
    "Stage closure Every prior stage shows a closed determination in the",
    "file.",
    "Section 9",
    "Deficiencies Every deficiency shows a closure with re-inspection",
    "evidence.",
    "Section 10",
    "Scope match Structure as built matches the WPI-1 description and",
    "the construction documents; any change recorded and",
    "accepted by the engineer.",
    "Section 6",
    "Overall photographs All elevations and all roof planes. Section 9",
    "Appendix B. Minimum photograph counts",
    "Counts are per structure per stage and are minimums. The engineer may require more in the job",
    "inspection plan. Counts include wide and close photographs and exclude drone stills, which are",
    "additional.",
    "Stage Minimum Basis",
    "1. Foundation and anchorage 24 Two per corner, three intermediate per wall",
    "line on a four-wall plan, every hold-down, sill",
    "plate stamps",
    "2. Wall framing and shear 40 Six fastening measurements per elevation,",
    "every hold-down and strap, headers, bracing",
    "panels, grade stamps",
    "3. Roof framing and connections 40 Representative connector runs on every",
    "bearing wall, every corner and gable end",
    "connector, truss identification, bracing",
    "4. Roof deck 32 Eight fastening measurements per roof plane",
    "on a four-plane roof, grade stamps, deck",
    "condition",
    "5. Roof covering 32 Product labels, exposed fastening on each",
    "plane, starter, ridge, edge, and flashing details",
    "6. Openings and debris protection 4 per opening Label, installation fastening, flashing,",
    "protection panel or shutter",
    "7. Exterior covering 20 Product identification and three attachment",
    "measurements per elevation",
    "8. Mechanical equipment 4 per unit Unit label, anchorage on each side, pad or",
    "stand",
    "9. Final 12 All elevations and roof planes",
    "Where a structure has fewer or more elevations, roof planes, or openings than the basis assumes,",
    "the technician applies the per-element basis and records the resulting count in the package.",
    "Appendix C. Forms and references",
    "Item Location",
    "TDI Windstorm Inspection Program tdi.texas.gov/wind/index.html",
    "TDI Windstorm system (WPI-1, WPI-",
    "2, WPI-8 entry and retrieval)",
    "appscenter.tdi.texas.gov/windstorm/p/home",
    "TDI Adopted Building Codes and",
    "wind speed tools",
    "tdi.texas.gov/wind/adopted-codes.html",
    "TDI Building Codes and Downloads",
    "(Texas revisions and amendments)",
    "tdi.texas.gov/wind/dwnloads.html",
    "TDI Designated Catastrophe Areas",
    "map",
    "Linked from the Adopted Building Codes page",
    "TDI Product Evaluations Linked from the Windstorm Inspection Program page",
    "TDI ongoing versus completed tdi.texas.gov/wind/documents/TWIAFlowchart",
    "Item Location",
    "improvement flowchart",
    "TDI Windstorm intake Windstorm@tdi.texas.gov, 800-248-6032",
    "TDI Engineering Services",
    "(appointments, Windstorm system",
    "access)",
    "Engineering@tdi.texas.gov, 512-676-6750",
    "TWIA certification requirements for",
    "completed improvements",
    "twia.org/windstorm-certification-requirements",
    "Texas Insurance Code Chapter",
    "2210",
    "statutes.capitol.texas.gov",
    "28 TAC Chapter 5, Subchapter E Texas Administrative Code, Secretary of State",
    "TBPELS rules, 22 TAC Chapter 137 pels.texas.gov",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record and Appointed Qualified Inspector, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const WP001_COUNTS = [];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const WP001_OTHER_RULES = [];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const WP001_BLANK_JOB_LIST_ITEMS = 0;
