/**
 * 254-WS-001 v1.1, Windstorm Certification Protocol for Completed Construction (Form WPI-8E).
 *
 * TRANSCRIBED, NEVER WRITTEN. Generated on 2026-10-07 from the engineer's own
 * PDF, docs/protocols/incoming/v1.1/254-WS-001_Windstorm_Certification_Protocol_v1_1.pdf, read with pdftotext -raw, sha256 f4cbe248957298bbae6d968350d3732ef3197b46684959c6ec083f494f3ed6b5. Every string below
 * is the document's own, with page footers removed and the bullet glyph shown
 * as a bullet; line wrapping is the extraction's, rejoined. The document is the
 * authority and this file is its implementation, proved against the PDF in both
 * directions by protocol-registry-audit, section 8. It is registered in
 * received.ts and nowhere else.
 *
 * UNSIGNED. Issued 2026-10-06 and not yet signed. The engineer signs it in the
 * portal, from his own session, under ruling 2a of 2026-10-06. Until then it
 * drives nothing: it adds no intake field and opens no line.
 *
 * DO NOT EDIT BY HAND. A change to this file is a change to what the engineer
 * will be asked to sign. Regenerate from the PDF, and only from a new PDF.
 */
export const WS001 = {
  "documentNumber": "254-WS-001",
  "title": "Windstorm Certification Protocol for Completed Construction (Form WPI-8E)",
  "version": "1.1",
  "issueDate": "2026-10-06",
  "issueDateAsPrinted": "October 6, 2026",
  "preparedBy": "Aman Dhakal, P.E., Engineer of Record, 254 Engineering Services",
  "approvedBy": "Aman Dhakal, P.E., Engineer of Record",
  "appliesTo": "All windstorm certification engagements on completed improvements performed by 254 Engineering Services",
  "supersedes": "Version 1.0, dated October 4, 2026.",
  "serviceSlug": "windstorm-wpi-8",
  "serviceTier": "completed",
  "requiresDiscipline": null,
  "sourceFile": "docs/protocols/incoming/v1.1/254-WS-001_Windstorm_Certification_Protocol_v1_1.pdf",
  "sourceSha256": "f4cbe248957298bbae6d968350d3732ef3197b46684959c6ec083f494f3ed6b5",
  "firmNameOnDocument": "254 Engineering Services",
  "sections": [
    {
      "key": "job-information",
      "heading": "JOB INFORMATION",
      "at": "Appendix B"
    },
    {
      "key": "context",
      "heading": "CONTEXT (every job)",
      "at": "Appendix B"
    },
    {
      "key": "roof-covering",
      "heading": "ROOF COVERING",
      "at": "Appendix B"
    },
    {
      "key": "building-products",
      "heading": "BUILDING PRODUCTS",
      "at": "Appendix B"
    },
    {
      "key": "entire-building-or-addition",
      "heading": "ENTIRE BUILDING OR ADDITION (also complete Roof Covering and Building Products)",
      "at": "Appendix B"
    },
    {
      "key": "close-out",
      "heading": "CLOSE-OUT",
      "at": "Appendix B"
    }
  ],
  "photoProcedure": [
    {
      "step": 1,
      "text": "Before starting, make a rough sketch of the building, number each opening, and mark North. Take a photo of it.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 2,
      "text": "Tick the item you are about to photograph, take a photo of the checklist, then take the photos for that item.",
      "at": "Appendix B, PHOTOS"
    },
    {
      "step": 3,
      "text": "Move on to the next item the same way.",
      "at": "Appendix B, PHOTOS"
    }
  ],
  "intakeQuestions": [
    {
      "number": 1,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & requestor",
      "ask": "What is the certificate needed for? (TWIA policy / renewal / home sale / lender / other, record exactly)",
      "flag": false,
      "verbatim": true,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 2,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & requestor",
      "ask": "Who is requesting it, and what is their relationship to the property? (owner, contractor, agent)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 3,
      "group": "purpose-and-recipient",
      "groupHeading": "Purpose & requestor",
      "ask": "What deadline is the customer working against, if any?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 4,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property address and county",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 5,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property type (single family / duplex / townhome / small commercial) and number of stories",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 6,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Year built",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 7,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "What work is to be certified? (re-roof / windows and doors / garage door / siding / addition / entire building)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 8,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Date the work began and date it was completed",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 9,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Contractor who did the work (name and phone)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 10,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Property owner's name and contact. If the builder still owns it, the builder's",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 11,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Has a WPI-2E application already been started with TDI? If yes, the Application ID",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 12,
      "group": "property-basics",
      "groupHeading": "Property basics",
      "ask": "Is there an earlier windstorm certificate for this property? (WPI-8, WPI-8E, WPI-8C)",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 13,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is any of the work still in progress?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 14,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is there active or threatened litigation, or an open insurance dispute, involving this work?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 15,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Has TDI or another engineer already declined or denied certification of this work?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 16,
      "group": "flags",
      "groupHeading": "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
      "ask": "Is the customer unable to name the products that were installed?",
      "flag": true,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 17,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Is there attic access?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 18,
      "group": "access-and-safety",
      "groupHeading": "Access & safety (decides dispatch feasibility)",
      "ask": "Occupied or vacant? Accessible if occupied?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    },
    {
      "number": 19,
      "group": "prior-paperwork",
      "groupHeading": "Prior paperwork prompt",
      "ask": "Do you have: contract or invoice, product approvals or wrappers, photos taken during the work, plans, permit, earlier certificates, letters from TDI or TWIA?",
      "flag": false,
      "verbatim": false,
      "at": "Appendix A, Part 1"
    }
  ],
  "intakeUploads": [
    {
      "key": "photo-of-the-front-of-the-1",
      "what": "Photo of the front of the property (confirms address/structure)",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "contract-or-invoice-for-the-work-2",
      "what": "Contract or invoice for the work, showing the products installed",
      "tier": "required",
      "when": null,
      "tierHeading": "Required",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "photos-taken-during-the-work-before-3",
      "what": "Photos taken during the work, before it was covered",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "product-approvals-wrappers-labels-or-installation-4",
      "what": "Product approvals, wrappers, labels, or installation instructions",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "any-letter-from-tdi-or-twia-5",
      "what": "Any letter from TDI or TWIA about this property",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "earlier-windstorm-certificate-6",
      "what": "Earlier windstorm certificate",
      "tier": "required-if-exists",
      "when": null,
      "tierHeading": "Required if it exists",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "window-and-door-order-sheet-showing-7",
      "what": "Window and door order sheet showing sizes and design pressure ratings (building products)",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "shutter-or-opening-protection-paperwork-building-8",
      "what": "Shutter or opening protection paperwork (building products)",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "structural-drawings-foundation-plan-and-truss-9",
      "what": "Structural drawings, foundation plan, and truss drawings (entire building or addition)",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    },
    {
      "key": "permit-and-final-inspection-record-10",
      "what": "Permit and final inspection record",
      "tier": "when-applicable",
      "when": null,
      "tierHeading": "Collect when applicable",
      "at": "Appendix A, Part 2"
    }
  ],
  "checklist": [
    {
      "key": "photo-of-address-marker-house-number",
      "section": "job-information",
      "label": "Photo of address marker (house number, street sign, or mailbox)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "all-four-elevations-of-the-structure",
      "section": "context",
      "label": "All four elevations of the structure",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "view-away-from-the-building-on",
      "section": "context",
      "label": "View away from the building on each of the four sides, showing what surrounds it",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-roof-plane-overall",
      "section": "roof-covering",
      "label": "Each roof plane, overall",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "covering-type-and-product-name-from",
      "section": "roof-covering",
      "label": "Covering type and product name, from wrapper, marking, or leftover bundle",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "shingles-tab-lifted-at-four-locations",
      "section": "roof-covering",
      "label": "Shingles: tab lifted at four locations, one on each side of the building, ruler in frame, showing fastener count and placement",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "metal-panels-profile-fastener-type-and",
      "section": "roof-covering",
      "label": "Metal panels: profile, fastener type, and fastener spacing measured at eave, field, and ridge",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "tile-or-other-covering-fastening-at",
      "section": "roof-covering",
      "label": "Tile or other covering: fastening at eave, field, and ridge where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "eave-and-rake-edge-drip-edge",
      "section": "roof-covering",
      "label": "Eave and rake edge: drip edge, starter, and underlayment where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "hip-and-ridge",
      "section": "roof-covering",
      "label": "Hip and ridge",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-roof-vent-type-label-if",
      "section": "roof-covering",
      "label": "Every roof vent: type, label if any, and fastening",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-skylight-label-and-curb",
      "section": "roof-covering",
      "label": "Every skylight: label and curb",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "roof-deck-from-the-attic-panel",
      "section": "roof-covering",
      "label": "Roof deck from the attic: panel stamp showing type and thickness",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "deck-fastening-from-the-attic-nails",
      "section": "roof-covering",
      "label": "Deck fastening from the attic: nails visible along a rafter or truss, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "each-area-opened-by-the-owner",
      "section": "roof-covering",
      "label": "Each area opened by the owner's contractor: underlayment, deck, and deck fastening exposed, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-window-wide-then-label-then",
      "section": "building-products",
      "label": "Every window: wide, then label, then tape across width and height",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-exterior-door-wide-then-label",
      "section": "building-products",
      "label": "Every exterior door: wide, then label on the hinge edge or frame, then tape across width and height",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-sliding-door-wide-label-and",
      "section": "building-products",
      "label": "Every sliding door: wide, label, and size",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "every-garage-door-wide-from-inside",
      "section": "building-products",
      "label": "Every garage door: wide from inside, label on the door section, size, and track fastening",
      "photo": true,
      "ruler": false,
      "perOccurrence": true,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "impact-marking-on-the-glass-or",
      "section": "building-products",
      "label": "Impact marking on the glass, or the shutter and its installed hardware, for every glazed opening",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "fastening-of-each-window-and-door",
      "section": "building-products",
      "label": "Fastening of each window and door to the wall where visible, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exterior-wall-covering-type-product-marking",
      "section": "building-products",
      "label": "Exterior wall covering: type, product marking, and fastening where visible, each elevation",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "foundation-type-and-anchorage-where-visible",
      "section": "entire-building-or-addition",
      "label": "Foundation type and anchorage where visible: anchor bolts or straps at the sill plate, spacing measured",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "hold-downs-and-straps-at-wall",
      "section": "entire-building-or-addition",
      "label": "Hold-downs and straps at wall ends and corners where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "wall-sheathing-type-and-nailing-where",
      "section": "entire-building-or-addition",
      "label": "Wall sheathing type and nailing where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "stud-to-plate-connections-where-visible",
      "section": "entire-building-or-addition",
      "label": "Stud to plate connections where visible",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "roof-to-wall-connectors-in-the",
      "section": "entire-building-or-addition",
      "label": "Roof to wall connectors in the attic: connector marking, nails in each, and count over a 10 ft length of wall, each side",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "rafter-or-truss-size-and-spacing",
      "section": "entire-building-or-addition",
      "label": "Rafter or truss size and spacing, tape in frame",
      "photo": true,
      "ruler": true,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "gable-end-bracing",
      "section": "entire-building-or-addition",
      "label": "Gable end bracing",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "floor-to-floor-straps-where-visible",
      "section": "entire-building-or-addition",
      "label": "Floor to floor straps where visible (two stories)",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "porch-carport-and-patio-cover-posts",
      "section": "entire-building-or-addition",
      "label": "Porch, carport, and patio cover posts: connection at top and at bottom, every post",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "outdoor-mechanical-equipment-anchorage-of-each",
      "section": "entire-building-or-addition",
      "label": "Outdoor mechanical equipment: anchorage of each unit",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "addition-where-and-how-it-joins",
      "section": "entire-building-or-addition",
      "label": "Addition: where and how it joins the main structure",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "full-perimeter-walk-anything-unusual",
      "section": "close-out",
      "label": "Full perimeter walk: anything unusual",
      "photo": true,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    },
    {
      "key": "exception-menu-cleared-for-every-non",
      "section": "close-out",
      "label": "Exception menu cleared for every non-applicable item",
      "photo": false,
      "ruler": false,
      "perOccurrence": false,
      "coveringOnly": null,
      "capture": null,
      "at": "Appendix B"
    }
  ],
  "determinations": [
    {
      "key": "pass",
      "heading": "PASS",
      "effect": null,
      "criteria": [
        "Package complete: every checklist item for the scope present or properly excepted",
        "Every product in scope identified, with a current product evaluation or test report",
        "Rated design pressure of every product meets or exceeds the required design pressure",
        "Every product is within the largest size tested",
        "Installation matches the product evaluation or manufacturer's instructions at every location photographed",
        "Opening protection present where the applicable code requires it",
        "Entire building or addition: load path verified from roof to foundation",
        "Every concealed item in scope opened and photographed at the locations the engineer set"
      ],
      "at": "Appendix C"
    },
    {
      "key": "revise",
      "heading": "REVISE",
      "effect": null,
      "criteria": [
        "Any required photo missing, blurry, or a label that cannot be read",
        "An opening on the sketch with no record, or a record with no size",
        "Counts or measurements inconsistent with photos",
        "Exception used where the condition plainly applied"
      ],
      "at": "Appendix C"
    },
    {
      "key": "repairs-required",
      "heading": "REPAIRS REQUIRED (compliance report withheld, repair list issued)",
      "effect": "compliance report withheld, repair list issued",
      "criteria": [
        "A product rated below the required design pressure",
        "A product larger than the largest size tested",
        "Fastening that does not match the product evaluation or manufacturer's instructions",
        "Opening protection missing where the applicable code requires it",
        "A load path connection missing or not installed to the applicable code",
        "A product with no product evaluation or test report",
        "The compliance report proceeds only after repairs are verified on revisit"
      ],
      "at": "Appendix C"
    },
    {
      "key": "site-revisit",
      "heading": "SITE REVISIT (technician returns with an engineer-specified capture list)",
      "effect": "technician returns with an engineer-specified capture list",
      "criteria": [
        "Label not found on the first visit, return after the customer supplies the product paperwork and match it to the installed product",
        "Concealed item not yet opened, return after the owner's contractor opens it and photograph it",
        "Conflicting evidence (invoice vs. label vs. photos), return for the specific items that settle it",
        "Repairs required, return after repairs to verify each item on the repair list"
      ],
      "at": "Appendix C"
    },
    {
      "key": "decline",
      "heading": "DECLINE",
      "effect": null,
      "criteria": [
        "Work still in progress, route to ongoing construction windstorm line",
        "Property outside the designated catastrophe area",
        "The work being certified began before January 1, 1988, decline, with a referral to TWIA",
        "Request is for cause or extent of storm damage, decline, with a referral to an independent firm",
        "Active or threatened litigation, decline",
        "Concealed work the owner will not have opened",
        "Customer requests a predetermined conclusion, automatic decline, log verbatim request"
      ],
      "at": "Appendix C"
    }
  ],
  "thresholds": [],
  "text": [
    "254 ENGINEERING SERVICES",
    "Windstorm Certification Protocol",
    "Document Value",
    "Title Windstorm Certification Protocol for Completed Construction",
    "(Form WPI-8E)",
    "Document number 254-WS-001",
    "Version 1.1",
    "Issue date October 6, 2026",
    "Prepared by Aman Dhakal, P.E., Engineer of Record, 254 Engineering",
    "Services",
    "Approval Aman Dhakal, P.E., Engineer of Record",
    "Applies to All windstorm certification engagements on completed",
    "improvements performed by 254 Engineering Services",
    "Supersedes Version 1.0, dated October 4, 2026.",
    "1. Purpose",
    "This protocol establishes how 254 Engineering Services inspects completed improvements for",
    "windstorm certification so that the engineer can seal a postconstruction evaluation report and apply",
    "to the Texas Department of Insurance (TDI) for a Certificate of Compliance for Completed",
    "Improvement, Form WPI-8E, supported by an evidence package collected by a field technician",
    "under the engineer's supervision.",
    "The engineer signs and seals the evaluation report personally and is the engineer named on the",
    "certificate. Every requirement in this protocol exists so that the engineer can confirm compliance",
    "from the evidence package alone.",
    "2. Scope",
    "This protocol applies to completed improvements on residential and light commercial structures in",
    "the designated catastrophe area, where the owner needs a certificate of compliance for windstorm",
    "and hail insurance through the Texas Windstorm Insurance Association.",
    "The firm offers three certification scopes, matching 28 TAC 5.4606(b). The scope is recorded at",
    "intake and the report certifies that scope only.",
    "• Roof covering. The roof covering assembly, including covering, fasteners, underlayment, roof",
    "deck, roof vents, and skylights.",
    "• Building products. Windows, exterior doors, sliding doors, garage doors, exterior wall",
    "coverings, and opening protection.",
    "• Entire building or addition. Accepted only where the engineer finds at intake that the load path",
    "can be verified from plans, construction photographs, or framing that is open to view.",
    "This protocol does not cover ongoing construction, which is inspected under the engineer's TDI",
    "appointment and the firm's ongoing construction windstorm protocol; certification by sealed design",
    "under 28 TAC 5.4604(a)(1), which is available only where the firm designed the improvement;",
    "structural design; or repair specification. The firm does not perform forensic or cause-of-loss",
    "investigation under this or any protocol.",
    "3. Governing requirements",
    "• Texas Insurance Code Chapter 2210 and 28 TAC 5.4601 through 5.4642. A Texas licensed",
    "professional engineer may certify a completed improvement. A TDI appointment is not required",
    "for this protocol.",
    "• 28 TAC 5.4604(a)(2). The application is supported by a sealed postconstruction evaluation",
    "report that confirms the improvement complies with the applicable building code under the plan",
    "of operation and includes supporting evidence.",
    "• 28 TAC 5.4606. Supporting evidence for the scope being certified. The Code names what the",
    "evidence must verify. Appendix B is the engineer's list of what the technician captures so that",
    "evidence exists.",
    "• The applicable windstorm building code is set by the date construction began. For construction",
    "that began on or after April 1, 2026, the 2024 International Residential Code and International",
    "Building Code with Texas revisions. For construction that began from September 1, 2020",
    "through March 31, 2026, the 2018 editions. For earlier work, the code TDI lists for that date.",
    "The engineer records the applicable code for each job.",
    "• Product evaluations from TDI, ICC-ES, IAPMO Uniform ES, Miami-Dade, the Florida Building",
    "Code, UL, FM, and comparable recognized agencies are acceptable. A TDI listing is not",
    "required.",
    "• TDI issues the certificate. The firm does not issue it and does not promise that TDI will.",
    "4. Roles and responsibilities",
    "Only the Engineer of Record determines the applicable code, the wind design conditions, the",
    "outcome of a job, and the wording of the report. The field technician and the coordinator relay the",
    "engineer's written determination without interpretation, addition, or estimate of when a certificate will",
    "issue.",
    "• The engineer determines the items of the WPI-2E application that are engineering",
    "determinations: building code and wind load standard, wind speed, risk category, exposure",
    "category, and opening protection. These are never asked of the customer or the technician.",
    "• The coordinator enters the application in TDI's Windstorm system for the engineer's review,",
    "tracks the Application ID, and submits the engineer's sealed documents.",
    "• The technician records and photographs what is installed. The technician gives no opinion on",
    "compliance.",
    "5. Personnel qualifications",
    "Field Technician",
    "• At least two years of documented experience in residential construction, roofing, window and",
    "door installation, or windstorm inspection, or equivalent experience the engineer accepts in",
    "writing.",
    "• Completion of the engineer's training on this protocol and Appendix B, with a supervised",
    "inspection before independent work.",
    "• Demonstrated ability to find and read product labels, and to read plans and locate items in the",
    "field against them.",
    "• Annual refresher training when the adopted code, this protocol, or Appendix B changes.",
    "Engineer of Record",
    "• Active Texas P.E. license. A copy, with expiration date, is held in the firm's compliance file.",
    "6. Intake",
    "• The coordinator opens a job file for each property. The file records the intake answers and",
    "customer uploads required by Appendix A.",
    "• The coordinator records the purpose of the certificate and the requestor exactly as given at",
    "intake.",
    "• The coordinator records the certification scope as roof covering, building products, or entire",
    "building or addition, and the dates construction began and was completed.",
    "• The coordinator records the items of the WPI-2E application the customer can answer: the",
    "owner's or builder's name and contact, and whether title has passed from the builder to the first",
    "owner.",
    "• A scope of entire building or addition routes the job to the engineer before dispatch. Work that",
    "began before January 1, 1988 is declined under section 12.",
    "• A yes to any flag question in Appendix A routes the job to the engineer before dispatch. The",
    "engineer records accept, accept with conditions, or decline.",
    "• Work that needs no inspection under 28 TAC 5.4605 is not opened as a job. The coordinator",
    "tells the customer in writing that TDI does not require a certificate for it.",
    "• A job is not dispatched until intake is complete and every upload required by Appendix A has",
    "been received.",
    "• The engineer records any condition of acceptance in the job file, including where concealed",
    "work is to be opened and any item the technician must capture beyond Appendix B.",
    "7. Scheduling and dispatch",
    "• The coordinator schedules an accepted job within two business days. The engineer may set a",
    "different interval for a job in the job file.",
    "• The technician confirms access, occupancy, and attic availability before travel.",
    "• The coordinator tells the customer before the visit that concealed work in the scope must be",
    "opened by their contractor at the locations the engineer sets.",
    "• Where site conditions prevent complete capture, including weather, access, or safety, the",
    "technician records each item that could not be observed and the reason. No item is estimated,",
    "assumed, or left blank.",
    "8. Field inspection",
    "The technician completes the job information and context sections of Appendix B on every job, and",
    "every item of the section for the scope recorded at intake, in the order listed, following the photo",
    "procedure printed at the head of that checklist.",
    "• Before starting, the technician makes a rough sketch of the building, marks North, numbers",
    "each opening on the sketch where openings are in scope, and photographs the sketch.",
    "• The technician ticks the item being photographed, photographs the checklist, then takes the",
    "photographs for that item, and moves to the next item the same way.",
    "• An item that does not apply to the property is marked with the reason it does not apply.",
    "• The counts and measurements called for on the checklist are recorded as counts and",
    "measurements, not as descriptions.",
    "• The technician does not remove or open any finish. A concealed item in the scope is opened",
    "by the owner's contractor so the technician can photograph it. The engineer sets where and",
    "how much is opened.",
    "9. Evidence standard and engineer review",
    "Evidence package",
    "Each job produces one evidence package in the firm's field application, consisting of the completed",
    "Appendix B checklist, the photographs, the technician's notes, and the customer uploads.",
    "• Every checklist item has at least one wide photograph placing the item on the structure and",
    "one close photograph showing its condition.",
    "• Every product label is photographed so that every line on it can be read.",
    "• Every opening in scope is photographed and measured individually. A representative sample",
    "is not acceptable.",
    "• Where a size, spacing, or count governs, a tape or ruler is in frame.",
    "• Photographs are captured directly in the firm's field application and carry device time, server",
    "time, the difference between them, and location. Photographs sent by text or messaging app,",
    "or taken on another device, are not accepted from the technician.",
    "• Photographs the customer or contractor took during installation are accepted as customer",
    "uploads. They do not replace opening a concealed item.",
    "• An observation that cannot be made is recorded as not observed with the reason.",
    "• A package that does not cover every checklist item for the scope is rejected without review.",
    "Engineer review",
    "• The engineer records the applicable code, wind speed, risk category, exposure category, and",
    "required design pressures for the job, and the product evaluation relied on for each product in",
    "scope.",
    "• The engineer reviews each evidence package and records one of the five determinations in",
    "Appendix C: pass, revise, repairs required, site revisit, or decline.",
    "• The engineer's review record identifies the checklist items, photographs, and documents relied",
    "on for the determination.",
    "• A package that does not allow the engineer to verify a required item is returned for revision or",
    "a site revisit.",
    "10. Deficiencies and repairs",
    "• On a repairs required determination, the engineer issues a written repair list identifying each",
    "item, what governs it, and what is required to close it.",
    "• Repairs are performed by others. 254 Engineering Services does not perform, supervise, or",
    "recommend a contractor for the repair work.",
    "• Corrections are verified on a site revisit to the same evidence standard, and the engineer",
    "closes each item individually.",
    "• No report confirming compliance is sealed with an open repair item.",
    "• Where the owner does not make the repairs, the engineer seals a report stating that the",
    "improvement does not comply and why. That report goes to the customer. It is not submitted to",
    "TDI as a certification.",
    "11. Evaluation report and certification",
    "• On a pass determination, the engineer seals a postconstruction evaluation report that identifies",
    "the property, the certification scope, the applicable code, the wind design conditions, each",
    "product in scope with its evaluation, and the evidence relied on, and confirms that the",
    "improvement complies with the applicable code.",
    "• The engineer signs the WPI-2E application. The coordinator submits the application, the",
    "sealed report, and the supporting evidence through TDI's Windstorm system, or by email to",
    "windstorm@tdi.texas.gov if the system is unavailable. The property address and Application ID",
    "are on every document.",
    "• Where TDI asks for more evidence, the coordinator routes the request to the engineer the day",
    "it is received. Only the engineer answers it.",
    "• The report covers the scope recorded at intake only. It states that the inspection was visual",
    "except where work was opened, states where concealed work was opened and photographed,",
    "and reflects condition on the date of inspection.",
    "• The report does not forecast how the improvement will perform in a future storm and does not",
    "warrant the work.",
    "• The engineer does not certify an improvement that was not inspected under this protocol by",
    "this firm.",
    "12. Exclusions",
    "The following are declined or routed to another service line under its own engagement terms. The",
    "coordinator records the routing in the job file and informs the customer in writing.",
    "• Construction that is still in progress. Routed to the ongoing construction windstorm line.",
    "• A property outside the designated catastrophe area. Declined. No TDI certificate applies.",
    "• Work to be certified that began before January 1, 1988. Eligibility follows the date the work",
    "being certified began, not the year the building was built. Declined, with a referral to TWIA.",
    "• A request to determine the cause or extent of storm damage. Declined, with a referral to an",
    "independent firm.",
    "• Active or threatened litigation involving the improvement. Declined.",
    "• Concealed work in the scope that the owner will not have opened. Declined.",
    "• A customer request for a predetermined conclusion. This is an automatic decline and the",
    "request is logged verbatim.",
    "13. Records and retention",
    "• Each job file contains: the intake record and customer uploads, the engineer's acceptance",
    "record, the dispatch record, the completed Appendix B checklist, all photographs, the",
    "technician's notes, the engineer's review record and determination, any repair list and its",
    "closure records, the sealed report, the WPI-2E application with its Application ID, all TDI",
    "correspondence, and the certificate.",
    "• Job files are retained for ten years from the date of the report. For a job that produces no",
    "report, the ten years runs from the date of the engineer's last recorded determination or",
    "closure.",
    "• 28 TAC 5.4606(d) requires the engineer named on the certificate to keep the supporting",
    "evidence for each component for five years from the most recent certification application on",
    "the structure. The ten-year retention satisfies it.",
    "• The engineer keeps access to the supporting evidence for every certificate that names him for",
    "the full retention period, including after he leaves the firm.",
    "• The compliance file holds the engineer's license records, technician qualification and training",
    "records, and every issued version of this protocol.",
    "14. Protocol maintenance",
    "• The engineer reviews this protocol annually, and within thirty days of any change to the TDI",
    "rules, the adopted code, or the firm's field application.",
    "• Revisions are issued as a new version number with the effective date and the engineer's",
    "approval recorded in the document control table.",
    "• This document follows the firm's house protocol format. The portal's four parts are carried in",
    "Appendices A through C. Appendix A carries both the intake questions and the customer",
    "uploads. Appendix D is the reference list.",
    "Appendix A. Intake questions and customer uploads",
    "Asked and collected by the coordinator before the job is created. A job is not dispatched until every",
    "required item is present.",
    "PART 1: INTAKE QUESTIONS",
    "Purpose & requestor",
    "1. What is the certificate needed for? (TWIA policy / renewal / home sale / lender / other, record",
    "exactly)",
    "Answer: ____________________________________________________",
    "2. Who is requesting it, and what is their relationship to the property? (owner, contractor, agent)",
    "Answer: ____________________________________________________",
    "3. What deadline is the customer working against, if any?",
    "Answer: ____________________________________________________",
    "Property basics",
    "4. Property address and county",
    "Answer: ____________________________________________________",
    "5. Property type (single family / duplex / townhome / small commercial) and number of stories",
    "Answer: ____________________________________________________",
    "6. Year built",
    "Answer: ____________________________________________________",
    "7. What work is to be certified? (re-roof / windows and doors / garage door / siding / addition / entire",
    "building)",
    "Answer: ____________________________________________________",
    "8. Date the work began and date it was completed",
    "Answer: ____________________________________________________",
    "9. Contractor who did the work (name and phone)",
    "Answer: ____________________________________________________",
    "10. Property owner's name and contact. If the builder still owns it, the builder's",
    "Answer: ____________________________________________________",
    "11. Has a WPI-2E application already been started with TDI? If yes, the Application ID",
    "Answer: ____________________________________________________",
    "12. Is there an earlier windstorm certificate for this property? (WPI-8, WPI-8E, WPI-8C)",
    "Answer: ____________________________________________________",
    "Flags: a YES on any of these routes to engineer review BEFORE dispatch",
    "13. Is any of the work still in progress?",
    "Yes No If yes, describe: ____________________________________________________",
    "14. Is there active or threatened litigation, or an open insurance dispute, involving this work?",
    "Yes No If yes, describe: ____________________________________________________",
    "15. Has TDI or another engineer already declined or denied certification of this work?",
    "Yes No If yes, describe: ____________________________________________________",
    "16. Is the customer unable to name the products that were installed?",
    "Yes No If yes, describe: ____________________________________________________",
    "Access & safety (decides dispatch feasibility)",
    "17. Is there attic access?",
    "Answer: ____________________________________________________",
    "18. Occupied or vacant? Accessible if occupied?",
    "Answer: ____________________________________________________",
    "Prior paperwork prompt",
    "19. Do you have: contract or invoice, product approvals or wrappers, photos taken during the work,",
    "plans, permit, earlier certificates, letters from TDI or TWIA?",
    "Answer: ____________________________________________________",
    "PART 2: CUSTOMER UPLOADS (collected at intake, before dispatch)",
    "Required",
    "-- Photo of the front of the property (confirms address/structure)",
    "-- Contract or invoice for the work, showing the products installed",
    "Required if it exists",
    "-- Photos taken during the work, before it was covered",
    "-- Product approvals, wrappers, labels, or installation instructions",
    "-- Any letter from TDI or TWIA about this property",
    "-- Earlier windstorm certificate",
    "Collect when applicable",
    "-- Window and door order sheet showing sizes and design pressure ratings (building products)",
    "-- Shutter or opening protection paperwork (building products)",
    "-- Structural drawings, foundation plan, and truss drawings (entire building or addition)",
    "-- Permit and final inspection record",
    "Appendix B. Technician on-site checklist",
    "Completed on site by the technician. The checklist cannot be submitted incomplete. Job information",
    "and context are completed on every job. After that, complete the section for the scope on the",
    "dispatch.",
    "PHOTOS",
    "-- Before starting, make a rough sketch of the building, number each opening, and mark North. Take",
    "a photo of it.",
    "-- Tick the item you are about to photograph, take a photo of the checklist, then take the photos for",
    "that item.",
    "-- Move on to the next item the same way.",
    "JOB INFORMATION",
    "Job / Dispatch No.: ____________________________",
    "Property address (full, incl. county):",
    "__________________________________________________________",
    "Technician name: ______________________________________",
    "Date / arrival time / departure time: ________________________________________",
    "Weather during visit: ________________________________________",
    "Contact on site (name, role, phone): ________________________________________________",
    "[ ] Photo of address marker (house number, street sign, or mailbox) [PHOTO]",
    "CONTEXT (every job)",
    "[ ] All four elevations of the structure [PHOTO]",
    "[ ] View away from the building on each of the four sides, showing what surrounds it [PHOTO]",
    "Building length (ft): ________ width (ft): ________ height to eave (ft): ________ height to ridge (ft):",
    "________",
    "Roof shape (gable / hip / flat / other) and stories: __________________________________",
    "Roof pitch, measured, each plane: __________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "ROOF COVERING",
    "[ ] Each roof plane, overall [PHOTO]",
    "[ ] Covering type and product name, from wrapper, marking, or leftover bundle [PHOTO]",
    "[ ] Shingles: tab lifted at four locations, one on each side of the building, ruler in frame, showing",
    "fastener count and placement [PHOTO]",
    "[ ] Metal panels: profile, fastener type, and fastener spacing measured at eave, field, and ridge",
    "[PHOTO]",
    "[ ] Tile or other covering: fastening at eave, field, and ridge where visible [PHOTO]",
    "[ ] Eave and rake edge: drip edge, starter, and underlayment where visible [PHOTO]",
    "[ ] Hip and ridge [PHOTO]",
    "[ ] Every roof vent: type, label if any, and fastening [PHOTO]",
    "[ ] Every skylight: label and curb [PHOTO]",
    "[ ] Roof deck from the attic: panel stamp showing type and thickness [PHOTO]",
    "[ ] Deck fastening from the attic: nails visible along a rafter or truss, tape in frame [PHOTO]",
    "[ ] Each area opened by the owner's contractor: underlayment, deck, and deck fastening exposed,",
    "tape in frame [PHOTO]",
    "Fasteners per shingle at each of the four locations: ____ ____ ____ ____",
    "Roof vents ____ skylights ____ items concealed ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "BUILDING PRODUCTS",
    "[ ] Every window: wide, then label, then tape across width and height [PHOTO]",
    "[ ] Every exterior door: wide, then label on the hinge edge or frame, then tape across width and",
    "height [PHOTO]",
    "[ ] Every sliding door: wide, label, and size [PHOTO]",
    "[ ] Every garage door: wide from inside, label on the door section, size, and track fastening [PHOTO]",
    "[ ] Impact marking on the glass, or the shutter and its installed hardware, for every glazed opening",
    "[PHOTO]",
    "[ ] Fastening of each window and door to the wall where visible, tape in frame [PHOTO]",
    "[ ] Exterior wall covering: type, product marking, and fastening where visible, each elevation",
    "[PHOTO]",
    "Opening number, type, width x height (in.), and what the label says, for every opening on the sketch:",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Openings total ____ with a label that can be read ____ without a label ____",
    "ENTIRE BUILDING OR ADDITION (also complete Roof Covering and Building",
    "Products)",
    "[ ] Foundation type and anchorage where visible: anchor bolts or straps at the sill plate, spacing",
    "measured [PHOTO]",
    "[ ] Hold-downs and straps at wall ends and corners where visible [PHOTO]",
    "[ ] Wall sheathing type and nailing where visible [PHOTO]",
    "[ ] Stud to plate connections where visible [PHOTO]",
    "[ ] Roof to wall connectors in the attic: connector marking, nails in each, and count over a 10 ft length",
    "of wall, each side [PHOTO]",
    "[ ] Rafter or truss size and spacing, tape in frame [PHOTO]",
    "[ ] Gable end bracing [PHOTO]",
    "[ ] Floor to floor straps where visible (two stories) [PHOTO]",
    "[ ] Porch, carport, and patio cover posts: connection at top and at bottom, every post [PHOTO]",
    "[ ] Outdoor mechanical equipment: anchorage of each unit [PHOTO]",
    "[ ] Addition: where and how it joins the main structure [PHOTO]",
    "Connectors counted over 10 ft ____ connectors missing ____ items concealed ____",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "CLOSE-OUT",
    "[ ] Full perimeter walk: anything unusual [PHOTO]",
    "[ ] Exception menu cleared for every non-applicable item",
    "Total photos: ______________",
    "Technician signature / date: ____________________________________________",
    "Technician notes / readings:",
    "________________________________________________________________________________",
    "________",
    "________________________________________________________________________________",
    "________",
    "Appendix C. Engineer decision rules",
    "Applied by the engineer to each evidence package. One determination is recorded per review.",
    "PASS",
    "-- Package complete: every checklist item for the scope present or properly excepted",
    "-- Every product in scope identified, with a current product evaluation or test report",
    "-- Rated design pressure of every product meets or exceeds the required design pressure",
    "-- Every product is within the largest size tested",
    "-- Installation matches the product evaluation or manufacturer's instructions at every location",
    "photographed",
    "-- Opening protection present where the applicable code requires it",
    "-- Entire building or addition: load path verified from roof to foundation",
    "-- Every concealed item in scope opened and photographed at the locations the engineer set",
    "REVISE",
    "-- Any required photo missing, blurry, or a label that cannot be read",
    "-- An opening on the sketch with no record, or a record with no size",
    "-- Counts or measurements inconsistent with photos",
    "-- Exception used where the condition plainly applied",
    "REPAIRS REQUIRED (compliance report withheld, repair list issued)",
    "-- A product rated below the required design pressure",
    "-- A product larger than the largest size tested",
    "-- Fastening that does not match the product evaluation or manufacturer's instructions",
    "-- Opening protection missing where the applicable code requires it",
    "-- A load path connection missing or not installed to the applicable code",
    "-- A product with no product evaluation or test report",
    "-- The compliance report proceeds only after repairs are verified on revisit",
    "SITE REVISIT (technician returns with an engineer-specified capture list)",
    "-- Label not found on the first visit, return after the customer supplies the product paperwork and",
    "match it to the installed product",
    "-- Concealed item not yet opened, return after the owner's contractor opens it and photograph it",
    "-- Conflicting evidence (invoice vs. label vs. photos), return for the specific items that settle it",
    "-- Repairs required, return after repairs to verify each item on the repair list",
    "DECLINE",
    "-- Work still in progress, route to ongoing construction windstorm line",
    "-- Property outside the designated catastrophe area",
    "-- The work being certified began before January 1, 1988, decline, with a referral to TWIA",
    "-- Request is for cause or extent of storm damage, decline, with a referral to an independent firm",
    "-- Active or threatened litigation, decline",
    "-- Concealed work the owner will not have opened",
    "-- Customer requests a predetermined conclusion, automatic decline, log verbatim request",
    "Appendix D. References",
    "Item Location",
    "Texas Insurance Code",
    "Chapter 2210",
    "statutes.capitol.texas.gov",
    "28 TAC 5.4601 through",
    "5.4642, Inspections for",
    "Windstorm and Hail",
    "Insurance",
    "Texas Administrative Code",
    "28 TAC 5.4604, Certification",
    "Form for Completed",
    "Texas Administrative Code",
    "Improvement",
    "28 TAC 5.4605, Items Not",
    "Requiring an Inspection",
    "Texas Administrative Code; tdi.texas.gov/wind/no-inspection-",
    "required.html",
    "28 TAC 5.4606, Supporting",
    "Evidence for Sealed",
    "Postconstruction",
    "Evaluation Report and",
    "Design",
    "Texas Administrative Code",
    "Form WPI-2E, Application",
    "for Certificate of",
    "Compliance for Completed",
    "Improvement",
    "TDI Windstorm system",
    "2024 International",
    "Residential Code and",
    "International Building Code",
    "with Texas revisions",
    "tdi.texas.gov/wind",
    "ASCE 7 and the ASCE",
    "Hazard Tool",
    "ascehazardtool.org",
    "Texas Engineering Practice",
    "Act, Texas Occupations",
    "Code Chapter 1001",
    "statutes.capitol.texas.gov",
    "TBPELS rules, 22 TAC",
    "Chapter 137",
    "pels.texas.gov",
    "254-RC-001 Roof",
    "Certification Protocol, v1.1,",
    "issued September 18, 2026",
    "Firm document",
    "Approval",
    "Reviewed and approved by the Engineer of Record. This protocol is in force from the date below.",
    "Aman Dhakal, P.E.",
    "Engineer of Record, 254 Engineering Services",
    "Signature: ______________________________________ Date: __________________"
  ]
} as const;

/** Capture fields printed on the checklist, verbatim, blanks included. */
export const WS001_COUNTS = [
  {
    "key": "field-1",
    "prompt": "Job / Dispatch No.: ____________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-2",
    "prompt": "Property address (full, incl. county):",
    "at": "Appendix B"
  },
  {
    "key": "field-3",
    "prompt": "Technician name: ______________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-4",
    "prompt": "Date / arrival time / departure time: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-5",
    "prompt": "Weather during visit: ________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-6",
    "prompt": "Contact on site (name, role, phone): ________________________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-7",
    "prompt": "Building length (ft): ________ width (ft): ________ height to eave (ft): ________ height to ridge (ft):",
    "at": "Appendix B"
  },
  {
    "key": "field-8",
    "prompt": "Roof shape (gable / hip / flat / other) and stories: __________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-9",
    "prompt": "Roof pitch, measured, each plane: __________________________________",
    "at": "Appendix B"
  },
  {
    "key": "field-10",
    "prompt": "Fasteners per shingle at each of the four locations: ____ ____ ____ ____",
    "at": "Appendix B"
  },
  {
    "key": "field-11",
    "prompt": "Roof vents ____ skylights ____ items concealed ____",
    "at": "Appendix B"
  },
  {
    "key": "field-12",
    "prompt": "Opening number, type, width x height (in.), and what the label says, for every opening on the sketch:",
    "at": "Appendix B"
  },
  {
    "key": "field-13",
    "prompt": "Openings total ____ with a label that can be read ____ without a label ____",
    "at": "Appendix B"
  },
  {
    "key": "field-14",
    "prompt": "Connectors counted over 10 ft ____ connectors missing ____ items concealed ____",
    "at": "Appendix B"
  },
  {
    "key": "field-15",
    "prompt": "Total photos: ______________",
    "at": "Appendix B"
  },
  {
    "key": "field-16",
    "prompt": "Technician signature / date: ____________________________________________",
    "at": "Appendix B"
  }
];

/** Decision rules that are not the five determinations (DS-001 decides by acceptance and an issue check). */
export const WS001_OTHER_RULES = [];

/** Checklist lines the document leaves blank for the engineer to write per job. */
export const WS001_BLANK_JOB_LIST_ITEMS = 0;
