-- ===========================================================================
-- 0018: roles and grants become data
--
-- Phase 10 Section 2. The platform had three roles compiled into a TypeScript
-- union and a static matrix. A firm that hires a coordinator, a salesperson or
-- a customer service representative needs more, and a buyer of this business
-- needs to see that access is governed rather than assumed.
--
-- WHAT DOES NOT BECOME DATA, AND THAT IS THE POINT
-- ------------------------------------------------
-- Sealing, the four review decisions, and authoring or publishing a protocol
-- are NOT in this schema. There is no row that grants them and no column that
-- represents them. They are bound in code to holding the engineer role, because
-- a seal represents a Texas PE licence and a licence is not something a
-- permission screen may confer.
--
-- Operator ruling, 2026-09-04: grantable-but-excluded leaves an exclusion
-- somebody can delete; unrepresentable leaves nothing to delete. The compiler
-- enforces it, in scripts/proofs/licensed-actions-are-unrepresentable.ts, which
-- fails the project typecheck the day one of them becomes grantable.
-- ===========================================================================

create table if not exists eng_roles (
  key           text primary key,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  name          text not null,

  /*
   * Where somebody holding this role lands after signing in.
   *
   * NOT NULL, so creating a role without one is impossible rather than
   * discouraged. Operator ruling: an owner created role silently inheriting
   * somebody else's home screen is the kind of thing nobody notices until a
   * salesperson lands on the review queue and wonders what it is. A default
   * would have made that the quiet behaviour.
   */
  landing_path  text not null,

  /*
   * A system role cannot be deleted or rekeyed. Its GRANTS are still the
   * owner's to change, because that is a decision about the firm.
   *
   * The engineer key matters most: holdsLicence compares against it, so
   * renaming it would quietly detach the licence from the people holding it.
   */
  is_system     boolean not null default false,

  description   text
);

create table if not exists eng_role_grants (
  role_key      text not null references eng_roles (key) on update cascade on delete cascade,
  action        text not null,
  created_at    timestamptz not null default now(),
  primary key (role_key, action)
);

create index if not exists eng_role_grants_role_idx on eng_role_grants (role_key);

alter table eng_roles enable row level security;
alter table eng_role_grants enable row level security;

drop trigger if exists eng_roles_touch on eng_roles;
create trigger eng_roles_touch before update on eng_roles
  for each row execute function eng_touch_updated_at();

comment on table eng_roles is
  'Roles as data, owner creatable. The licence bound capabilities are deliberately NOT representable here: see the header of 0018 and scripts/proofs.';
comment on column eng_roles.landing_path is
  'Where this role lands after signing in. NOT NULL so a new role cannot silently inherit somebody else''s home screen.';
comment on column eng_roles.is_system is
  'Cannot be deleted or rekeyed. Grants remain editable. The engineer key is compared against in code, so renaming it would detach the licence.';

-- ------------------------------------------------------------------ the seed
--
-- GENERATED by scripts/emit-role-seed.mjs from DEFAULT_ROLES, not typed by
-- hand. The three roles that already existed take their grants from the matrix
-- that was enforcing them the day before this ran, so nobody's access changes
-- on the day of the migration. A retyped list would have been a second chance
-- to get that wrong, and the mistake would have looked like a decision.

-- Generated by scripts/emit-role-seed.mjs from DEFAULT_ROLES. Do not hand edit.
insert into eng_roles (key, name, landing_path, is_system) values
  ('admin', 'Administrator', '/portal', true),
  ('engineer', 'Professional Engineer', '/portal/review', true),
  ('field_tech', 'Field Technician', '/portal/jobs', true),
  ('dispatcher', 'Dispatcher', '/portal/files', false),
  ('sales', 'Sales', '/portal/clients', false),
  ('customer_service', 'Customer Service', '/portal/files', false),
  ('read_only', 'Read Only', '/portal', false)
on conflict (key) do nothing;

insert into eng_role_grants (role_key, action) values
  ('admin', 'accounts.manage'),
  ('admin', 'audit.read'),
  ('admin', 'billing.read'),
  ('admin', 'clients.create'),
  ('admin', 'clients.list'),
  ('admin', 'clients.update'),
  ('admin', 'documents.deliver'),
  ('admin', 'documents.read'),
  ('admin', 'evidence.review'),
  ('admin', 'evidence.start'),
  ('admin', 'evidence.submit'),
  ('admin', 'files.assign'),
  ('admin', 'files.cancel'),
  ('admin', 'files.create'),
  ('admin', 'files.list'),
  ('admin', 'files.transition'),
  ('admin', 'files.update'),
  ('admin', 'jobs.manage'),
  ('admin', 'ledger.approve'),
  ('admin', 'ledger.read_all'),
  ('admin', 'ledger.read_own'),
  ('admin', 'messages.use'),
  ('admin', 'offers.dispatch'),
  ('admin', 'offers.list_own'),
  ('admin', 'offers.respond'),
  ('admin', 'payments.charge'),
  ('admin', 'payments.reconcile'),
  ('admin', 'payments.refund'),
  ('admin', 'pricing.read'),
  ('admin', 'profiles.create'),
  ('admin', 'profiles.force_reset'),
  ('admin', 'profiles.list'),
  ('admin', 'profiles.read_self'),
  ('admin', 'profiles.suspend'),
  ('admin', 'profiles.update'),
  ('admin', 'profiles.update_self'),
  ('admin', 'responsible_charge.read_all'),
  ('admin', 'responsible_charge.read_own'),
  ('admin', 'tasks.use'),
  ('admin', 'time.log_own'),
  ('engineer', 'clients.list'),
  ('engineer', 'documents.deliver'),
  ('engineer', 'documents.read'),
  ('engineer', 'evidence.review'),
  ('engineer', 'evidence.start'),
  ('engineer', 'evidence.submit'),
  ('engineer', 'files.list'),
  ('engineer', 'files.transition'),
  ('engineer', 'files.update'),
  ('engineer', 'ledger.read_own'),
  ('engineer', 'messages.use'),
  ('engineer', 'pricing.read'),
  ('engineer', 'profiles.read_self'),
  ('engineer', 'profiles.update_self'),
  ('engineer', 'responsible_charge.read_own'),
  ('engineer', 'tasks.use'),
  ('engineer', 'time.log_own'),
  ('field_tech', 'evidence.capture'),
  ('field_tech', 'evidence.start'),
  ('field_tech', 'evidence.submit'),
  ('field_tech', 'files.list'),
  ('field_tech', 'ledger.read_own'),
  ('field_tech', 'messages.use'),
  ('field_tech', 'offers.list_own'),
  ('field_tech', 'offers.respond'),
  ('field_tech', 'profiles.read_self'),
  ('field_tech', 'profiles.update_self'),
  ('field_tech', 'tasks.use'),
  ('dispatcher', 'clients.list'),
  ('dispatcher', 'files.assign'),
  ('dispatcher', 'files.list'),
  ('dispatcher', 'files.transition'),
  ('dispatcher', 'files.update'),
  ('dispatcher', 'messages.use'),
  ('dispatcher', 'offers.dispatch'),
  ('dispatcher', 'offers.list_own'),
  ('dispatcher', 'profiles.list'),
  ('dispatcher', 'profiles.read_self'),
  ('dispatcher', 'profiles.update_self'),
  ('dispatcher', 'tasks.use'),
  ('dispatcher', 'time.log_own'),
  ('sales', 'clients.create'),
  ('sales', 'clients.list'),
  ('sales', 'clients.update'),
  ('sales', 'files.create'),
  ('sales', 'files.list'),
  ('sales', 'messages.use'),
  ('sales', 'profiles.read_self'),
  ('sales', 'profiles.update_self'),
  ('sales', 'tasks.use'),
  ('sales', 'time.log_own'),
  ('customer_service', 'clients.list'),
  ('customer_service', 'files.list'),
  ('customer_service', 'messages.use'),
  ('customer_service', 'profiles.read_self'),
  ('customer_service', 'profiles.update_self'),
  ('customer_service', 'tasks.use'),
  ('customer_service', 'time.log_own'),
  ('read_only', 'audit.read'),
  ('read_only', 'billing.read'),
  ('read_only', 'clients.list'),
  ('read_only', 'documents.read'),
  ('read_only', 'files.list'),
  ('read_only', 'ledger.read_all'),
  ('read_only', 'pricing.read'),
  ('read_only', 'profiles.list'),
  ('read_only', 'profiles.read_self'),
  ('read_only', 'profiles.update_self'),
  ('read_only', 'responsible_charge.read_all')
on conflict (role_key, action) do nothing;

-- --------------------------------------------------- profiles point at a row
--
-- eng_profiles.role keeps its NAME and its VALUES. 'admin', 'engineer' and
-- 'field_tech' are now the keys of seeded rows rather than members of a check
-- constraint, so NO PROFILE ROW IS REWRITTEN and no session is invalidated.
--
-- Production holds exactly one profile, an active administrator, and it lands
-- on the administrator role without a gap: the row it points at was inserted
-- above, in the same transaction, before the constraint below is swapped.
-- THE OTHER ROLE CONSTRAINT STAYS, AND WAS CHECKED AGAINST THE NEW ROLES.
--
-- eng_profiles_role_fields says license_number and tdi_appointment belong only
-- to an engineer, and certification_status and coverage_counties only to a
-- field technician. It keys off the same role values and is NOT dropped: it is
-- still true, and it is what stops a salesperson row carrying a licence number.
--
-- Verified rather than assumed: those columns default to NULL, and
-- coverage_counties defaults to '{}', so a dispatcher, sales, customer service
-- or read only profile created with defaults satisfies it. A new role does not
-- need a change here.
alter table eng_profiles drop constraint if exists eng_profiles_role_check;

alter table eng_profiles
  add constraint eng_profiles_role_fkey
  foreign key (role) references eng_roles (key) on update cascade;

comment on column eng_profiles.role is
  'The role key, now a foreign key into eng_roles rather than a check constraint. Values are unchanged from before Phase 10 Section 2.';
