/*
 * ===========================================================================
 * 0055  254-RC-001 v1.1 ENTERS THE PLATFORM, AWAITING ITS ENGINEER.
 * ===========================================================================
 *
 * GENERATED BY scripts/seed-roof-protocol.mjs --emit-sql. Do not hand edit.
 * The generator hashes docs/254-RC-001-roof-certification-protocol-v1.1.pdf
 * and refuses to write anything if the digest disagrees with the registry.
 * `protocol-registry-audit` reads the digest back OUT of this file and
 * asserts it equals both the PDF on disk and the registry, so a hand edit
 * turns the board red naming all three values.
 *
 * WHAT THIS SEEDS IS PROVENANCE, NOT AN APPROVAL. Operator ruling, 2026-09-16,
 * restated because a migration is read by somebody who has not read the script.
 * The row lands in 'awaiting_engineer': the engineer has signed the DOCUMENT
 * and has not approved it in the PLATFORM. 0049's constraints mean a row in
 * that state can carry no approver, no approval time and no publication date,
 * so this migration could not forge an approval even if somebody edited it to
 * try. The approval is an act by a named engineer in his own session, through
 * `eng_approve_protocol`, and it is what seeds the 51 checklist items.
 *
 * THE INTEGER version IS 2, NOT 1. `unique (service_slug, version)`
 * makes it the platform's sequence for this service line, and v1.0 is version
 * 1 already. version_label carries the document's own label.
 *
 * requires_discipline IS NULL ON PURPOSE. Whether a roof certification is
 * structural work is the engineer's answer rather than a reading of the word
 * "roof", and roof-inspections stays a waitlist until he states it in writing.
 *
 * v1.0 IS NOT INSERTED. Operator ruling, 2026-09-21: RC001_VERSIONS in
 * src/content/protocols/rc-001.ts is the record Section 13 requires of every
 * issued version, and this table is not a second copy of it.
 */

/*
 * ASSERT THE TARGET BEFORE WRITING, the idiom 0049 and 0052 both use.
 *
 * A row already naming this document at this version label, with a DIFFERENT
 * digest, means somebody has to decide which document this protocol is. That
 * is not a decision a migration may make quietly, so it raises instead.
 */
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-RC-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from 'd050a21a2b2d43114de47989ca731f41e26951f195c90187e99c11705011e4ef';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-RC-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'roof-inspections', 'Roof Certification Protocol for Existing Roofs', 2, '1.1', 'awaiting_engineer', '254-RC-001 v1.1, issued 2026-09-18, signed 2026-09-20 by Aman Dhakal, P.E., Engineer of Record. Awaiting approval in the platform.', '254-RC-001', '2026-09-18', 'd050a21a2b2d43114de47989ca731f41e26951f195c90187e99c11705011e4ef', '254 Engineering Services', null, '2026-09-20'
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-RC-001'
    and version_label   = '1.1'
);

/*
 * AND ASSERT WHAT WE JUST DID, because an insert guarded by NOT EXISTS is
 * silent about whether it inserted. Exactly one row names this document at
 * this version label when this migration finishes, or the transaction rolls
 * back and says so.
 */
do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-RC-001'
    and version_label   = '1.1';
  if n <> 1 then
    raise exception 'eng: % row(s) record % v% and exactly one is required.',
      n, '254-RC-001', '1.1';
  end if;
end;
$$;
