/*
 * ===========================================================================
 * 0056  THE ENGINEER OF RECORD STATES THE DISCIPLINE 254-RC-001 REQUIRES.
 * ===========================================================================
 *
 * GENERATED BY scripts/seed-roof-protocol.mjs --emit-discipline-sql. Do not
 * hand edit. The value is read from RC001.requiresDiscipline, which is sourced
 * from the engineer's written direction of 2026-09-21,
 * held at the path recorded in src/config/engineer-directions.ts and digested
 * there. `protocol-registry-audit` reads this literal back out and asserts it
 * equals the registry, so a hand edit turns the board red naming both values.
 *
 * HIS WORDS: "Regarding the roof certification, Structural Engineering governs this requirement."
 *
 * WHY THIS IS NOT PART OF 0055. That migration records PROVENANCE, the operator
 * placing a signed document into the platform. This records a JUDGEMENT by the
 * licensee, given five days later. They are separate acts by separate people
 * and they get separate migrations.
 *
 * NOTHING IS APPROVED BY THIS MIGRATION. 254-RC-001 stays awaiting_engineer.
 * Stating which discipline a protocol requires is not approving it, and the
 * approval remains an act in his own session through eng_approve_protocol.
 *
 * WHAT IT OPENS AND WHAT IT DOES NOT. protocol-gate.ts filters active engineers
 * by sealsOnly.includes(requires_discipline), and the register records
 * sealsOnly ["structural"] for him, so the DISCIPLINE block clears. The service
 * line does not open: it still needs an approved protocol.
 */

/*
 * ASSERT THE TARGET BEFORE WRITING. The row must exist, be the document this
 * repository holds, and still be awaiting its engineer. A migration that
 * silently updated nothing would be indistinguishable from one that worked.
 */
do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-RC-001'
    and version_label   = '1.1'
    and document_sha256 = 'd050a21a2b2d43114de47989ca731f41e26951f195c90187e99c11705011e4ef'
    and status          = 'awaiting_engineer';
  if n <> 1 then
    raise exception
      'eng: expected exactly one % v% awaiting its engineer under the declared digest, found %.',
      '254-RC-001', '1.1', n;
  end if;
end;
$$;

update eng_protocol_templates
   set requires_discipline = 'structural'
 where document_number = '254-RC-001'
   and version_label   = '1.1'
   and status          = 'awaiting_engineer';

/*
 * AND ASSERT WHAT WE JUST DID, because an UPDATE with a WHERE clause is silent
 * about whether it matched anything.
 */
do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number    = '254-RC-001'
    and version_label      = '1.1'
    and requires_discipline = 'structural';
  if n <> 1 then
    raise exception 'eng: % row(s) carry the discipline and exactly one is required.', n;
  end if;
end;
$$;
