/*
 * ===========================================================================
 * 0065  THE SEVEN v1.1 PROTOCOLS ENTER THE PLATFORM AS DRAFTS.
 * ===========================================================================
 *
 * GENERATED BY scripts/emit-received-protocols-migration.mjs --write. Not hand
 * edited. The generator hashes each PDF in docs/protocols/incoming/v1.1 and
 * writes nothing if a digest disagrees with the transcription's declaration.
 *
 * 254-WP-001 v1.1, 254-WS-001 v1.1, 254-MH-001 v1.1, 254-SL-001 v1.1, 254-PL-001 v1.1, 254-RS-001 v1.1, 254-DS-001 v1.1.
 *
 * DRAFT IS THE TRUE STATUS: the engineer of record has not signed these. He
 * signs each in the portal from his own session, and that signature is a seal
 * record, not a column here. A draft row holds no signature date, no approver
 * and no publication date (0049's constraints), so this migration cannot open a
 * line. Offered lines stay roof only, in configuration.
 *
 * The version integer is each line's next free number when its insert runs,
 * because unique (service_slug, version) is per line and 254-WP-001 and
 * 254-WS-001 both describe windstorm-wpi-8.
 *
 * Each insert is guarded by NOT EXISTS and followed by an assertion that
 * exactly one draft row names that document at that version with its digest,
 * so applying it twice changes nothing and a silent miss rolls back.
 *
 * No table, column, constraint, index, trigger or function changes, so neither
 * the shape fingerprint nor any count moves; the read back is the rows.
 */

-- 254-WP-001 v1.1: Windstorm Inspection Protocol for Certificates of Compliance (Form WPI-8), Ongoing Construction
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-WP-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from 'e7515b42a3d319483c40dc2ded4d07527f8ada932410d64ad69ec9c45ccb3040';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-WP-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'windstorm-wpi-8', 'Windstorm Inspection Protocol for Certificates of Compliance (Form WPI-8), Ongoing Construction',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'windstorm-wpi-8'), 0) + 1,
  '1.1', 'draft', '254-WP-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal. Covers the ongoing construction tier of this line.', '254-WP-001', '2026-10-06', 'e7515b42a3d319483c40dc2ded4d07527f8ada932410d64ad69ec9c45ccb3040',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-WP-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-WP-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = 'e7515b42a3d319483c40dc2ded4d07527f8ada932410d64ad69ec9c45ccb3040';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-WP-001', '1.1';
  end if;
end;
$$;

-- 254-WS-001 v1.1: Windstorm Certification Protocol for Completed Construction (Form WPI-8E)
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-WS-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from 'f4cbe248957298bbae6d968350d3732ef3197b46684959c6ec083f494f3ed6b5';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-WS-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'windstorm-wpi-8', 'Windstorm Certification Protocol for Completed Construction (Form WPI-8E)',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'windstorm-wpi-8'), 0) + 1,
  '1.1', 'draft', '254-WS-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal. Covers the completed construction tier of this line.', '254-WS-001', '2026-10-06', 'f4cbe248957298bbae6d968350d3732ef3197b46684959c6ec083f494f3ed6b5',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-WS-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-WS-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = 'f4cbe248957298bbae6d968350d3732ef3197b46684959c6ec083f494f3ed6b5';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-WS-001', '1.1';
  end if;
end;
$$;

-- 254-MH-001 v1.1: Manufactured Home Foundation Certification Protocol
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-MH-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from '5c88c73d9815cfae6825ef82d4368dd66a98dce746deed91b3c351cf2df09d4a';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-MH-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'manufactured-home-foundation-certifications', 'Manufactured Home Foundation Certification Protocol',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'manufactured-home-foundation-certifications'), 0) + 1,
  '1.1', 'draft', '254-MH-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal.', '254-MH-001', '2026-10-06', '5c88c73d9815cfae6825ef82d4368dd66a98dce746deed91b3c351cf2df09d4a',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-MH-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-MH-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = '5c88c73d9815cfae6825ef82d4368dd66a98dce746deed91b3c351cf2df09d4a';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-MH-001', '1.1';
  end if;
end;
$$;

-- 254-SL-001 v1.1: Solar Structural Letter Protocol for Existing Roofs
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-SL-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from '7bac29a7021086a7a40906021de5be9c2c2efaba747db33877410dd7b5c4e8f3';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-SL-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'solar-structural-letters', 'Solar Structural Letter Protocol for Existing Roofs',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'solar-structural-letters'), 0) + 1,
  '1.1', 'draft', '254-SL-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal.', '254-SL-001', '2026-10-06', '7bac29a7021086a7a40906021de5be9c2c2efaba747db33877410dd7b5c4e8f3',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-SL-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-SL-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = '7bac29a7021086a7a40906021de5be9c2c2efaba747db33877410dd7b5c4e8f3';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-SL-001', '1.1';
  end if;
end;
$$;

-- 254-PL-001 v1.1: Structural Letter Protocol for Permits
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-PL-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from 'f1ff2e5883aac06ac1b468a74ea09535c074a468a31de4c04297bf4c74b11387';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-PL-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'structural-letters', 'Structural Letter Protocol for Permits',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'structural-letters'), 0) + 1,
  '1.1', 'draft', '254-PL-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal.', '254-PL-001', '2026-10-06', 'f1ff2e5883aac06ac1b468a74ea09535c074a468a31de4c04297bf4c74b11387',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-PL-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-PL-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = 'f1ff2e5883aac06ac1b468a74ea09535c074a468a31de4c04297bf4c74b11387';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-PL-001', '1.1';
  end if;
end;
$$;

-- 254-RS-001 v1.1: Repair Specification Protocol for Existing Structures
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-RS-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from 'c7913d6637f2a08b1cd09a49c1767c682895db864143005a07bba99def8c2dd2';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-RS-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'repair-specifications', 'Repair Specification Protocol for Existing Structures',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'repair-specifications'), 0) + 1,
  '1.1', 'draft', '254-RS-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal.', '254-RS-001', '2026-10-06', 'c7913d6637f2a08b1cd09a49c1767c682895db864143005a07bba99def8c2dd2',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-RS-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-RS-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = 'c7913d6637f2a08b1cd09a49c1767c682895db864143005a07bba99def8c2dd2';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-RS-001', '1.1';
  end if;
end;
$$;

-- 254-DS-001 v1.1: Structural Design Protocol for Residential and Light Commercial Work
do $$
declare
  wrong integer;
begin
  select count(*) into wrong
  from eng_protocol_templates
  where document_number = '254-DS-001'
    and version_label   = '1.1'
    and document_sha256 is distinct from '37dd6b2e44155108df1daa681277332ddb64450a0f58813979e538da469ee22b';
  if wrong > 0 then
    raise exception
      'eng: % row(s) already record % v% under a different document digest. Somebody must decide which document this protocol is.',
      wrong, '254-DS-001', '1.1';
  end if;
end;
$$;

insert into eng_protocol_templates (
  service_slug, name, version, version_label, status, summary, document_number, issue_date, document_sha256, firm_name_on_document, requires_discipline, document_signed_at
)
select
  'residential-light-commercial-design', 'Structural Design Protocol for Residential and Light Commercial Work',
  coalesce((select max(version) from eng_protocol_templates where service_slug = 'residential-light-commercial-design'), 0) + 1,
  '1.1', 'draft', '254-DS-001 v1.1, issued 2026-10-06, received as a PDF with the engineer''s typed name and no signature. A draft until he signs it in the portal.', '254-DS-001', '2026-10-06', '37dd6b2e44155108df1daa681277332ddb64450a0f58813979e538da469ee22b',
  '254 Engineering Services', null, null
where not exists (
  select 1 from eng_protocol_templates
  where document_number = '254-DS-001'
    and version_label   = '1.1'
);

do $$
declare
  n integer;
begin
  select count(*) into n
  from eng_protocol_templates
  where document_number = '254-DS-001'
    and version_label   = '1.1'
    and status          = 'draft'
    and document_sha256 = '37dd6b2e44155108df1daa681277332ddb64450a0f58813979e538da469ee22b';
  if n <> 1 then
    raise exception 'eng: % draft row(s) record % v% with its digest and exactly one is required.',
      n, '254-DS-001', '1.1';
  end if;
end;
$$;
