import { currentPartner } from "@/lib/partner-auth";
import {
  assetDownloadUrl,
  partnerSubmissions,
  performingFirmLine,
  publishedAssets,
} from "@/lib/ops-partner-assets";
import { EmptyState, Panel, RestrictedMode, StatusPill } from "@/components/portal/design";
import { CopyBlock } from "./CopyBlock";
import { SubmitForm } from "./SubmitForm";

export const dynamic = "force-dynamic";

const KIND_LABEL: Record<string, string> = {
  copy_block: "Wording",
  one_pager: "Document",
  logo: "Artwork",
  email_snippet: "Email wording",
  link_card: "Link",
};

/**
 * The approved material, and the way to ask about anything else.
 *
 * NON NEGOTIABLE 2 IS WHAT THIS SCREEN IS FOR
 * -------------------------------------------
 * No partner surface may render a service claim the public site could not. The
 * library is how that becomes a path somebody can follow rather than a rule
 * somebody has to remember: wording that would fail the firm's own voice audit
 * cannot be published here, so everything on this screen is safe to use as
 * written.
 *
 * AND THE LIMIT IS ON THE SCREEN, NOT ONLY IN THE DOCUMENTATION
 * -------------------------------------------------------------
 * None of this stops a partner writing whatever they like on their own website.
 * Saying so here is not a disclaimer, it is the reason the approval path is
 * worth using: the firm is asking rather than pretending it can enforce.
 */
export default async function PartnerMaterials() {
  const principal = await currentPartner();
  if (!principal) return null;

  const assets = await publishedAssets();
  const submissions = await partnerSubmissions(principal);

  const files = await Promise.all(
    assets
      .filter((a) => a.storageKey)
      .map(async (a) => ({ slug: a.slug, url: await assetDownloadUrl(a.storageKey!) })),
  );
  const urlFor = new Map(files.map((f) => [f.slug, f.url]));

  return (
    <>
      <RestrictedMode />

      <div>
        <h1 className="font-display text-[24px] leading-[1.2] font-bold text-[var(--navy)]">Materials</h1>
        <p className="mt-1.5 max-w-[70ch] text-[13.5px] leading-[1.6] text-[var(--secondary)]">
          Wording and artwork the firm has approved for you to use as written. Anything you write
          yourself can be sent here to be looked at before you publish it.
        </p>
      </div>

      {/*
        THE LINE THAT GOES ON EVERYTHING, FIRST ON THE SCREEN.

        Non negotiable 1: every partner facing surface names the performing firm
        near the offer, and not as fine print. It is generated by one function
        so that a screen, an export and an emailed one pager cannot each carry
        their own wording of the same fact.
      */}
      <Panel
        title="The line that goes on everything"
        description="On any page or document of yours that mentions this programme, near the offer rather than in a footer."
      >
        <CopyBlock text={performingFirmLine()} />
      </Panel>

      <Panel
        title="Approved material"
        description="Use it as written. Changing the wording is what the approval was for, so a changed version needs a new one."
      >
        {assets.length === 0 ? (
          <EmptyState
            title="Nothing published yet"
            body="The firm has not published any material to the library. The line above is approved and can be used today."
          />
        ) : (
          <ul className="flex flex-col gap-4">
            {assets.map((asset) => (
              <li key={asset.id} className="rounded-[var(--radius-card)] border border-[var(--border)] p-3">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <p className="text-[15px] font-bold text-[var(--navy)]">{asset.title}</p>
                  <StatusPill tone="inert">{KIND_LABEL[asset.kind] ?? asset.kind}</StatusPill>
                </div>
                {asset.summary ? (
                  <p className="mt-1 text-[13.5px] leading-[1.55] text-[var(--secondary)]">{asset.summary}</p>
                ) : null}

                <div className="mt-3">
                  {asset.body ? <CopyBlock text={asset.body} /> : null}
                  {asset.storageKey ? (
                    urlFor.get(asset.slug) ? (
                      <a
                        href={urlFor.get(asset.slug)!}
                        className="inline-flex min-h-[var(--tap-target)] items-center rounded-[var(--radius-control)] border border-[var(--border-strong)] px-3 text-[13.5px] font-semibold text-[var(--navy)] active:bg-[var(--canvas)]"
                      >
                        Download
                      </a>
                    ) : (
                      <p className="text-[13.5px] leading-[1.55] text-[var(--secondary)]">
                        This file could not be prepared for download just now. Reload the page, and
                        tell the firm if it keeps happening.
                      </p>
                    )
                  ) : null}
                </div>

                <p className="mt-3 text-[12px] text-[var(--secondary)]">
                  Version {asset.version}
                  {asset.publishedAt
                    ? `, published ${new Date(asset.publishedAt).toLocaleDateString("en-US", {
                        year: "numeric",
                        month: "long",
                        day: "numeric",
                      })}`
                    : ""}
                </p>
              </li>
            ))}
          </ul>
        )}
      </Panel>

      <Panel
        title="Send something for approval"
        description="Anything you have written, or a page you have already published. It is always accepted, whatever it says."
      >
        <SubmitForm />
      </Panel>

      <Panel title="What you have sent">
        {submissions.length === 0 ? (
          <EmptyState
            title="Nothing sent yet"
            body="Anything you send appears here with the firm's answer on it, and the answer stays whatever happens afterwards."
          />
        ) : (
          <ul className="flex flex-col gap-2.5">
            {submissions.map((s) => (
              <li key={s.id} className="rounded-[var(--radius-card)] border border-[var(--border)] p-3">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <p className="text-[15px] font-bold text-[var(--navy)]">{s.title}</p>
                  <StatusPill
                    tone={
                      s.status === "approved"
                        ? "good"
                        : s.status === "changes_requested"
                          ? "failed"
                          : "pending"
                    }
                  >
                    {s.status === "approved"
                      ? "Approved"
                      : s.status === "changes_requested"
                        ? "Changes needed"
                        : s.status === "withdrawn"
                          ? "Withdrawn"
                          : "With the firm"}
                  </StatusPill>
                </div>

                {s.advice ? (
                  <p className="mt-2 rounded-[var(--radius-control)] border border-[var(--warn-border)] bg-[var(--gold-wash)] px-3 py-2 text-[13.5px] leading-[1.55] text-[var(--warn-ink)]">
                    Before anybody has read it: {s.advice}
                  </p>
                ) : null}

                {s.decisionNote ? (
                  <p className="mt-2 text-[13.5px] leading-[1.55] text-[var(--ink)]">{s.decisionNote}</p>
                ) : null}

                <p className="mt-2 text-[12px] text-[var(--secondary)]">
                  Sent{" "}
                  {new Date(s.createdAt).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                  })}
                </p>
              </li>
            ))}
          </ul>
        )}
      </Panel>

      <Panel title="What approval does and does not do">
        <p className="max-w-[74ch] text-[13.5px] leading-[1.65] text-[var(--ink)]">
          Approved wording is wording the firm has checked against the same rules its own website is
          held to. Using it as written means you are not making a claim the firm could not make
          itself, which is the thing that matters while its registration is pending.
        </p>
        <p className="mt-3 max-w-[74ch] text-[13.5px] leading-[1.65] text-[var(--ink)]">
          What this cannot do is police what is published elsewhere, and nothing here should be read
          as suggesting otherwise. The programme agreement is what governs that, and the firm can
          withdraw approval at any time.
        </p>
      </Panel>
    </>
  );
}
